import { Navbar } from "@/components/landing/navbar"
import { Footer } from "@/components/landing/footer"

export const metadata = { title: "Terms of Service" }

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="pt-24 md:pt-28 pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <h1 className="text-3xl md:text-4xl font-serif text-primary mb-2">Terms of Service</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>
          <div className="space-y-8 text-sm text-foreground/90 leading-relaxed">
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">1. Agreement</h2>
              <p>By using SajuAstrology.com, you agree to these Terms. Operated by Rimfactory (Reg. No. 402-44-01247), Seoul, Korea.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">2. Service</h2>
              <p>Personalized readings based on Korean Saju (Four Pillars of Destiny) principles, generated with AI technology. Includes free readings, premium readings, and master consultations.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">3. Important Disclaimer</h2>
              <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4">
                <p>Readings are for <strong>entertainment and self-reflection only</strong>. Not professional advice. <strong>Do not</strong> make financial, medical, legal, or relationship decisions based solely on readings. Rimfactory disclaims all liability for decisions resulting from our content.</p>
              </div>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">4. Accounts</h2>
              <p>Google sign-in required to save readings. Must be 13+ to create an account.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">5. Pricing</h2>
              <p className="mb-2"><strong>Free Reading:</strong> Personality, year forecast, and element guidance.</p>
              <p className="mb-2"><strong>Premium Reading ($9.99):</strong> Career, love, health, 10-year forecast, 6-month flow, hidden talent. One-time per reading.</p>
              <p className="mb-2"><strong>Master Consultation ($29.99):</strong> 5 sessions for specific life questions. One-time purchase.</p>
              <p className="text-muted-foreground">All prices USD. Subject to change with notice.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">6. Refunds</h2>
              <p>Payments via Stripe. Digital content delivered instantly — sales are generally final. For technical issues, contact <a href="mailto:info@rimfactory.co.kr" className="text-primary hover:underline">info@rimfactory.co.kr</a> within 7 days.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">7. AI Content</h2>
              <p>Readings generated by AI (Anthropic Claude). May contain inaccuracies. Each reading is unique and may differ across sessions.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">8. Liability</h2>
              <p>Maximum liability limited to amounts paid in the preceding 12 months. Governed by Korean law, Seoul courts.</p>
            </section>
            <section>
              <h2 className="text-lg font-serif text-primary mb-3">Contact</h2>
              <div className="bg-card/50 border border-border rounded-xl p-4">
                <p><strong>Rimfactory</strong> — 243, 1F, Sindorim Technomart, 97 Saemallo, Guro-gu, Seoul</p>
                <p className="mt-1">Email: <a href="mailto:info@rimfactory.co.kr" className="text-primary hover:underline">info@rimfactory.co.kr</a> · Phone: +82-10-4648-6793</p>
              </div>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  )
}
