"use client"

import { useState, useEffect } from "react"
import { Navbar } from "@/components/landing/navbar"
import { Footer } from "@/components/landing/footer"

// ─── locale detection (same as whitepaper-client pattern) ───────────────────
function detectLocale(): "en" | "ko" | "ja" {
  if (typeof window === "undefined") return "en"
  try {
    const urlLang = new URLSearchParams(window.location.search).get("lang")
    if (urlLang === "ko" || urlLang === "ja" || urlLang === "en") return urlLang
    const stored = localStorage.getItem("locale")
    if (stored === "ko" || stored === "ja") return stored
  } catch {}
  return "en"
}

// ─── Language toggle button ─────────────────────────────────────────────────
function LangToggle({
  active,
  onChange,
}: {
  active: "en" | "ko" | "ja"
  onChange: (l: "en" | "ko" | "ja") => void
}) {
  const langs: { key: "en" | "ko" | "ja"; label: string }[] = [
    { key: "en", label: "EN" },
    { key: "ko", label: "KO" },
    { key: "ja", label: "JA" },
  ]
  return (
    <div className="flex gap-1 mb-8">
      {langs.map(({ key, label }) => (
        <button
          key={key}
          onClick={() => onChange(key)}
          className={`px-3 py-1 rounded-full text-xs font-medium border transition-colors ${
            active === key
              ? "bg-primary text-primary-foreground border-primary"
              : "border-border text-muted-foreground hover:text-foreground"
          }`}
        >
          {label}
        </button>
      ))}
    </div>
  )
}

// ─── ENGLISH content ─────────────────────────────────────────────────────────
function TermsEN() {
  return (
    <div className="space-y-8 text-sm text-foreground/90 leading-relaxed">
      <section>
        <h2 className="text-lg font-serif text-primary mb-3">1. Agreement</h2>
        <p className="mb-2">By accessing or using SajuAstrology.com (the &ldquo;Website&rdquo;) or the SajuAstrology mobile application (the &ldquo;App&rdquo;, collectively the &ldquo;Service&rdquo;), you agree to be legally bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree, do not use the Service.</p>
        <p>The Service is operated by Rimfactory (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;Rimfactory&rdquo;), a business entity registered in the Republic of Korea with the following details:</p>
        <div className="bg-card/50 border border-border rounded-xl p-4 mt-2 text-xs">
          <p><strong>Business name:</strong> Rimfactory</p>
          <p><strong>Representative:</strong> Yun Choyeon (Chandler Yun)</p>
          <p><strong>Business Registration No.:</strong> 402-44-01247</p>
          <p><strong>Mail-order Business Report No.:</strong> 2025-Seoul Guro-2056</p>
          <p><strong>Address:</strong> 243, 1F, Sindorim Technomart, 97 Saemal-ro, Guro-gu, Seoul 08213, Republic of Korea</p>
          <p><strong>Email:</strong> <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a></p>
          <p><strong>Phone:</strong> +82-10-4648-6793</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">2. The Service</h2>
        <p className="mb-2">SajuAstrology provides AI-generated content based on the principles of Korean Saju (\uc0ac\uc8fc \u2014 Four Pillars of Destiny), a traditional East Asian cosmological framework. The Service is available on the Website and through native mobile apps on iOS (Apple App Store) and Android (Google Play) in ten languages: English, Korean (\ud55c\uad6d\uc5b4), Japanese (\u65e5\u672c\u8a9e), Spanish, French, Portuguese, Traditional Chinese (\u7e41\u9ad4\u4e2d\u6587), Russian, Hindi (\u0939\u093f\u0928\u094d\u0926\u0940), and Indonesian.</p>
        <p>Offerings include free Saju readings, free compatibility analysis, paid Compatibility Full unlock, the paid Full Destiny Reading, paid Master 5 Pack consultations, and the Soram Companion subscription. Pricing details are in \u00a76.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">3. Entertainment Only \u2014 Important Disclaimer</h2>
        <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4 space-y-2">
          <p>All content generated by the Service is provided strictly for <strong>entertainment, cultural exploration, and personal self-reflection purposes</strong>. It is <strong>not</strong> professional advice of any kind and must not be treated as such.</p>
          <p><strong>You must not rely on any reading, consultation, or daily fortune to make decisions regarding:</strong> medical, psychological, or health matters; legal or regulatory matters; financial, investment, insurance, or tax decisions; relationships, marriage, or reproductive choices; employment, career, or business decisions; child welfare, custody, or educational choices; or any other matter with meaningful real-world consequences. Always consult a qualified, licensed professional.</p>
          <p>Saju is a traditional East Asian cultural practice, not a religious practice or divine prophecy, and has no scientifically validated predictive power. Acceptance of fortune-telling, divination, or astrology varies widely across cultures and religions. You are solely responsible for determining whether use of the Service is appropriate for you and consistent with your personal, cultural, or religious values.</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">4. Eligibility and Age</h2>
        <p className="mb-2">By signing in to the Service, you represent that you are at least <strong>14 years of age</strong> (the minimum digital-consent age under Korea&rsquo;s Personal Information Protection Act) and that you have the legal capacity to agree to these Terms. EU/EEA residents must also meet the minimum digital-consent age in their member state (generally 16, lower in some countries).</p>
        <p>We do not knowingly collect information from children under the applicable minimum age. If we learn that such data has been collected in violation of applicable law, we will delete it promptly. Parents or legal guardians who believe a minor has submitted information should contact <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">5. Accounts</h2>
        <p className="mb-2">Accounts are created exclusively via Google OAuth or Apple Sign-in. We do not operate username/password accounts. You are responsible for safeguarding access to the third-party identity provider account used to sign in. You agree to provide accurate information, including the birth data you voluntarily supply for readings. False or fraudulent use of the Service is grounds for immediate termination.</p>
        <p className="mb-2">Your account syncs between Website and App when you use the same sign-in method. To prevent account confusion across platforms, the iOS App offers Apple Sign-in only and the Android App offers Google Sign-in only; the Website offers both. Choose your preferred sign-in method consistently to keep one account.</p>
        <p>Your primary saju (the birth data registered to your account for the dashboard, daily fortune, and Soram chat) is set once at sign-up. To change your primary saju thereafter, please contact <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>. You may delete your account and all associated personal data at any time from your dashboard, or by contacting <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>. Deletion will be completed within 30 days.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">6. Pricing</h2>
        <p className="mb-2"><strong>Free tier:</strong> personal Saju reading (personality, Five Elements, year forecast), full compatibility analysis (love, work, friendship, conflict, yearly forecast), personalized daily fortune, one Soram conversation per day, and shareable result pages.</p>
        <p className="mb-2"><strong>Compatibility Full (US$2.99):</strong> one-time payment per pair. Unlocks the detailed paid sections of an existing compatibility result. Lifetime access from your account.</p>
        <p className="mb-2"><strong>Full Destiny Reading (US$9.99):</strong> one-time payment per reading. Includes career and wealth blueprint, love and relationship insights, health timing guidance, 10-year fortune cycle analysis, monthly energy calendar, and hidden-talent analysis. Permanent access to your reading page.</p>
        <p className="mb-2"><strong>Master 5 Pack (US$29.99):</strong> one-time payment. Includes five (5) AI-generated consultation rounds for specific life questions (career, love, timing, finances, health, etc.), each grounded in your birth chart and the RimSaju Engine&rsquo;s 562 classical passages &mdash; <strong>plus the Full Destiny Reading is included</strong>. Consultation credits never expire and remain associated with your account indefinitely.</p>
        <p className="mb-2"><strong>Soram Companion (US$4.99/month \u2014 auto-renewable subscription):</strong> unlimited daily Soram chat and one (1) Master-tier consultation credit per billing month. Auto-renews monthly unless cancelled at least 24 hours before the end of the current period.</p>
        <p className="text-muted-foreground">All prices are in U.S. Dollars. Prices are identical across the Website and the App.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">7. Payments and Refunds</h2>
        <p className="mb-2"><strong>Web payments</strong> are processed by PayPal Checkout. <strong>App payments</strong> are processed by the Apple App Store (iOS) or Google Play (Android). We do not receive, handle, or store your payment card details.</p>
        <p className="mb-2">Digital content is delivered immediately upon purchase.</p>
        <ul className="list-disc pl-6 mb-2 space-y-1">
          <li>If a technical error prevents your reading from being delivered, contact <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> within 7 days of purchase for a refund.</li>
          <li>For in-app purchases (iOS/Android), refund requests must be submitted through Apple or Google.</li>
          <li><strong>Soram Companion \u2014 how to cancel:</strong>
            <ul className="list-disc pl-6 mt-1 space-y-1">
              <li><strong>iOS App Store:</strong> Settings \u2192 [your name] \u2192 Subscriptions \u2192 Soram Companion \u2192 Cancel Subscription.</li>
              <li><strong>Google Play:</strong> Play Store \u2192 profile icon \u2192 Payments &amp; subscriptions \u2192 Subscriptions \u2192 Soram Companion \u2192 Cancel.</li>
              <li><strong>Web (PayPal):</strong> cancel from your dashboard or email <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>, or via PayPal \u2192 Payments \u2192 Manage automatic payments.</li>
            </ul>
            Cancellation stops the next billing cycle; you retain access through the end of the current paid period.
          </li>
          <li><strong>Korean consumers:</strong> Rights under Korea&rsquo;s Act on the Consumer Protection in Electronic Commerce are preserved in full.</li>
          <li><strong>EU/EEA consumers:</strong> Rights under Directive 2011/83/EU are preserved.</li>
        </ul>
        <p>Chargebacks initiated without first contacting <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> may result in account suspension.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">8. AI-Generated Content and Model Providers</h2>
        <p className="mb-2">All readings are generated by large language models \u2014 primarily Google Gemini with Anthropic Claude as a fallback and verification layer. Our proprietary &ldquo;RimSaju Engine&rdquo; combines deterministic Saju calculations with retrieval-augmented generation from 562 classical passages.</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>AI output may contain inaccuracies or hallucinations.</li>
          <li>Each reading is generated uniquely at the moment of request.</li>
          <li>Your birth data is transmitted to the Models as prompt input. We do not knowingly submit it for training their foundation models.</li>
          <li>AI output is not a substitute for professional advice (see \u00a73).</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">9. User Conduct and Acceptable Use</h2>
        <p className="mb-2">You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Submit another person&rsquo;s birth data without their informed consent;</li>
          <li>Use the Service to harass or defame identifiable third parties;</li>
          <li>Scrape, resell, or redistribute readings in bulk;</li>
          <li>Reverse-engineer the underlying prompts, embeddings, or RAG sources;</li>
          <li>Upload unlawful, hateful, or sexually explicit content;</li>
          <li>Circumvent rate limits, payment validation, or IAP verification.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">10. Intellectual Property</h2>
        <p>The SajuAstrology name, brand, RimSaju Engine, website design, code, classical-passage curation, and all original content are owned by Rimfactory and protected by copyright, trademark, and related laws. We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service for your own personal, non-commercial use. AI-generated readings delivered to you may be shared via the share links provided, but may not be used to train other AI models or resold.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">11. Changes and Termination</h2>
        <p>We may modify, suspend, or discontinue any part of the Service at any time. Material changes will be announced on the Website with a new &ldquo;Last updated&rdquo; date. Continued use after changes constitutes acceptance. We may suspend or terminate accounts for breach of these Terms, suspected fraud, or as required by law.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">12. Warranty Disclaimer</h2>
        <p>THE SERVICE IS PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY OF AI-GENERATED CONTENT.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">13. Limitation of Liability</h2>
        <p className="mb-2">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, RIMFACTORY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. OUR AGGREGATE LIABILITY SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO RIMFACTORY IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR US$100, WHICHEVER IS GREATER.</p>
        <p>Nothing in this section limits liability that cannot be excluded under applicable consumer-protection law.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">14. Indemnification</h2>
        <p>To the maximum extent permitted by law, you agree to indemnify Rimfactory from claims arising from (a) your violation of these Terms, (b) your misuse of the Service, (c) your infringement of third-party rights, or (d) reliance on readings in violation of \u00a73. This does not apply to the extent prohibited by consumer-protection law in your country of residence.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">15. Dispute Resolution</h2>
        <p className="mb-2"><strong>Informal resolution first.</strong> Contact <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> and allow at least 30 days for good-faith resolution before initiating formal proceedings.</p>
        <p className="mb-2"><strong>Governing law.</strong> These Terms are governed by the laws of the Republic of Korea. Mandatory consumer-protection rights in your country of residence are not affected.</p>
        <p className="mb-2"><strong>Jurisdiction.</strong> The Seoul Central District Court of Korea shall have exclusive jurisdiction, subject to mandatory local consumer-protection laws.</p>
        <p><strong>No class actions.</strong> To the maximum extent permitted by law, disputes will be resolved on an individual basis only.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">16. Third-Party App Store Terms</h2>
        <p>If you download the App from Apple App Store or Google Play, additional terms from the respective store apply. Apple and Google are third-party beneficiaries of these Terms to the extent required by their developer agreements.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">17. Severability and Entire Agreement</h2>
        <p>If any provision is found unenforceable, the remaining provisions remain in effect. These Terms, together with our Privacy Policy, constitute the entire agreement between you and Rimfactory regarding the Service.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">Contact</h2>
        <div className="bg-card/50 border border-border rounded-xl p-4">
          <p><strong>Rimfactory</strong> \u2014 243, 1F, Sindorim Technomart, 97 Saemal-ro, Guro-gu, Seoul 08213, Republic of Korea</p>
          <p className="mt-1">Business Registration No.: 402-44-01247 \u00b7 Mail-order Business Report No.: 2025-Seoul Guro-2056</p>
          <p className="mt-1">Email: <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u00b7 Phone: +82-10-4648-6793</p>
        </div>
      </section>
    </div>
  )
}

// ─── KOREAN content ──────────────────────────────────────────────────────────
function TermsKO() {
  return (
    <div className="space-y-8 text-sm text-foreground/90 leading-relaxed break-keep">
      <section>
        <h2 className="text-lg font-serif text-primary mb-3">1. \uc774\uc6a9 \ub3d9\uc758</h2>
        <p className="mb-2">SajuAstrology.com(\uc774\ud558 &ldquo;\uc6f9\uc0ac\uc774\ud2b8&rdquo;) \ub610\ub294 SajuAstrology \ubaa8\ubc14\uc77c \uc571(\uc774\ud558 &ldquo;\uc571&rdquo;, \ud1b5\uce6d &ldquo;\uc11c\ube44\uc2a4&rdquo;)\uc744 \uc774\uc6a9\ud568\uc73c\ub85c\uc368 \ubcf8 \uc774\uc6a9\uc57d\uad00(\uc774\ud558 &ldquo;\uc57d\uad00&rdquo;)\uc5d0 \ub3d9\uc758\ud558\ub294 \uac83\uc73c\ub85c \ubc95\uc801 \ud6a8\ub825\uc774 \ubc1c\uc0dd\ud569\ub2c8\ub2e4. \ub3d9\uc758\ud558\uc9c0 \uc54a\ub294 \uacbd\uc6b0 \uc11c\ube44\uc2a4\ub97c \uc774\uc6a9\ud558\uc9c0 \ub9c8\uc2ed\uc2dc\uc624.</p>
        <p>\uc11c\ube44\uc2a4\ub294 \ub300\ud55c\ubbfc\uad6d\uc5d0 \ub4f1\ub85d\ub41c \uc0ac\uc5c5\uc790 Rimfactory(\uc774\ud558 &ldquo;\ud68c\uc0ac&rdquo;)\uac00 \uc6b4\uc601\ud569\ub2c8\ub2e4.</p>
        <div className="bg-card/50 border border-border rounded-xl p-4 mt-2 text-xs">
          <p><strong>\uc0c1\ud638:</strong> Rimfactory</p>
          <p><strong>\ub300\ud45c\uc790:</strong> \uc724\ucd08\uc5f0 (Yun Choyeon / Chandler Yun)</p>
          <p><strong>\uc0ac\uc5c5\uc790\ub4f1\ub85d\ubc88\ud638:</strong> 402-44-01247</p>
          <p><strong>\ud1b5\uc2e0\ud310\ub9e4\uc5c5 \uc2e0\uace0\ubc88\ud638:</strong> 2025-\uc11c\uc6b8\uad6c\ub85c-2056</p>
          <p><strong>\uc8fc\uc18c:</strong> \uc11c\uc6b8\ud2b9\ubcc4\uc2dc \uad6c\ub85c\uad6c \uc0c8\ub9d0\ub85c 97 \uc2e0\ub3c4\ub9bc\ud14c\ud06c\ub178\ub9c8\ud2b8 1\ub3d9 243\ud638, 08213</p>
          <p><strong>\uc774\uba54\uc77c:</strong> <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a></p>
          <p><strong>\uc804\ud654:</strong> +82-10-4648-6793</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">2. \uc11c\ube44\uc2a4 \ub0b4\uc6a9</h2>
        <p className="mb-2">SajuAstrology\ub294 \ud55c\uad6d \uc804\ud1b5 \uba85\ub9ac\ud559(\uc0ac\uc8fc\ud314\uc790)\uc5d0 \uae30\ubc18\ud55c AI \uc0dd\uc131 \ucf58\ud150\uce20\ub97c \uc81c\uacf5\ud569\ub2c8\ub2e4. \uc6f9\uc0ac\uc774\ud2b8\uc640 iOS(App Store) \u00b7 Android(Google Play) \uc571\uc744 \ud1b5\ud574 \uc601\uc5b4\u00b7\ud55c\uad6d\uc5b4\u00b7\uc77c\ubcf8\uc5b4 \ub4f1 10\uac1c \uc5b8\uc5b4\ub85c \uc81c\uacf5\ub429\ub2c8\ub2e4.</p>
        <p>\ubb34\ub8cc \uc0ac\uc8fc \ub9ac\ub529, \ubb34\ub8cc \uad81\ud569, \uc720\ub8cc Compatibility Full, \uc720\ub8cc Full Destiny Reading, Master 5 Pack \uc0c1\ub2f4, Soram Companion \uad6c\ub3c5\uc744 \uc81c\uacf5\ud569\ub2c8\ub2e4. \uac00\uaca9 \uc138\ubd80\uc0ac\ud56d\uc740 \u00a76\uc744 \ucc38\uc870\ud558\uc2ed\uc2dc\uc624.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">3. \uc624\ub77d \ubaa9\uc801 \uc804\uc6a9 \uc548\ub0b4 \u2014 \uc911\uc694 \uace0\uc9c0</h2>
        <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4 space-y-2">
          <p>\ubcf8 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ucf58\ud150\uce20\ub294 <strong>\uc624\ub77d\u00b7\ubb38\ud654 \ud0d0\uad6c\u00b7\uc790\uae30 \uc131\ucc30 \ubaa9\uc801</strong>\uc73c\ub85c\ub9cc \uc81c\uacf5\ub429\ub2c8\ub2e4. \uc5b4\ub5a0\ud55c \uc885\ub958\uc758 \uc804\ubb38\uc801 \uc870\uc5b8\ub3c4 \uc544\ub2c8\uba70 \uadf8\ub807\uac8c \uc774\uc6a9\ud574\uc11c\ub294 \uc548 \ub429\ub2c8\ub2e4.</p>
          <p><strong>\ub2e4\uc74c \uc0ac\ud56d\uc5d0 \ub300\ud55c \uacb0\uc815\uc744 \ub0b4\ub9ac\ub294 \ub370 \ubcf8 \uc11c\ube44\uc2a4\ub97c \uc0ac\uc6a9\ud558\uc9c0 \ub9c8\uc2ed\uc2dc\uc624:</strong> \uc758\ub8cc\u00b7\uc815\uc2e0 \uac74\uac15, \ubc95\ub960\uc801 \ubb38\uc81c, \uae08\uc735\u00b7\ud22c\uc790\u00b7\uc138\ubb34 \uc758\uc0ac\uacb0\uc815, \uad00\uacc4\u00b7\uacb0\ud63c\u00b7\ucd9c\uc0b0, \uace0\uc6a9\u00b7\ucee4\ub9ac\uc5b4\u00b7\uc0ac\uc5c5, \uc544\ub3d9\ubcf5\uc9c0\u00b7\uad50\uc721 \ub4f1 \uc911\uc694\ud55c \ud604\uc2e4\uc801 \uc131\uacfc\ub97c \ubbf8\uce58\ub294 \ubaa8\ub4e0 \uc0ac\ud56d. \ubc18\ub4dc\uc2dc \uc790\uaca9\uc744 \uac16\ucd98 \uc804\ubb38\uac00\uc640 \uc0c1\ub2f4\ud558\uc2ed\uc2dc\uc624.</p>
          <p>\uc0ac\uc8fc\ub294 \ub3d9\uc544\uc2dc\uc544 \uc804\ud1b5 \ubb38\ud654 \uc2e4\ucc9c\uc73c\ub85c, \uc885\uad50\uc801 \uc758\uc2dd\uc774\ub098 \uad50\ub9ac\uac00 \uc544\ub2c8\uba70 \uacfc\ud559\uc801\uc73c\ub85c \uc785\uc99d\ub41c \uc608\uce21\ub825\uc774 \uc5c6\uc2b5\ub2c8\ub2e4. \ubcf8 \uc11c\ube44\uc2a4 \uc774\uc6a9\uc774 \ubcf8\uc778\uc758 \uac00\uce58\uad00\u00b7\uc885\uad50\uc801 \uc2e0\ub150\uc5d0 \uc801\ud569\ud55c\uc9c0 \uc5ec\ubd80\ub294 \uc774\uc6a9\uc790 \uc2a4\uc2a4\ub85c \ud310\ub2e8\ud558\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">4. \uc774\uc6a9 \uc790\uaca9</h2>
        <p className="mb-2">\uc11c\ube44\uc2a4\uc5d0 \ub85c\uadf8\uc778\ud568\uc73c\ub85c\uc368 \uadc0\ud558\ub294 \uac1c\uc778\uc815\ubcf4\ubcf4\ud638\ubc95\uc0c1 \ucd5c\uc18c \ub514\uc9c0\ud138 \ub3d9\uc758\uc5f0\ub839(<strong>14\uc138 \uc774\uc0c1</strong>)\uc784\uc744 \ud655\uc778\ud569\ub2c8\ub2e4. EU/EEA \uac70\uc8fc\uc790\ub294 \ud574\ub2f9 \ud68c\uc6d0\uad6d\uc758 \ucd5c\uc18c \uc5f0\ub839(\uc77c\ubc18\uc801\uc73c\ub85c 16\uc138, \uc77c\ubd80 \uad6d\uac00\ub294 \ud558\ud5a5)\uc744 \ucda9\uc871\ud574\uc57c \ud569\ub2c8\ub2e4.</p>
        <p>\ubbf8\uc131\ub144\uc790\uc758 \uc815\ubcf4\uac00 \uc5f4\ub78c\ub41c \uacbd\uc6b0 \ubc95\ub839\uc5d0 \ub530\ub77c \uc989\uc2dc \uc0ad\uc81c\ud569\ub2c8\ub2e4. \ubcf4\ud638\uc790\ub294 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \ubb38\uc758\ud558\uc2ed\uc2dc\uc624.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">5. \uacc4\uc815</h2>
        <p className="mb-2">\uacc4\uc815\uc740 Google OAuth \ub610\ub294 Apple \ub85c\uadf8\uc778\uc73c\ub85c\ub9cc \uc0dd\uc131\ub429\ub2c8\ub2e4. \uc544\uc774\ub514/\ube44\ubc00\ubc88\ud638 \uc2dc\uc2a4\ud15c\uc740 \uc6b4\uc601\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \ub3d9\uc77c\ud55c \ub85c\uadf8\uc778 \ubc29\uc2dd\uc744 \uc0ac\uc6a9\ud558\uba74 \uc6f9\uacfc \uc571 \uac04 \uacc4\uc815\uc774 \ub3d9\uae30\ud654\ub429\ub2c8\ub2e4. \ud50c\ub7ab\ud3fc\ubcc4 \ud63c\ub78c\uc744 \ubc29\uc9c0\ud558\uae30 \uc704\ud574 iOS \uc571\uc740 Apple \ub85c\uadf8\uc778\ub9cc, Android \uc571\uc740 Google \ub85c\uadf8\uc778\ub9cc \uc81c\uacf5\ud569\ub2c8\ub2e4.</p>
        <p>\ub300\uc2dc\ubcf4\ub4dc\u00b7\uc77c\uc77c\uc6b4\uc138\u00b7\uc18c\ub78c \uc5f0\ub3d9\uc5d0 \uc0ac\uc6a9\ub418\ub294 \uc8fc\uc0ac\uc8fc\ub294 \uac00\uc785 \uc2dc 1\ud68c \uc785\ub825 \ud6c4 \ubcc0\uacbd\uc744 \uc6d0\ud558\uc2dc\uba74 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \ubb38\uc758\ud558\uc2ed\uc2dc\uc624. \uacc4\uc815 \uc0ad\uc81c\ub294 \ub300\uc2dc\ubcf4\ub4dc \ub610\ub294 \uc774\uba54\uc77c \uc694\uccad\uc73c\ub85c \uac00\ub2a5\ud558\uba70, 30\uc77c \uc774\ub0b4 \uc644\ub8cc\ub429\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">6. \uac00\uaca9</h2>
        <p className="mb-2"><strong>\ubb34\ub8cc:</strong> \uc0ac\uc8fc \ub9ac\ub529(\uc131\uaca9\u00b7\uc624\ud589\u00b7\uc5f0\ub3c4\uc6b4\uc138), \uad81\ud569 \uc804\uccb4, \uc77c\uc77c\uc6b4\uc138, \ud558\ub8e8 1\ud68c \uc18c\ub78c \ub300\ud654, \uacb0\uacfc \uacf5\uc720.</p>
        <p className="mb-2"><strong>Compatibility Full (US$2.99):</strong> \ud398\uc5b4\ub2f9 1\ud68c \uacb0\uc81c. \uc874\uc7ac\ud558\ub294 \uad81\ud569 \uacb0\uacfc\uc758 \uc720\ub8cc \uc601\uc5ed \uc2b5\ub2c8\ub2e4. \uacc4\uc815 \uc720\uc9c0 \uc2dc \uc601\uad6c \uc811\uadfc.</p>
        <p className="mb-2"><strong>Full Destiny Reading (US$9.99):</strong> \ub9ac\ub529\ub2f9 1\ud68c \uacb0\uc81c. \ucee4\ub9ac\uc5b4\u00b7\ubd80\uc758, \uc5f0\uc560\u00b7\uad00\uacc4, \uac74\uac15 \ud0c0\uc774\ubc0d, 10\ub144 \ub300\uc6b4 \ubd84\uc11d, \uc6d4\ubcc4 \uc5d0\ub108\uc9c0 \uce98\ub9b0\ub354, \uc228\uaca8\uc9c4 \uc7ac\ub2a5 \ubd84\uc11d \ud3ec\ud568. \ub9ac\ub529 \ud398\uc774\uc9c0 \uc601\uad6c \ubcf4\uc874.</p>
        <p className="mb-2"><strong>Master 5 Pack (US$29.99):</strong> 1\ud68c \uacb0\uc81c. AI \uc0c1\ub2f4 5\ud68c + Full Destiny Reading \ud3ec\ud568. \uc0c1\ub2f4 \ud06c\ub808\ub527\uc740 \ub9cc\ub8cc \uc5c6\uc774 \uacc4\uc815\uc5d0 \uc720\uc9c0\ub429\ub2c8\ub2e4.</p>
        <p className="mb-2"><strong>Soram Companion (US$4.99/\uc6d4 \uc790\ub3d9 \uac31\uc2e0 \uad6c\ub3c5):</strong> \uc18c\ub78c \ub300\ud654 \ubb34\uc81c\ud55c + \uc6d4 1\ud68c Master \uad09 \uc0c1\ub2f4 \ud06c\ub808\ub527. \ud604\uc7ac \uae30\uac04 \uc885\ub8cc 24\uc2dc\uac04 \uc804\uc5d0 \ucde8\uc18c\ud558\uc9c0 \uc54a\uc73c\uba74 \ub3d9\uc77c \uac00\uaca9\uc73c\ub85c \uc790\ub3d9 \uac31\uc2e0\ub429\ub2c8\ub2e4.</p>
        <p className="text-muted-foreground">\ubaa8\ub4e0 \uac00\uaca9\uc740 \ubbf8\uad6d \ub2ec\ub7ec(USD) \uae30\uc900\uc774\uba70, \uc6f9\uacfc \uc571\uc5d0\uc11c \ub3d9\uc77c\ud569\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">7. \uacb0\uc81c \ubc0f \ud658\ubd88</h2>
        <p className="mb-2"><strong>\uc6f9 \uacb0\uc81c</strong>\ub294 PayPal Checkout\ub85c \ucc98\ub9ac\ub429\ub2c8\ub2e4. <strong>\uc571 \uacb0\uc81c</strong>\ub294 Apple App Store(iOS) \ub610\ub294 Google Play(Android)\ub97c \ud1b5\ud574 \uc9c4\ud589\ub429\ub2c8\ub2e4. \ud68c\uc0ac\ub294 \uacb0\uc81c \uce74\ub4dc \uc815\ubcf4\ub97c \ubc1b\uac70\ub098 \uc800\uc7a5\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>
        <p className="mb-2">\ub514\uc9c0\ud138 \ucf58\ud150\uce20\ub294 \uacb0\uc81c \uc989\uc2dc \uc81c\uacf5\ub429\ub2c8\ub2e4.</p>
        <ul className="list-disc pl-6 mb-2 space-y-1">
          <li>\uae30\uc220\uc801 \uc624\ub958\ub85c \ub9ac\ub529\uc774 \uc81c\uacf5\ub418\uc9c0 \uc54a\uc740 \uacbd\uc6b0, \uacb0\uc81c \ud6c4 7\uc77c \uc774\ub0b4 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \ubb38\uc758\ud558\uc2dc\uba74 \ud658\ubd88\ud574 \ub4dc\ub9bd\ub2c8\ub2e4.</li>
          <li>iOS/Android \uc571 \ub0b4 \uad6c\ub3c5\uc758 \ud658\ubd88\uc740 Apple/Google \uc815\ucc45\uc5d0 \ub530\ub77c \uac01 \uc2a4\ud1a0\uc5b4\uc5d0 \uc9c1\uc811 \uc2e0\uccad\ud558\uc154\uc57c \ud569\ub2c8\ub2e4.</li>
          <li><strong>Soram Companion \ucde8\uc18c \ubc29\ubc95:</strong>
            <ul className="list-disc pl-6 mt-1 space-y-1">
              <li><strong>iOS App Store:</strong> \uc124\uc815 \u2192 [Apple ID \uc774\ub984] \u2192 \uad6c\ub3c5 \u2192 Soram Companion \u2192 \uad6c\ub3c5 \ucde8\uc18c</li>
              <li><strong>Google Play:</strong> Play \uc2a4\ud1a0\uc5b4 \u2192 \ud504\ub85c\ud544 \uc544\uc774\ucf58 \u2192 \uacb0\uc81c \ubc0f \uad6c\ub3c5 \u2192 \uad6c\ub3c5 \u2192 Soram Companion \u2192 \uad6c\ub3c5 \ucde8\uc18c</li>
              <li><strong>\uc6f9(PayPal):</strong> \ub300\uc2dc\ubcf4\ub4dc\uc5d0\uc11c \ucde8\uc18c \ud558\uac70\ub098 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \uc774\uba54\uc77c. \ub610\ub294 PayPal \uc790\ub3d9\uacb0\uc81c \uad00\ub9ac \uba54\ub274\uc5d0\uc11c \uc9c1\uc811 \ucde8\uc18c \uac00\ub2a5.</li>
            </ul>
            \ucde8\uc18c \uc2dc \ub2e4\uc74c \uc694\uae08 \uccad\uad6c\ub294 \uc911\uc9c0\ub418\uba70, \ud604\uc7ac \uae30\uac04\uc774 \ub05d\ub0a0 \ub54c\uae4c\uc9c0\ub294 \uc11c\ube44\uc2a4\ub97c \uacc4\uc18d \uc774\uc6a9\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.
          </li>
          <li><strong>\ud55c\uad6d \uc18c\ube44\uc790:</strong> \uc804\uc790\uc0c1\uac70\ub798\uc5d0\uc11c\uc758 \uc18c\ube44\uc790\ubcf4\ud638\uc5d0 \uad00\ud55c \ubc95\ub960\uc5d0 \uc758\ud55c \uad8c\ub9ac(\ub514\uc9c0\ud138 \ucf58\ud150\uce20 \ud2b9\uc131\uc0c1 \ucca3\uae09\uad8c \uc81c\ud55c \uc81c\uc678)\uc740 \uc644\uc804\ud788 \ubcf4\uc7a5\ub429\ub2c8\ub2e4.</li>
        </ul>
        <p>\uba3c\uc800 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \ud574\uacb0 \uc2dc\ub3c4 \uc5c6\uc774 \uc81c\uae30\ub41c \ucc28\uc9c0\ubc31\uc740 \uacc4\uc815 \uc815\uc9c0\ub85c \uc774\uc5b4\uc9c8 \uc218 \uc788\uc2b5\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">8. AI \uc0dd\uc131 \ucf58\ud150\uce20 \ubc0f \ubaa8\ub378 \uc81c\uacf5\uc790</h2>
        <p className="mb-2">\ubaa8\ub4e0 \ub9ac\ub529\uc740 \uc8fc\ub85c Google Gemini, \ubcf4\uc870 \ubc0f \uac80\uc99d\ub808\uc774\uc5b4\ub85c Anthropic Claude\uac00 \uc0dd\uc131\ud558\uba70, \uc800\ud76c \uace0\uc720 \uc624\ucf00\uc2a4\ud2b8\ub808\uc774\uc158 \ub808\uc774\uc5b4 &ldquo;RimSaju Engine&rdquo;\uc774 \uacb0\uc815\ub860\uc801 \uc0ac\uc8fc \uc5f0\uc0b0\uacfc 562\uc801 \uace0\uc804 \ubb38\ud5cc RAG\ub97c \uacb0\ud569\ud569\ub2c8\ub2e4.</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>AI \ucd9c\ub825\uc5d0\ub294 \uc624\ub958\ub098 \ud560\ub8e8\uc2dc\ub124\uc774\uc158\uc774 \ud3ec\ud568\ub420 \uc218 \uc788\uc2b5\ub2c8\ub2e4.</li>
          <li>\ub9ac\ub529\uc740 \uc694\uccad \uc2dc\uc810\uc5d0 \uc720\uc77c\ud558\uac8c \uc0dd\uc131\ub429\ub2c8\ub2e4.</li>
          <li>\uc0dd\ub144\uc6d4\uc77c\uc2dc \uc815\ubcf4\ub294 \ub9ac\ub529 \uc0dd\uc131\uc744 \uc704\ud574 AI \ubaa8\ub378\uc5d0 \uc785\ub825\uac12\uc73c\ub85c \uc804\ub2ec\ub429\ub2c8\ub2e4.</li>
          <li>AI \ucd9c\ub825\uc740 \uc804\ubb38\uac00 \uc870\uc5b8\uc744 \ub300\uccb4\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4(\u00a73 \ucc38\uc870).</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">9. \uc774\uc6a9 \ud589\ub3d9 \uaddc\uc815</h2>
        <p className="mb-2">\ub2e4\uc74c \ud589\uc704\ub97c \uc5c6\uc73c\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>\ubcf8\uc778 \ub3d9\uc758 \uc5c6\uc774 \ud0c0\uc778\uc758 \uc0dd\ub144\uc6d4\uc77c\uc2dc \uc815\ubcf4 \uc785\ub825</li>
          <li>\uc11c\ube44\uc2a4\ub97c \uc774\uc6a9\ud55c \ud2b9\uc815\uc778 \uad34\ub86d\ud78c\uc774\ub098 \uba85\uc608\ud6fc\uc190</li>
          <li>\ub9ac\ub529\uc758 \ub300\ub7c9 \uc2a4\ud06c\ub798\ud551\u00b7\uc7ac\ud310\ub9e4\u00b7\uc7ac\ubc30\ud3ec</li>
          <li>\ud504\ub86c\ud504\ud2b8\u00b7\uc784\ubca0\ub529\u00b7RAG \uc18c\uc2a4 \uc5ed\ubd84\uc11d</li>
          <li>\ubd88\ubc95\u00b7\ud601\uc624\uc2a4\ub7ec\uc6b4\u00b7\uc131\uc801 \ucf58\ud150\uce20 \uc5c5\ub85c\ub4dc</li>
          <li>\uc694\uc728 \uc81c\ud55c\u00b7\uacb0\uc81c \uc778\uc99d \uc6b0\ud68c</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">10. \uc9c0\uc2dd\uc7ac\uc0b0\uad8c</h2>
        <p>SajuAstrology \uc0c1\ud45c\u00b7\ube0c\ub79c\ub4dc\u00b7RimSaju Engine\u00b7\uc6f9\uc0ac\uc774\ud2b8 \ub514\uc790\uc778\u00b7\ucf54\ub4dc\u00b7\uace0\uc804 \ubb38\ud5cc \ud050\ub808\uc774\uc158\uc740 Rimfactory\uc758 \uc18c\uc720\uc785\ub2c8\ub2e4. \uc774\uc6a9\uc790\ub294 \uac1c\uc778 \ube44\uc0c1\uc5c5 \ubaa9\uc801\uc73c\ub85c\ub9cc \uc0ac\uc6a9\ud560 \uc218 \uc788\ub294 \uc81c\ud55c\uc801\u00b7\ube44\ub3c5\uc810\uc801\u00b7\uc591\ub3c4 \ubd88\uac00 \ub77c\uc774\uc120\uc2a4\ub97c \ubd80\uc5ec\ubc1b\uc2b5\ub2c8\ub2e4. AI \uc0dd\uc131 \ub9ac\ub529\uc740 \uc81c\uacf5\ub41c \uacf5\uc720 \ub9c1\ud06c\ub97c \ud1b5\ud574 \uacf5\uc720\ud560 \uc218 \uc788\uc73c\ub098 \uc7ac\ud310\ub9e4\ud558\uac70\ub098 \ub2e4\ub978 AI \ubaa8\ub378 \ud559\uc2b5\uc5d0 \uc0ac\uc6a9\ud560 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">11. \ubcc0\uacbd \ubc0f \uc885\ub8cc</h2>
        <p>\uc11c\ube44\uc2a4\uc758 \uc77c\ubd80\ub97c \uc5b8\uc81c\ub4e0\uc9c0 \uc218\uc815\u00b7\uc911\ub2e8\u00b7\uc885\ub8cc\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4. \uc911\uc694\ud55c \ubcc0\uacbd\uc740 \uc6f9\uc0ac\uc774\ud2b8\uc5d0 \uc0c8 &ldquo;\ucd5c\uc885 \uc218\uc815\uc77c&rdquo;\ub85c \uacf5\uc9c0\ub429\ub2c8\ub2e4. \ubcc0\uacbd \ud6c4 \uacc4\uc18d \uc774\uc6a9\ud558\ub294 \uacbd\uc6b0 \ub3d9\uc758\ud55c \uac83\uc73c\ub85c \uac04\uc8fc\ud569\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">12. \ubcf4\uc99d \ubd80\uc778</h2>
        <p>\uc11c\ube44\uc2a4\ub294 &ldquo;\ud604\uc0c1\ud0dc\ub300\ub85c&rdquo; \uc81c\uacf5\ub429\ub2c8\ub2e4. \ubc95\ub960\uc774 \ud5c8\uc6a9\ud558\ub294 \ucd5c\ub300 \ubc94\uc704 \ub0b4\uc5d0\uc11c \uc0c1\ud488\uc131\u00b7\ud2b9\uc815 \ubaa9\uc801 \uc801\ud569\uc131\u00b7\ube44\uce68\ud574\uc131\u00b7AI \uc0dd\uc131 \ucf58\ud150\uce20 \uc815\ud655\uc131\uc5d0 \ub300\ud55c \ubaa8\ub4e0 \ubcf4\uc99d\uc744 \ubd80\uc778\ud569\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">13. \ucc45\uc784 \uc81c\ud55c</h2>
        <p className="mb-2">\uc801\uc6a9 \ubc95\ub960\uc774 \ud5c8\uc6a9\ud558\ub294 \ucd5c\ub300 \ubc94\uc704 \ub0b4\uc5d0\uc11c Rimfactory\ub294 \uac04\uc811\u00b7\uc6b0\ubc1c\u00b7\ud2b9\ubcc4\u00b7\uacb0\uacfc\uc801 \uc190\ud574\uc5d0 \ub300\ud574 \ucc45\uc784\uc744 \uc9c0\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4. \uc804\uccb4 \uc18c\uc1a1 \ud569\uc0b0 \ucc45\uc784\uc740 \uccad\uad6c \ubc1c\uc0dd \uc804 12\uac1c\uc6d4 \ub3d9\uc548 Rimfactory\uc5d0 \ub0b4\uc2e0 \uac8c\uc774\ub098 US$100 \uc911 \ud070 \uae08\uc561\uc744 \ucd08\uacfc\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>
        <p>\ud55c\uad6d \uc18c\ube44\uc790\ubcf4\ud638\ubc95\ub839\uc5d0 \uc758\ud574 \uc81c\ud55c\ud560 \uc218 \uc5c6\ub294 \ucc45\uc784\uc740 \uc774 \uc870\ud56d\uc5d0 \uad00\uacc4\uc5c6\uc774 \ubcf4\uc804\ub429\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">14. \ubd84\uc7c1 \ud574\uacb0</h2>
        <p className="mb-2"><strong>\ube44\uacf5\uc2dd \ud574\uacb0 \uc6b0\uc120.</strong> \uacf5\uc2dd \uc808\ucc28 \uc2dc\uc791 \uc804 <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a>\ub85c \uc5f0\ub77d\ud558\uc5ec 30\uc77c\uc758 \uc131\uc2e4\ud55c \ud574\uacb0 \uc2dc\ub3c4 \uae30\uac04\uc744 \ubd80\uc5ec\ud558\uc2ed\uc2dc\uc624.</p>
        <p className="mb-2"><strong>\uc900\uac70\ubc95.</strong> \ubcf8 \uc57d\uad00\uc740 \ub300\ud55c\ubbfc\uad6d \ubc95\ub960\uc5d0 \ub530\ub974\uba70, \uac71\ub4dc\ub294 \uad6c\uc18c\uc9c0\uc758 \uc18c\ube44\uc790 \ubcf4\ud638 \uad8c\ub9ac\uc5d0\ub294 \uc601\ud5a5\uc744 \ub300\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>
        <p><strong>\uad00\ud560.</strong> \uc11c\uc6b8\uc911\uc559\uc9c0\ubc29\ubc95\uc6d0\uc774 \uc804\uc18d \uad00\ud560\uad8c\uc744 \uac16\uc2b5\ub2c8\ub2e4(\uc18c\ube44\uc790\ubcf4\ud638\ubc95\ub839\uc5d0 \uc758\ud55c \uac15\ud589\uaddc\uc815 \uc801\uc6a9 \uc81c\uc678).</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">15. \ubd84\ub9ac \uac00\ub2a5\uc131 \ubc0f \uc804\uccb4 \ud569\uc758</h2>
        <p>\uc77c\ubd80 \uc870\ud56d\uc774 \ubb34\ud6a8\ub85c \ud310\uc815\ub418\uc5b4\ub3c4 \ub098\uba38\uc9c0 \uc870\ud56d\uc740 \uc720\ud6a8\ud569\ub2c8\ub2e4. \ubcf8 \uc57d\uad00\uacfc \uac1c\uc778\uc815\ubcf4\ucc98\ub9ac\ubc29\uce68\uc774 \uc11c\ube44\uc2a4\uc5d0 \uad00\ud55c Rimfactory\uc640 \uc774\uc6a9\uc790 \uac04\uc758 \uc804\uccb4 \ud569\uc758\ub97c \uad6c\uc131\ud569\ub2c8\ub2e4.</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">\ubb38\uc758</h2>
        <div className="bg-card/50 border border-border rounded-xl p-4">
          <p><strong>Rimfactory</strong> \u2014 \uc11c\uc6b8\ud2b9\ubcc4\uc2dc \uad6c\ub85c\uad6c \uc0c8\ub9d0\ub85c 97, \uc2e0\ub3c4\ub9bc\ud14c\ud06c\ub178\ub9c8\ud2b8 1\ub3d9 243\ud638, 08213</p>
          <p className="mt-1">\uc0ac\uc5c5\uc790\ub4f1\ub85d\ubc88\ud638: 402-44-01247 \u00b7 \ud1b5\uc2e0\ud310\ub9e4\uc5c5 \uc2e0\uace0\ubc88\ud638: 2025-\uc11c\uc6b8\uad6c\ub85c-2056</p>
          <p className="mt-1">\uc774\uba54\uc77c: <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u00b7 \uc804\ud654: +82-10-4648-6793</p>
        </div>
      </section>
    </div>
  )
}

// ─── JAPANESE content (\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u8868\u793a included) ──────────────────────────────────
function TermsJA() {
  return (
    <div className="space-y-8 text-sm text-foreground/90 leading-relaxed">
      <section>
        <h2 className="text-lg font-serif text-primary mb-3">1. \u540c\u610f</h2>
        <p className="mb-2">SajuAstrology.com(\u300c\u30a6\u30a7\u30d6\u30b5\u30a4\u30c8\u300d)\u307e\u305f\u306fSajuAstrology\u30e2\u30d0\u30a4\u30eb\u30a2\u30d7\u30ea(\u300c\u30a2\u30d7\u30ea\u300d\u3001\u4e00\u7dcf\u3057\u3066\u300c\u30b5\u30fc\u30d3\u30b9\u300d)\u3092\u5229\u7528\u3059\u308b\u3053\u3068\u3067\u3001\u672c\u5229\u7528\u898f\u7d04(\u300c\u898f\u7d04\u300d)\u306b\u6cd5\u7684\u306b\u62d8\u675f\u3055\u308c\u308b\u3053\u3068\u306b\u540c\u610f\u3057\u305f\u3082\u306e\u3068\u307f\u306a\u3057\u307e\u3059\u3002\u540c\u610f\u3044\u305f\u3060\u3051\u306a\u3044\u5834\u5408\u306f\u3001\u30b5\u30fc\u30d3\u30b9\u3092\u3054\u5229\u7528\u306b\u306a\u308c\u307e\u305b\u3093\u3002</p>
        <p>\u672c\u30b5\u30fc\u30d3\u30b9\u306fRimfactory(\u300c\u5f53\u793e\u300d)\u304c\u904b\u55b6\u3057\u3066\u3044\u307e\u3059\u3002</p>
      </section>

      {/* \u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u793a */}
      <section>
        <h2 className="text-lg font-serif text-primary mb-3">\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u793a</h2>
        <div className="bg-card/50 border border-border rounded-xl p-4 text-xs space-y-1">
          <p><strong>\u4e8b\u696d\u8005\u540d\uff08\u6cd5\u4eba\u540d\uff09:</strong> Rimfactory</p>
          <p><strong>\u4ee3\u8868\u8005\u6c0f\u540d:</strong> Yun Choyeon (Chandler Yun)</p>
          <p><strong>\u6240\u5728\u5730:</strong> 243, 1F, Sindorim Technomart, 97 Saemal-ro, Guro-gu, Seoul 08213, \u5927\u97d3\u6c11\u56fd</p>
          <p><strong>\u96fb\u8a71\u756a\u53f7:</strong> +82-10-4648-6793</p>
          <p><strong>\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9:</strong> <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a></p>
          <p><strong>\u8ca9\u58f2\u4fa1\u683c:</strong> \u5404\u5546\u54c1\u30da\u30fc\u30b8\u306b\u8a18\u8f09\u306e\u901a\u308a\u3002Compatibility Full USD 2.99 / Full Destiny Reading USD 9.99 / Master 5 Pack USD 29.99 / Soram Companion USD 4.99/\u6708</p>
          <p><strong>\u8ca9\u58f2\u4fa1\u683c\u4ee5\u5916\u306b\u5fc5\u8981\u306a\u8cbb\u7528:</strong> \u306a\u3057(\u901a\u4fe1\u6599\u7b49\u306f\u30e6\u30fc\u30b6\u30fc\u8ca0\u62c5)</p>
          <p><strong>\u304a\u652f\u6255\u3044\u65b9\u6cd5:</strong> PayPal Checkout(\u30a6\u30a7\u30d6)\u3001Apple App Store\u306e\u30a2\u30d7\u30ea\u5185\u8ab2\u91d1(iOS)\u3001Google Play\u306e\u30a2\u30d7\u30ea\u5185\u8ab2\u91d1(Android)</p>
          <p><strong>\u5546\u54c1\u306e\u5f15\u6e21\u3057\u6642\u671f:</strong> \u304a\u652f\u6255\u3044\u5b8c\u4e86\u5f8c\u3001\u5373\u6642\u306b\u30c7\u30b8\u30bf\u30eb\u30b3\u30f3\u30c6\u30f3\u30c4\u3092\u3054\u63d0\u4f9b</p>
          <p><strong>\u8fd4\u54c1\u30fb\u30ad\u30e3\u30f3\u30bb\u30eb\u306b\u3064\u3044\u3066:</strong> \u30c7\u30b8\u30bf\u30eb\u30b3\u30f3\u30c6\u30f3\u30c4\u306e\u6027\u8cea\u4e0a\u3001\u8cfc\u5165\u5b8c\u4e86\u5f8c\u306e\u8fd4\u54c1\u30fb\u9003\u8fd4\u306f\u539f\u5247\u3068\u3057\u3066\u304a\u5c71\u3052\u3067\u304d\u307e\u305b\u3093\u3002\u305f\u3060\u3057\u3001\u6280\u8853\u7684\u306a\u969c\u5bb3\u306b\u3088\u308a\u30b3\u30f3\u30c6\u30f3\u30c4\u304c\u63d0\u4f9b\u3055\u308c\u306a\u304b\u3063\u305f\u5834\u5408\u306f\u3001\u8cfc\u5165\u65e5\u304b\u307710\u65e5\u4ee5\u5185\u306b <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u3054\u9023\u7d61\u304f\u3060\u3055\u3044\u3002<br />\u300cSoram Companion\u300d\u5b9a\u671f\u8cfc\u8aad\u306e\u89e3\u7d04\u306b\u3064\u3044\u3066\u306f\u300710\u7ae0\u3092\u3054\u78ba\u8a8d\u304f\u3060\u3055\u3044\u3002</p>
          <p><strong>\u52d5\u4f5c\u74b0\u5883:</strong> \u30a6\u30a7\u30d6\u30d6\u30e9\u30a6\u30b6(\u6a19\u6e96\u7684\u306a\u73fe\u884c\u30d6\u30e9\u30a6\u30b6)\u3001iOS\u30a2\u30d7\u30ea\u3001Android\u30a2\u30d7\u30ea</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">2. \u30b5\u30fc\u30d3\u30b9\u5185\u5bb9</h2>
        <p className="mb-2">SajuAstrology\u306f\u3001\u97d3\u56fd\u4f1d\u7d71\u547d\u7406\u5b66(\u56db\u67f1\u63a8\u547d)\u306b\u57fa\u3065\u304fAI\u751f\u6210\u30b3\u30f3\u30c6\u30f3\u30c4\u3092\u63d0\u4f9b\u3057\u307e\u3059\u3002\u30a6\u30a7\u30d6\u30b5\u30a4\u30c8\u304a\u3088\u3073iOS(App Store)\u30fb Android(Google Play)\u30a2\u30d7\u30ea\u3092\u901a\u3058\u3066\u3001\u65e5\u672c\u8a9e\u3092\u542b\u304610\u8a00\u8a9e\u3067\u3054\u5229\u7528\u3044\u305f\u3060\u3051\u307e\u3059\u3002</p>
        <p>\u7121\u6599\u9451\u5b9a\u3001\u7121\u6599\u76f8\u6027\u5224\u65ad\u3001\u6709\u6599Compatibility Full\u3001\u6709\u6599Full Destiny Reading\u3001Master 5 Pack\u30b3\u30f3\u30b5\u30eb\u30c6\u30fc\u30b7\u30e7\u30f3\u3001Soram Companion\u30b5\u30d6\u30b9\u30af\u30ea\u30d7\u30b7\u30e7\u30f3\u3092\u63d0\u4f9b\u3057\u3066\u3044\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">3. \u5a08\u697d\u76ee\u7684\u306e\u307f \u2014 \u91cd\u8981\u306a\u514d\u8cac\u4e8b\u9805</h2>
        <div className="bg-amber-500/5 border border-amber-500/20 rounded-xl p-4 space-y-2">
          <p>\u672c\u30b5\u30fc\u30d3\u30b9\u306e\u30b3\u30f3\u30c6\u30f3\u30c4\u306f\u3059\u3079\u3066\u3001<strong>\u5a18\u697d\u30fb\u6587\u5316\u7684\u63a2\u6c42\u30fb\u81ea\u5df1\u5185\u7701\u306e\u305f\u3081</strong>\u306e\u3082\u306e\u3067\u3059\u3002\u3044\u304b\u306a\u308b\u7a2e\u985e\u306e\u5c02\u9580\u7684\u30a2\u30c9\u30d0\u30a4\u30b9\u3067\u3082\u3042\u308a\u307e\u305b\u3093\u3002</p>
          <p><strong>\u6b21\u306e\u4e8b\u9805\u306b\u95a2\u3059\u308b\u610f\u601d\u6c7a\u5b9a\u306b\u672c\u30b5\u30fc\u30d3\u30b9\u3092\u4f7f\u7528\u3057\u306a\u3044\u3067\u304f\u3060\u3055\u3044:</strong> \u533b\u7642\u30fb\u7cbe\u795e\u5065\u5eb7\u3001\u6cd5\u5f8b\u554f\u984c\u3001\u91d1\u878d\u30fb\u6295\u8cc4\u30fb\u7a0e\u52d9\u3001\u6050\u611b\u30fb\u7d50\u5a5a\u30fb\u751f\u6b96\u3001\u96c7\u7528\u30fb\u30ad\u30e3\u30ea\u30a2\u30fb\u4e8b\u696d\u3001\u5150\u7ae5\u8986\u7949\u30fb\u6559\u80b2\u3001\u305d\u306e\u4ed6\u91cd\u8981\u306a\u73fe\u5b9f\u4e16\u754c\u3078\u306e\u5f71\u97ff\u3002\u5fc5\u305a\u8cc7\u683c\u3092\u6301\u3063\u305f\u5c02\u9580\u5bb6\u306b\u3054\u76f8\u8ac7\u304f\u3060\u3055\u3044\u3002</p>
          <p>\u56db\u67f1\u63a8\u547d\u306f\u6771\u30a2\u30b8\u30a2\u306e\u4f1d\u7d71\u6587\u5316\u5b9f\u8df5\u3067\u3042\u308a\u3001\u5b97\u6559\u7684\u6559\u7fa9\u3084\u795e\u306e\u554f\u3044\u3067\u306f\u306a\u304f\u3001\u79d1\u5b66\u7684\u306b\u8a3c\u660e\u3055\u308c\u305f\u4e88\u8a00\u80fd\u529b\u3082\u3042\u308a\u307e\u305b\u3093\u3002\u672c\u30b5\u30fc\u30d3\u30b9\u306e\u5229\u7528\u304c\u3054\u81ea\u8eab\u306e\u4fa1\u5024\u89b3\u30fb\u5b97\u6559\u7684\u4fe1\u5ff5\u306b\u9069\u5207\u304b\u3069\u3046\u304b\u306f\u3054\u81ea\u8eab\u3067\u3054\u5224\u65ad\u304f\u3060\u3055\u3044\u3002</p>
        </div>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">4. \u5229\u7528\u8cc7\u683c</h2>
        <p className="mb-2">\u30b5\u30fc\u30d3\u30b9\u306b\u30b5\u30a4\u30f3\u30a4\u30f3\u3059\u308b\u3053\u3068\u3067\u3001\u5c0a\u6cd5\u306e\u500b\u4eba\u60c5\u5831\u4fdd\u8b77\u6cd5\u306b\u57fa\u3065\u304f\u6700\u4f4e\u30c7\u30b8\u30bf\u30eb\u5c0c\u8adf\u5e74\u9f62\uff08<strong>14\u6b73\u4ee5\u4e0a</strong>\uff09\u3067\u3042\u308b\u3053\u3068\u3092\u8868\u660e\u3057\u305f\u3082\u306e\u3068\u307f\u306a\u3057\u307e\u3059\u3002</p>
        <p>\u6cd5\u5b9a\u5e74\u9f62\u4ee5\u4e0b\u306e\u6728\u8eab\u8005\u306e\u60c5\u5831\u304c\u767b\u9332\u3055\u308c\u305f\u5834\u5408\u3001\u901a\u77e5\u6b21\u7b2c\u5373\u5ea7\u306b\u524a\u9664\u3044\u305f\u3057\u307e\u3059\u3002\u4fdd\u8b77\u8005\u306e\u65b9\u306f <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u304a\u554f\u3044\u5408\u308f\u305b\u304f\u3060\u3055\u3044\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">5. \u30a2\u30ab\u30a6\u30f3\u30c8</h2>
        <p className="mb-2">\u30a2\u30ab\u30a6\u30f3\u30c8\u306fGoogle OAuth\u307e\u305f\u306fApple\u30b5\u30a4\u30f3\u30a4\u30f3\u306e\u307f\u3067\u4f5c\u6210\u3067\u304d\u307e\u3059\u3002ID/\u30d1\u30b9\u30ef\u30fc\u30c9\u306f\u904b\u7528\u3057\u3066\u3044\u307e\u305b\u3093\u3002\u540c\u4e00\u306e\u30b5\u30a4\u30f3\u30a4\u30f3\u65b9\u6cd5\u3092\u4f7f\u7528\u3059\u308b\u3068\u3001\u30a6\u30a7\u30d6\u3068\u30a2\u30d7\u30ea\u9593\u3067\u30a2\u30ab\u30a6\u30f3\u30c8\u304c\u540c\u671f\u3055\u308c\u307e\u3059\u3002</p>
        <p>\u30c0\u30c3\u30b7\u30e5\u30dc\u30fc\u30c9\u30fb\u65e5\u4f8b\u904b\u52e2\u30fb\u30bd\u30e9\u30e0\u9023\u643a\u306e\u4e3b\u56db\u67f1\u306f\u767b\u9332\u6642\u306b1\u56de\u5165\u529b\u3059\u308b\u3082\u306e\u3067\u3059\u3002\u5909\u66f4\u3092\u5e0c\u671b\u3055\u308c\u308b\u5834\u5408\u306f <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u304a\u554f\u3044\u5408\u308f\u305b\u304f\u3060\u3055\u3044\u3002\u30a2\u30ab\u30a6\u30f3\u30c8\u306e\u524a\u9664\u306f\u30c0\u30c3\u30b7\u30e5\u30dc\u30fc\u30c9\u307e\u305f\u306f\u30e1\u30fc\u30eb\u3067\u8981\u8acb\u53ef\u80fd\u3067\u3001\u5b8c\u4e86\u307e\u3067\u306330\u65e5\u4ee5\u5185\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">6. \u6599\u91d1</h2>
        <p className="mb-2"><strong>\u7121\u6599:</strong> \u56db\u67f1\u9451\u5b9a(\u6027\u683c\u30fb\u4e94\u884c\u30fb\u5e74\u904b)\u3001\u76f8\u6027\u5224\u65ad\u5168\u4f53\u3001\u65e5\u4f8b\u904b\u52e2\u3001\u30bd\u30e9\u30e01\u65e5\u51fa\u4f1a\u30141\u56de\u3001\u7d50\u679c\u30b7\u30a7\u30a2\u3002</p>
        <p className="mb-2"><strong>Compatibility Full (USD 2.99):</strong> \u30da\u30a2\u306b\u3064\u304d1\u56de\u306e\u4e00\u6642\u6255\u3044\u3002\u65e2\u5b58\u306e\u76f8\u6027\u7d50\u679c\u306e\u6709\u6599\u30a8\u30ea\u30a2\u3092\u89e3\u9501\u3002\u30a2\u30ab\u30a6\u30f3\u30c8\u7dad\u6301\u4e2d\u306f\u6c38\u4e45\u30a2\u30af\u30bb\u30b9\u3002</p>
        <p className="mb-2"><strong>Full Destiny Reading (USD 9.99):</strong> \u30ea\u30fc\u30c7\u30a3\u30f3\u30b0\u306b\u3064\u304d1\u56de\u306e\u4e00\u6642\u6255\u3044\u3002\u547d\u5f0f\u30d9\u30fc\u30b9\u306e\u8a73\u3057\u3044\u9451\u5b9a\u3002\u30ea\u30fc\u30c7\u30a3\u30f3\u30b0\u30da\u30fc\u30b8\u306f\u6c38\u4e45\u4fdd\u5b58\u3002</p>
        <p className="mb-2"><strong>Master 5 Pack (USD 29.99):</strong> 1\u56de\u306e\u4e00\u6642\u6255\u3044\u3002AI\u30b3\u30f3\u30b5\u30eb5\u56de + Full Destiny Reading\u3092\u542b\u3080\u3002\u30b3\u30f3\u30b5\u30eb\u30af\u30ec\u30b8\u30c3\u30c8\u306e\u6709\u52b9\u671f\u9650\u306a\u3057\u3002</p>
        <p className="mb-2"><strong>Soram Companion (USD 4.99/\u6708 \u2014 \u81ea\u52d5\u66f4\u65b0\u30b5\u30d6\u30b9\u30af\u30ea\u30d7\u30b7\u30e7\u30f3):</strong> \u30bd\u30e9\u30e0\u30c1\u30e3\u30c3\u30c8\u7121\u5236\u9650 + \u6bce\u6708Master\u30b3\u30f3\u30b5\u30eb1\u56de\u5206\u30af\u30ec\u30b8\u30c3\u30c8\u3002\u66f4\u65b0\u65e5\u306e24\u6642\u9593\u524d\u307e\u3067\u89e3\u7d04\u3057\u306a\u3044\u5834\u5408\u3001\u540c\u4e00\u91d1\u984d\u3067\u81ea\u52d5\u66f4\u65b0\u3055\u308c\u307e\u3059\u3002</p>
        <p className="text-muted-foreground">\u6599\u91d1\u306f\u7c73\u30c9\u30eb(USD)\u8868\u793a\u3002\u30a6\u30a7\u30d6\u3068\u30a2\u30d7\u30ea\u3067\u540c\u4e00\u4fa1\u683c\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">7. \u304a\u652f\u6255\u3044\u30fb\u8fd4\u91d1</h2>
        <p className="mb-2"><strong>\u30a6\u30a7\u30d6\u306e\u304a\u652f\u6255\u3044</strong>\u306fPayPal Checkout\u3067\u51e6\u7406\u3055\u308c\u307e\u3059\u3002<strong>\u30a2\u30d7\u30ea\u306e\u304a\u652f\u6255\u3044</strong>\u306fApple App Store(iOS)\u307e\u305f\u306fGoogle Play(Android)\u3067\u51e6\u7406\u3055\u308c\u307e\u3059\u3002\u5f53\u793e\u306f\u304a\u652f\u6255\u3044\u30ab\u30fc\u30c9\u60c5\u5831\u3092\u53d7\u3051\u53d6\u3063\u305f\u308a\u4fdd\u5b58\u3057\u305f\u308a\u3044\u305f\u3057\u307e\u305b\u3093\u3002</p>
        <p className="mb-2">\u30c7\u30b8\u30bf\u30eb\u30b3\u30f3\u30c6\u30f3\u30c4\u306f\u304a\u652f\u6255\u3044\u5b8c\u4e86\u5f8c\u5373\u5ea7\u306b\u63d0\u4f9b\u3055\u308c\u307e\u3059\u3002</p>
        <ul className="list-disc pl-6 mb-2 space-y-1">
          <li>\u6280\u8853\u7684\u969c\u5bb3\u306b\u3088\u308a\u30b3\u30f3\u30c6\u30f3\u30c4\u304c\u63d0\u4f9b\u3055\u308c\u306a\u304b\u3063\u305f\u5834\u5408\u3001\u8cfc\u5165\u65e5\u304b\u307710\u65e5\u4ee5\u5185\u306b <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u304a\u554f\u3044\u5408\u308f\u305b\u304f\u3060\u3055\u3044\u3002</li>
          <li>iOS/Android\u30a2\u30d7\u30ea\u5185\u8cfc\u5165\u306e\u8fd4\u91d1\u306fApple/Google\u306e\u30dd\u30ea\u30b7\u30fc\u306b\u5f93\u3044\u3001\u5404\u30b9\u30c8\u30a2\u306b\u76f4\u63a5\u304a\u7533\u3057\u8fbc\u307f\u304f\u3060\u3055\u3044\u3002</li>
          <li><strong>Soram Companion \u89e3\u7d04\u65b9\u6cd5:</strong>
            <ul className="list-disc pl-6 mt-1 space-y-1">
              <li><strong>iOS App Store:</strong> \u8a2d\u5b9a \u2192 [Apple ID\u540d] \u2192 \u30b5\u30d6\u30b9\u30af\u30ea\u30d7\u30b7\u30e7\u30f3 \u2192 Soram Companion \u2192 \u30b5\u30d6\u30b9\u30af\u30ea\u30d7\u30b7\u30e7\u30f3\u3092\u30ad\u30e3\u30f3\u30bb\u30eb</li>
              <li><strong>Google Play:</strong> Play\u30b9\u30c8\u30a2 \u2192 \u30d7\u30ed\u30d5\u30a3\u30fc\u30eb\u30a2\u30a4\u30b3\u30f3 \u2192 \u304a\u652f\u6255\u3044\u3068\u5b9a\u671f\u8cfc\u8aad \u2192 \u5b9a\u671f\u8cfc\u8aad \u2192 Soram Companion \u2192 \u5b9a\u671f\u8cfc\u8aad\u3092\u30ad\u30e3\u30f3\u30bb\u30eb</li>
              <li><strong>\u30a6\u30a7\u30d6(PayPal):</strong> \u30c0\u30c3\u30b7\u30e5\u30dc\u30fc\u30c9\u304b\u3089\u30ad\u30e3\u30f3\u30bb\u30eb\u3001\u307e\u305f\u306f <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u30e1\u30fc\u30eb\u3002PayPal\u306e\u81ea\u52d5\u652f\u6255\u3044\u7ba1\u7406\u304b\u3089\u76f4\u63a5\u30ad\u30e3\u30f3\u30bb\u30eb\u3082\u53ef\u80fd\u3002</li>
            </ul>
            \u89e3\u7d04\u5f8c\u306f\u6b21\u306e\u8ab2\u91d1\u30b5\u30a4\u30af\u30eb\u304c\u505c\u6b62\u3055\u308c\u3001\u5f53\u524d\u671f\u9593\u7d42\u4e86\u307e\u3067\u30b5\u30fc\u30d3\u30b9\u3092\u304a\u5229\u7528\u3044\u305f\u3060\u3051\u307e\u3059\u3002
          </li>
        </ul>
        <p>\u307e\u305a <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u3078\u306e\u89e3\u6c7a\u8a66\u307f\u306a\u304f\u884c\u308f\u308c\u305f\u30c1\u30e3\u30fc\u30b8\u30d0\u30c3\u30af\u306f\u3001\u30a2\u30ab\u30a6\u30f3\u30c8\u5c01\u6b62\u306b\u3064\u306a\u304c\u308b\u5834\u5408\u304c\u3042\u308a\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">8. AI\u751f\u6210\u30b3\u30f3\u30c6\u30f3\u30c4\u3068\u30e2\u30c7\u30eb\u30d7\u30ed\u30d0\u30a4\u30c0\u30fc</h2>
        <p className="mb-2">\u5168\u3066\u306e\u9451\u5b9a\u306f\u4e3b\u306bGoogle Gemini\u3001\u691c\u8a3c\u30ec\u30a4\u30e4\u30fc\u3068\u3057\u3066Anthropic Claude\u3092\u4f7f\u7528\u3057\u3066\u751f\u6210\u3055\u308c\u3001\u5f53\u793e\u72ec\u81ea\u306e\u300cRimSaju Engine\u300d\u304c\u6c7a\u5b9a\u8ad6\u7684\u56db\u67f1\u8a08\u7b97\u3068562\u5178\u7c4d\u306eRAG\u3092\u7d44\u307f\u5408\u308f\u305b\u307e\u3059\u3002</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>AI\u51fa\u529b\u306b\u306f\u8aa4\u308a\u3084\u30cf\u30eb\u30b7\u30cd\u30fc\u30b7\u30e7\u30f3\u304c\u542b\u307e\u308c\u308b\u5834\u5408\u304c\u3042\u308a\u307e\u3059\u3002</li>
          <li>\u751f\u5e74\u6708\u65e5\u6642\u60c5\u5831\u306f\u9451\u5b9a\u751f\u6210\u306e\u305f\u3081\u306b\u30e2\u30c7\u30eb\u306b\u5165\u529b\u3068\u3057\u3066\u9001\u4fe1\u3055\u308c\u307e\u3059\u3002</li>
          <li>AI\u51fa\u529b\u306f\u5c02\u9580\u5bb6\u306e\u30a2\u30c9\u30d0\u30a4\u30b9\u306e\u4ee3\u66ff\u306b\u306f\u306a\u308a\u307e\u305b\u3093(\u7b2c3\u6761\u53c2\u7167)\u3002</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">9. \u5229\u7528\u8005\u306e\u884c\u70ba\u30eb\u30fc\u30eb</h2>
        <p className="mb-2">\u6b21\u306e\u884c\u70ba\u3092\u7981\u6b62\u3057\u307e\u3059\u3002</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>\u672c\u4eba\u306e\u540c\u610f\u306a\u304f\u4ed6\u8005\u306e\u751f\u5e74\u6708\u65e5\u6642\u60c5\u5831\u306e\u5165\u529b</li>
          <li>\u30b5\u30fc\u30d3\u30b9\u3092\u5229\u7528\u3057\u305f\u7279\u5b9a\u500b\u4eba\u3078\u306e\u5ac1\u304c\u3089\u305b\u30fb\u5438\u5bb9</li>
          <li>\u9451\u5b9a\u7d50\u679c\u306e\u5927\u91cf\u30b9\u30af\u30ec\u30a4\u30d4\u30f3\u30b0\u30fb\u518d\u8ca9\u58f2\u30fb\u518d\u914d\u5e03</li>
          <li>\u30d7\u30ed\u30f3\u30d7\u30c8\u30fb\u57cb\u3081\u8fbce\u307f\u30fbRAG\u30bd\u30fc\u30b9\u306e\u30ea\u30d0\u30fc\u30b9\u30a8\u30f3\u30b8\u30cb\u30a2\u30ea\u30f3\u30b0</li>
          <li>\u9055\u6cd5\u30fb\u5dee\u5225\u7684\u30fb\u6027\u7684\u30b3\u30f3\u30c6\u30f3\u30c4\u306e\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9</li>
          <li>\u30ec\u30fc\u30c8\u5236\u9650\u30fb\u6c7a\u6e08\u8a8d\u8a3c\u306e\u56de\u907f</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">10. \u77e5\u7684\u8ca1\u7523\u6a29</h2>
        <p>SajuAstrology\u306e\u540d\u79f0\u30fb\u30d6\u30e9\u30f3\u30c9\u30fbRimSaju Engine\u30fb\u30a6\u30a7\u30d6\u30c7\u30b6\u30a4\u30f3\u30fb\u30b3\u30fc\u30c9\u30fb\u53e4\u5178\u30ad\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u306fRimfactory\u306e\u6240\u6709\u3067\u3059\u3002\u5229\u7528\u8005\u306f\u500b\u4eba\u7684\u30fb\u975e\u5546\u696d\u7684\u76ee\u7684\u306b\u9650\u308a\u3001\u9650\u5b9a\u7684\u30fb\u975e\u72ec\u5360\u7684\u30fb\u8b72\u6e21\u4e0d\u53ef\u306e\u30e9\u30a4\u30bb\u30f3\u30b9\u3092\u4ed8\u4e0e\u3055\u308c\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">11. \u5909\u66f4\u304a\u3088\u3073\u89e3\u7d04</h2>
        <p>\u30b5\u30fc\u30d3\u30b9\u306e\u4e00\u90e8\u3092\u3044\u3064\u3067\u3082\u5909\u66f4\u30fb\u4e2d\u65ad\u30fb\u7d42\u4e86\u3059\u308b\u3053\u3068\u304c\u3042\u308a\u307e\u3059\u3002\u91cd\u8981\u306a\u5909\u66f4\u306f\u30a6\u30a7\u30d6\u30b5\u30a4\u30c8\u4e0a\u3067\u65b0\u3057\u3044\u300c\u6700\u7d42\u66f4\u65b0\u65e5\u300d\u3092\u4ed8\u3051\u3066\u304a\u77e5\u3089\u305b\u3057\u307e\u3059\u3002\u5909\u66f4\u5f8c\u3082\u5f15\u304d\u7d9a\u304d\u30b5\u30fc\u30d3\u30b9\u3092\u3054\u5229\u7528\u306e\u5834\u5408\u3001\u5909\u66f4\u306b\u540c\u610f\u3057\u305f\u3082\u306e\u3068\u307f\u306a\u3057\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">12. \u4fdd\u8a3c\u306e\u5426\u8a8d</h2>
        <p>\u30b5\u30fc\u30d3\u30b9\u306f\u300c\u73fe\u72b6\u306e\u307e\u307e\u300d\u63d0\u4f9b\u3055\u308c\u307e\u3059\u3002\u6cd5\u5f8b\u304c\u8a31\u5bb9\u3059\u308b\u6700\u5927\u9650\u5ea6\u306b\u304a\u3044\u3066\u3001\u5546\u54c1\u6027\u30fb\u7279\u5b9a\u76ee\u7684\u9069\u5408\u6027\u30fbAI\u751f\u6210\u30b3\u30f3\u30c6\u30f3\u30c4\u306e\u6b63\u78ba\u6027\u306b\u95a2\u3059\u308b\u4fdd\u8a3c\u306f\u3059\u3079\u3066\u5426\u8a8d\u3057\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">13. \u8cac\u4efb\u306e\u5236\u9650</h2>
        <p className="mb-2">\u9069\u7528\u6cd5\u304c\u8a31\u5bb9\u3059\u308b\u6700\u5927\u9650\u5ea6\u306b\u304a\u3044\u3066\u3001Rimfactory\u306f\u9593\u63a5\u30fb\u5076\u767a\u7684\u30fb\u7279\u5225\u30fb\u6d3e\u751f\u7684\u640d\u5bb3\u306b\u3064\u3044\u3066\u8cac\u4efb\u3092\u8ca0\u3044\u307e\u305b\u3093\u3002\u8cac\u4efb\u306e\u7dcf\u984d\u306f\u3001\u8acb\u6c42\u767a\u751f\u524d12\u30f6\u6708\u306b\u5f53\u793e\u306b\u304a\u652f\u6255\u3044\u3044\u305f\u3060\u3044\u305f\u91d1\u984d\u307e\u305f\u306fUSD 100\u306e\u5927\u304d\u3044\u65b9\u3092\u8d85\u3048\u307e\u305b\u3093\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">14. \u7d1a\u54c1\u88dc\u511f</h2>
        <p>\u6cd5\u5f8b\u304c\u8a31\u5b66\u3059\u308b\u9650\u308a\u3001\u5229\u7528\u8005\u306f(a)\u672c\u898f\u7d04\u306e\u9055\u53cd\u3001(b)\u30b5\u30fc\u30d3\u30b9\u306e\u6fc3\u7528\u3001(c)\u7b2c\u4e09\u8005\u306e\u6a29\u5229\u4fb5\u5bb3\u3001(d)\u7b2c3\u6761\u306b\u9055\u53cd\u3059\u308b\u9451\u5b9a\u3078\u306e\u4f9d\u5b58\u304b\u3089\u751f\u3058\u308b\u8acb\u6c42\u304b\u3089Rimfactory\u3092\u5514\u8cac\u6d88\u6ec5\u3059\u308b\u3053\u3068\u306b\u540c\u610f\u3057\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">15. \u7d1a\u4e89\u89e3\u6c7a</h2>
        <p className="mb-2"><strong>\u975e\u516c\u5f0f\u89e3\u6c7a\u3092\u512a\u5148\u3002</strong>\u6b63\u5f0f\u306a\u624b\u7d9a\u304d\u306e\u524d\u306b\u3001<a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u307e\u3067\u3054\u9023\u7d61\u304f\u3060\u3055\u3044\u300230\u65e5\u9593\u306e\u8aa0\u5b9f\u306a\u89e3\u6c7a\u671f\u9593\u3092\u8a2d\u3051\u307e\u3059\u3002</p>
        <p className="mb-2"><strong>\u6e96\u62e0\u6cd5\u3002</strong>\u672c\u898f\u7d04\u306f\u5927\u97d3\u6c11\u56fd\u6cd5\u306b\u6e96\u62e0\u3057\u307e\u3059\u3002\u5c45\u4f4f\u56fd\u306e\u5f37\u884c\u7684\u6d88\u8cbb\u8005\u4fdd\u8b77\u898f\u5b9a\u306f\u5f71\u97ff\u3092\u53d7\u3051\u307e\u305b\u3093\u3002</p>
        <p><strong>\u7ba1\u8f44\u3002</strong>\u30bd\u30a6\u30eb\u4e2d\u592e\u5730\u65b9\u6cd5\u9662\u3092\u5c02\u5c5e\u7ba1\u8f44\u3068\u3057\u307e\u3059(\u5c45\u4f4f\u56fd\u306e\u5f37\u884c\u7684\u6d88\u8cbb\u8005\u4fdd\u8b77\u898f\u5b9a\u3092\u9664\u304f)\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">16. \u5206\u96e2\u53ef\u80fd\u6027\u304a\u3088\u3073\u5b8c\u5168\u306a\u5408\u610f</h2>
        <p>\u4e00\u90e8\u6761\u9805\u304c\u7121\u52b9\u3068\u5224\u65ad\u3055\u308c\u3066\u3082\u3001\u6b8b\u308a\u306e\u6761\u9805\u306f\u5f15\u304d\u7d9a\u304d\u6709\u52b9\u3067\u3059\u3002\u672c\u898f\u7d04\u3068\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u30dd\u30ea\u30b7\u30fc\u304c\u3001\u30b5\u30fc\u30d3\u30b9\u306b\u95a2\u3059\u308bRimfactory\u3068\u5229\u7528\u8005\u9593\u306e\u5b8c\u5168\u306a\u5408\u610f\u3092\u69cb\u6210\u3057\u307e\u3059\u3002</p>
      </section>

      <section>
        <h2 className="text-lg font-serif text-primary mb-3">\u304a\u554f\u3044\u5408\u308f\u305b</h2>
        <div className="bg-card/50 border border-border rounded-xl p-4">
          <p><strong>Rimfactory</strong> \u2014 243, 1F, Sindorim Technomart, 97 Saemal-ro, Guro-gu, Seoul 08213, \u5927\u97d3\u6c11\u56fd</p>
          <p className="mt-1">\u4e8b\u696d\u8005\u767b\u9332\u756a\u53f7: 402-44-01247</p>
          <p className="mt-1">\u30e1\u30fc\u30eb: <a href="mailto:info@rimfactory.io" className="text-primary hover:underline">info@rimfactory.io</a> \u00b7 \u96fb\u8a71: +82-10-4648-6793</p>
        </div>
      </section>
    </div>
  )
}

// ─── Main Page ───────────────────────────────────────────────────────────────
export default function TermsPage() {
  const [lang, setLang] = useState<"en" | "ko" | "ja">("en")

  useEffect(() => {
    setLang(detectLocale())
  }, [])

  const titles: Record<"en" | "ko" | "ja", string> = {
    en: "Terms of Service",
    ko: "\uc774\uc6a9\uc57d\uad00",
    ja: "\u5229\u7528\u898f\u7d04",
  }
  const dates: Record<"en" | "ko" | "ja", string> = {
    en: "Last updated: 2 May 2026",
    ko: "\ucd5c\uc885 \uc218\uc815\uc77c: 2026\ub144 5\uc6d4 2\uc77c",
    ja: "\u6700\u7d42\u66f4\u65b0\u65e5: 2026\u5e745\u67082\u65e5",
  }

  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="pt-page pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          <h1 className="text-3xl md:text-4xl font-serif text-primary mb-2">{titles[lang]}</h1>
          <p className="text-sm text-muted-foreground mb-6">{dates[lang]}</p>
          <LangToggle active={lang} onChange={setLang} />
          {lang === "ko" ? <TermsKO /> : lang === "ja" ? <TermsJA /> : <TermsEN />}
        </div>
      </div>
      <Footer />
    </main>
  )
}
