// Pre-written content for each archetype

export const ARCHETYPE_CONTENT = {
  "The Ally": {
    title: "The Ally",
    subtitle: "Steadfast Companion of the Cosmic Order",
    personality: "You possess an unwavering sense of loyalty and a deep understanding of collaborative energy. Your presence brings stability to any group, and others naturally trust your judgment. You see the world through a lens of fairness and mutual benefit.",
    strengths: ["Natural team player", "Highly dependable", "Strong sense of justice", "Excellent at maintaining harmony"],
    challenges: ["May struggle with independence", "Can be overly competitive with peers", "Sometimes resistant to change"],
    career: "Your cosmic blueprint suggests success in partnerships, law, human resources, diplomacy, and any field requiring collaboration. You thrive when working alongside others toward shared goals. Consider roles in mediation, team leadership, or cooperative ventures.",
    relationships: "In relationships, you seek true equals. You're drawn to partners who match your energy and commitment. Your challenge is maintaining your individual identity while deeply merging with another.",
    yearlyOutlook: "This year brings opportunities to strengthen existing bonds and form powerful new alliances. The cosmos favors joint ventures and collaborative projects. Trust those who prove themselves worthy.",
  },
  "The Maverick": {
    title: "The Maverick",
    subtitle: "Bold Challenger of Convention",
    personality: "You carry a fierce independent spirit that refuses to be contained by tradition. Your energy is dynamic and sometimes disruptive—you see opportunities where others see obstacles. You're not afraid to take risks that make others uncomfortable.",
    strengths: ["Fearless initiative", "Quick to seize opportunities", "Magnetic charisma", "Thrives under pressure"],
    challenges: ["Impulsive decision-making", "Difficulty with authority", "May alienate conservative allies"],
    career: "Your path leads toward entrepreneurship, high-stakes finance, competitive sports, or any field requiring bold moves. You excel in environments where conventional rules don't apply. Consider startups, trading, or pioneering new industries.",
    relationships: "You need a partner who can match your intensity without trying to tame you. Traditional relationship structures may feel confining. Seek someone who celebrates your wildness.",
    yearlyOutlook: "This year rewards calculated risks and bold moves. The universe is clearing obstacles for those brave enough to act. However, pace yourself—not every battle needs to be fought.",
  },
  "The Creator": {
    title: "The Creator",
    subtitle: "Vessel of Cosmic Expression",
    personality: "You are a natural channel for creative energy, transforming the raw materials of life into something beautiful and meaningful. Your mind works in patterns others can't perceive, and you find joy in the act of making. Abundance flows through creative expression.",
    strengths: ["Exceptional creativity", "Natural contentment", "Ability to nurture ideas", "Gentle strength"],
    challenges: ["May avoid confrontation", "Can be too passive", "Sometimes scattered focus"],
    career: "The arts, culinary fields, content creation, teaching, and healing professions align with your energy. You thrive when given space to create without harsh deadlines. Consider design, writing, cooking, or therapeutic practices.",
    relationships: "You bring warmth and creativity to partnerships, often expressing love through acts of creation. Seek partners who appreciate your gentle nature without exploiting it.",
    yearlyOutlook: "This year overflows with creative potential. Projects started now have cosmic momentum. Focus on bringing one or two visions to completion rather than starting many.",
  },
  "The Rebel": {
    title: "The Rebel",
    subtitle: "Sacred Disruptor of Stagnation",
    personality: "You possess a sharp intellect and an even sharper tongue. The status quo is your natural enemy—you see through pretense and aren't afraid to name uncomfortable truths. Your role is to question, challenge, and ultimately transform.",
    strengths: ["Brilliant analytical mind", "Fearless truth-telling", "Innovative thinking", "Charismatic presence"],
    challenges: ["Can be needlessly provocative", "Difficulty with authority", "May burn bridges prematurely"],
    career: "Innovation, reform, investigative fields, and any domain requiring fresh perspectives suit you. You excel at disrupting outdated systems. Consider technology, journalism, activism, or creative destruction.",
    relationships: "You need intellectual equals who can spar with you without taking offense. Avoid partners who try to domesticate your wild energy. The right person will find your edge exciting.",
    yearlyOutlook: "This year demands authenticity. Speak your truth, but learn the art of timing. The cosmos supports transformation—focus your disruptive energy on systems that truly need changing.",
  },
  "The Adventurer": {
    title: "The Adventurer",
    subtitle: "Seeker of Fortune and Freedom",
    personality: "You are driven by an insatiable curiosity and a talent for discovering hidden value. Money and resources flow through your life like water—sometimes in torrents, sometimes in droughts. You understand that true wealth comes from movement.",
    strengths: ["Financial intuition", "Adaptability", "Networking prowess", "Opportunity recognition"],
    challenges: ["Inconsistent income", "Restlessness", "May struggle with commitment"],
    career: "Sales, trading, travel industry, import/export, and speculative ventures align with your nature. You need variety and the potential for windfall gains. Consider careers that combine travel with commerce.",
    relationships: "You're drawn to exciting, somewhat unpredictable partners. Long-distance relationships or unconventional arrangements may suit you. Seek someone who values freedom as much as you do.",
    yearlyOutlook: "Unexpected financial opportunities arise this year. Stay alert to chance encounters and be ready to move quickly. The cosmos rewards those who combine luck with preparation.",
  },
  "The Builder": {
    title: "The Builder",
    subtitle: "Architect of Lasting Prosperity",
    personality: "You possess a rare gift for creating tangible, lasting wealth. Unlike the Adventurer who chases windfalls, you understand that true prosperity comes from patient accumulation and wise stewardship. You build empires brick by brick.",
    strengths: ["Financial discipline", "Long-term planning", "Reliability", "Practical wisdom"],
    challenges: ["Can be overly cautious", "May miss bold opportunities", "Sometimes materialistic"],
    career: "Banking, real estate, accounting, engineering, and any field requiring systematic wealth-building suit you. You excel in roles with clear metrics and steady progression. Consider property development or financial planning.",
    relationships: "You seek stable, practical partners who share your values around security. Romance for you often involves building something together—a home, a business, a legacy.",
    yearlyOutlook: "This year favors consolidation and strategic investment. The foundations you lay now will support decades of growth. Avoid the temptation to chase quick gains at the expense of steady progress.",
  },
  "The Commander": {
    title: "The Commander",
    subtitle: "Wielder of Decisive Power",
    personality: "You carry an intense, almost warrior-like energy that demands respect. You're not interested in subtle influence—you prefer direct action and clear results. Others sense your power and either follow or get out of the way.",
    strengths: ["Decisive action", "Natural authority", "Crisis leadership", "Unflinching courage"],
    challenges: ["Can be domineering", "Difficulty with compromise", "May create unnecessary conflict"],
    career: "Military, surgery, high-level management, crisis intervention, and competitive fields suit your energy. You excel under pressure when others falter. Consider executive leadership or emergency services.",
    relationships: "You need partners strong enough to stand beside you without competing against you. Avoid relationships that feel like power struggles—seek complementary strength instead.",
    yearlyOutlook: "This year presents battles worth fighting. Choose them wisely. Your natural authority will be tested and ultimately strengthened. Victory favors the strategic over the merely aggressive.",
  },
  "The Leader": {
    title: "The Leader",
    subtitle: "Righteous Guide of the People",
    personality: "You embody legitimate authority—the kind that comes from integrity rather than force. People follow you not because they fear you, but because they trust your judgment. You carry responsibility with grace and use power ethically.",
    strengths: ["Natural integrity", "Organizational talent", "Diplomatic skill", "Respected presence"],
    challenges: ["Can be rigid", "May prioritize duty over joy", "Sometimes overly conventional"],
    career: "Government, corporate leadership, law, education administration, and any role requiring moral authority suit you. You excel in positions of legitimate power with clear responsibilities.",
    relationships: "You seek partners who respect tradition and share your values. Your relationships often have a formal quality—you show love through protection and provision.",
    yearlyOutlook: "This year elevates your status and influence. Responsibilities increase, but so does recognition. The cosmos rewards ethical leadership—continue to lead by example.",
  },
  "The Visionary": {
    title: "The Visionary",
    subtitle: "Seer of Hidden Patterns",
    personality: "Your mind operates on frequencies others can't access. You perceive connections, patterns, and possibilities invisible to ordinary perception. Your ideas often seem ahead of their time—because they are.",
    strengths: ["Intuitive brilliance", "Unconventional wisdom", "Creative problem-solving", "Spiritual depth"],
    challenges: ["Can seem eccentric", "May struggle with practical matters", "Sometimes emotionally detached"],
    career: "Research, philosophy, technology innovation, alternative healing, and any field requiring breakthrough thinking suit you. You excel at seeing what others miss. Consider academia or cutting-edge development.",
    relationships: "You need partners who appreciate your unusual perspective without demanding conventional expressions of emotion. Seek intellectual and spiritual connection above all.",
    yearlyOutlook: "This year brings flashes of genuine insight. Trust your unconventional ideas—they're seeds of future innovation. The cosmos speaks to you in symbols and synchronicities; pay attention.",
  },
  "The Mentor": {
    title: "The Mentor",
    subtitle: "Keeper of Sacred Knowledge",
    personality: "You are a natural teacher and guide, possessing wisdom that others seek. Your presence is calming, and your words carry weight. You understand that knowledge is meant to be shared, and you find fulfillment in nurturing others' growth.",
    strengths: ["Natural wisdom", "Patient teaching", "Protective care", "Emotional intelligence"],
    challenges: ["Can be overprotective", "May neglect self-care", "Sometimes passive-aggressive"],
    career: "Teaching, counseling, medicine, parenting-related fields, and any role involving guidance suit you. You excel at developing others' potential. Consider education, therapy, or mentorship programs.",
    relationships: "You often attract partners who need your guidance, but the healthiest relationships occur when you find an equal who can also teach you. Balance nurturing with receiving care.",
    yearlyOutlook: "This year asks you to share your knowledge more widely. A student or mentee may bring unexpected rewards. The cosmos multiplies wisdom that is freely given.",
  },
};

export const ELEMENT_DESCRIPTIONS = {
  wood: {
    name: "Wood",
    quality: "Growth & Expansion",
    description: "Wood energy represents growth, flexibility, and new beginnings. Like a tree reaching toward the sun, Wood types are ambitious yet adaptable, always seeking to expand their horizons.",
    positive: "Creative, compassionate, visionary, growth-oriented",
    shadow: "Anger when obstructed, impatience, over-extension",
  },
  fire: {
    name: "Fire",
    quality: "Illumination & Passion",
    description: "Fire energy brings warmth, visibility, and transformation. Fire types are charismatic and passionate, naturally drawing others toward their light. They excel at inspiring and leading.",
    positive: "Charismatic, joyful, intuitive, inspirational",
    shadow: "Anxiety, scattered attention, burnout, hysteria",
  },
  earth: {
    name: "Earth",
    quality: "Stability & Nurturance",
    description: "Earth energy provides grounding, stability, and nurturing support. Earth types are reliable and thoughtful, creating safe spaces for others to thrive. They excel at building lasting foundations.",
    positive: "Reliable, nurturing, practical, centered",
    shadow: "Worry, overthinking, stubbornness, stagnation",
  },
  metal: {
    name: "Metal",
    quality: "Precision & Value",
    description: "Metal energy represents refinement, precision, and discernment. Metal types have high standards and strong boundaries, naturally separating the valuable from the worthless.",
    positive: "Disciplined, discerning, organized, principled",
    shadow: "Grief, rigidity, criticism, isolation",
  },
  water: {
    name: "Water",
    quality: "Wisdom & Depth",
    description: "Water energy embodies depth, wisdom, and the power of stillness. Water types are introspective and perceptive, able to navigate complex situations with fluidity and grace.",
    positive: "Wise, adaptable, reflective, resourceful",
    shadow: "Fear, isolation, secretiveness, depression",
  },
};
