// Traditional Chinese Daily Fortune Messages (繁體中文)
import type { DailyFortune } from "./daily-fortune";
type Tier = "high" | "mid" | "low";

export const FORTUNES_ZHTW: Record<string, Record<Tier, DailyFortune[]>> = {
  wood: {
    high: [
      { message: "今日你的創造能量達到巔峰。正午前湧現的想法最具力量。", advice: "啟動新專案或提出一個想法。", luckyColor: "綠色", luckyColorHex: "#59DE9B", luckyDirection: "東方", luckyActivity: "林間漫步", shareText: "今天我的木氣爆棚 🌿 創意突破即將到來" },
      { message: "成長機會環繞著你。今天的一場對話可能開啟意想不到的大門。", advice: "對臨時邀約說「好」。", luckyColor: "青綠", luckyColorHex: "#2DD4BF", luckyDirection: "東南", luckyActivity: "晨間日記", shareText: "宇宙說今天是我成長的日子 🌱" },
      { message: "你天生的領導力閃耀。他人不自覺地尋求你的方向。", advice: "在團體中主動發言 — 你的話有份量。", luckyColor: "翡翠綠", luckyColorHex: "#00A86B", luckyDirection: "東方", luckyActivity: "團隊協作", shareText: "甲木能量強大 — 今天是天生的領袖 甲" },
      { message: "幾週前播下的種子開始發芽。過去努力的成果即將顯現。", advice: "跟進一件你一直在等待的事。", luckyColor: "祖母綠", luckyColorHex: "#50C878", luckyDirection: "東北", luckyActivity: "園藝或用新鮮香草烹飪", shareText: "過去的努力今天開花結果 — 耐心勝利 🌿" },
      { message: "柔韌是你今天的超能力。柔而不斷,你會找到完美的路。", advice: "調整計畫而非強行推進。", luckyColor: "萊姆綠", luckyColorHex: "#84CC16", luckyDirection: "東方", luckyActivity: "伸展或瑜伽", shareText: "木可彎不可折 — 今天我無人能擋 💚" },
      { message: "下午會有一波創作靈感來襲。隨時準備好捕捉想法。", advice: "隨身帶筆記本或用語音備忘。", luckyColor: "森林綠", luckyColorHex: "#228B22", luckyDirection: "東南", luckyActivity: "創意寫作或素描", shareText: "下午靈感爆發 — 我的木元素知道 🎋" },
      { message: "你的慈悲吸引需要指引的人。你天生的智慧幫助的比你想像得更多。", advice: "今天多聽少說。", luckyColor: "鼠尾草綠", luckyColorHex: "#9CAF88", luckyDirection: "東方", luckyActivity: "指導或教學", shareText: "我的木氣今天治癒他人 🌳 天生導師模式啟動" },
      { message: "擴張能量強盛。今天啟動的一切都有絕佳的成長潛力。", advice: "發佈、上線、開始 — 時機利於新起步。", luckyColor: "春綠色", luckyColorHex: "#00FF7F", luckyDirection: "東方", luckyActivity: "開始新事物", shareText: "全新起步能量最大化 ☘️" },
      { message: "你的道德羅盤今天校準精準。相信你的是非感。", advice: "做那個你一直推遲的決定。", luckyColor: "橄欖綠", luckyColorHex: "#808000", luckyDirection: "東北", luckyActivity: "整理空間", shareText: "相信直覺 — 我的四柱確認了 ✅" },
      { message: "想法之間的連結自然形成。你看見別人錯過的模式。", advice: "分享你的洞察 — 比你想的更有價值。", luckyColor: "薄荷綠", luckyColorHex: "#98FF98", luckyDirection: "東南", luckyActivity: "腦力激盪", shareText: "模式辨識:啟動 🧠🌿" },
    ],
    mid: [
      { message: "穩定成長的一天。沒有戲劇性,但根在地下深扎。", advice: "專注於持續而非強度。", luckyColor: "蕨綠色", luckyColorHex: "#4F7942", luckyDirection: "東方", luckyActivity: "例行維護任務", shareText: "寧靜成長之日 — 紮穩根基 🌿" },
      { message: "適合滋養既有關係,而非建立新關係的一天。", advice: "聯絡好久沒說話的人。", luckyColor: "苔蘚綠", luckyColorHex: "#8A9A5B", luckyDirection: "東南", luckyActivity: "與老友敘舊", shareText: "滋養模式啟動 — 加深連結的好能量 💚" },
      { message: "耐心受考驗但也獲報酬。今天緩慢之路通向更美好。", advice: "抗拒急躁的衝動。讓事情自然展開。", luckyColor: "綠色", luckyColorHex: "#59DE9B", luckyDirection: "東方", luckyActivity: "閱讀或學習", shareText: "耐心是我今天的超能力 — 木教我時機 🎋" },
      { message: "中等創造力。適合精煉現有想法,而非產生新想法。", advice: "編輯、打磨、改進你已經開始的。", luckyColor: "開心果綠", luckyColorHex: "#93C572", luckyDirection: "東北", luckyActivity: "編輯與修訂", shareText: "打磨之日 — 讓好變卓越 🌱" },
      { message: "今天的關鍵是給與受的平衡。你傾向於付出太多。", advice: "當別人提供幫助時,接受。", luckyColor: "鼠尾草綠", luckyColorHex: "#9CAF88", luckyDirection: "東方", luckyActivity: "自我照護儀式", shareText: "今天學習接受 — 平衡是一切 ⚖️🌿" },
      { message: "適合財務決策的穩定日。不適合冒險,但適合儲蓄。", advice: "檢視預算或設定自動儲蓄。", luckyColor: "獵人綠", luckyColorHex: "#355E3B", luckyDirection: "東南", luckyActivity: "財務規劃", shareText: "今天財務能量穩定 — 不求大動作,只做聰明動作 💰" },
      { message: "你的身體今天要求運動。身體活動能清除精神迷霧。", advice: "走20分鐘,最好靠近綠地。", luckyColor: "萊姆綠", luckyColorHex: "#84CC16", luckyDirection: "東方", luckyActivity: "戶外運動", shareText: "身體說動起來 — 星辰也同意 🏃🌿" },
      { message: "適合學習而非教導的好能量。先吸收再散播。", advice: "閱讀、聆聽或參加線上課程。", luckyColor: "青綠", luckyColorHex: "#2DD4BF", luckyDirection: "東北", luckyActivity: "學習新事物", shareText: "今天學生模式 — 像海綿吸收知識 📚" },
      { message: "關係從今天的誠實中受益。溫和的真相能強化羈絆。", advice: "進行你一直迴避的那段對話。", luckyColor: "薄荷綠", luckyColorHex: "#98FF98", luckyDirection: "東方", luckyActivity: "誠實對話", shareText: "說真話之日 — 誠實建立信任 🌿💬" },
      { message: "你的環境比平常更重要。乾淨空間 = 清晰思維。", advice: "花15分鐘整理工作空間。", luckyColor: "祖母綠", luckyColorHex: "#50C878", luckyDirection: "東南", luckyActivity: "整理與清潔", shareText: "乾淨空間,清晰思維 — 我的木元素要求秩序 🧹" },
    ],
    low: [
      { message: "你的木氣今天感覺被壓縮。成長暫停,並非停止。", advice: "無愧地休息。連大樹也會冬眠。", luckyColor: "深綠", luckyColorHex: "#006400", luckyDirection: "東方", luckyActivity: "午睡或冥想", shareText: "休息日 — 連強大的橡樹也需要靜止 🌳💤" },
      { message: "創意受阻但清晰度提升。用今天分析,不要創作。", advice: "整理、組織、規劃,而非創造。", luckyColor: "橄欖色", luckyColorHex: "#808000", luckyDirection: "東北", luckyActivity: "規劃與分析", shareText: "分析模式啟動 — 有時停下來才能創造空間 🌿" },
      { message: "金氣今天約束你。不要對抗 — 在限制中找到結構。", advice: "在約束中工作,而非對抗它。", luckyColor: "森林綠", luckyColorHex: "#228B22", luckyDirection: "東方", luckyActivity: "在界限中工作", shareText: "約束孕育創造力 — 聰明運用今日限制 🎋" },
      { message: "能量低不代表價值低。你最棒的洞察常在靜謐時刻出現。", advice: "獨自與思緒相處。", luckyColor: "鼠尾草綠", luckyColorHex: "#9CAF88", luckyDirection: "東南", luckyActivity: "獨自反思", shareText: "靜謐時刻蘊含智慧 — 今天聆聽 🌱🤫" },
      { message: "你的肝和眼睛今天需要額外照顧。可能的話日落後避免螢幕。", advice: "吃深綠葉蔬菜,讓眼睛休息。", luckyColor: "綠色", luckyColorHex: "#59DE9B", luckyDirection: "東方", luckyActivity: "晚餐後數位排毒", shareText: "今天以自我照護為先 — 尊重身體 💚" },
      { message: "社交能量低。保護你的空間,不需為此道歉。", advice: "拒絕讓你耗能的邀約。", luckyColor: "苔蘚綠", luckyColorHex: "#8A9A5B", luckyDirection: "東方", luckyActivity: "獨處與寧靜", shareText: "界限即自愛 — 今天為自己留空間 🌿🛡️" },
      { message: "建議財務上謹慎。不宜投資或大額消費。", advice: "購物留到別天。", luckyColor: "深苔綠", luckyColorHex: "#4A5D23", luckyDirection: "東北", luckyActivity: "編列預算與儲蓄", shareText: "今天錢包關起來 — 星辰建議耐心 💰🌿" },
      { message: "過去的遺憾可能浮現。承認它,然後溫柔放下。", advice: "寫下困擾你的事,然後合上本子。", luckyColor: "蕨綠", luckyColorHex: "#4F7942", luckyDirection: "東方", luckyActivity: "寫日記", shareText: "放下無法服務我的 — 減輕負擔 🍃" },
      { message: "你平常的柔韌今天感覺僵硬。沒關係 — 有時靜止就是答案。", advice: "今晚睡前做溫和伸展。", luckyColor: "松綠", luckyColorHex: "#01796F", luckyDirection: "東南", luckyActivity: "輕柔伸展", shareText: "靜止即力量 — 今天回到根 🌲" },
      { message: "別人今天可能誤解你。不要過度解釋 — 時間會澄清。", advice: "讓誤會自然化解。", luckyColor: "羅勒綠", luckyColorHex: "#487800", luckyDirection: "東方", luckyActivity: "練習耐心", shareText: "不是所有事都需要解釋 — 信任過程 🌿" },
    ],
  },
  fire: {
    high: [
      { message: "你的魅力今天具有磁性。人們被你的溫暖吸引卻說不出原因。", advice: "用你的影響力做有意義的事。", luckyColor: "紅色", luckyColorHex: "#EF4444", luckyDirection: "南方", luckyActivity: "公開演講或報告", shareText: "火焰能量今天燃燒 🔥 魅力勢不可擋" },
      { message: "熱情與清晰完美對齊。你渴望的與正確的是同一件事。", advice: "毫不猶豫追求那個目標。", luckyColor: "深紅", luckyColorHex: "#DC143C", luckyDirection: "南方", luckyActivity: "採取大膽行動", shareText: "心與腦對齊 — 今天我全力以赴 🔥❤️" },
      { message: "你的熱情點燃他人。看你的能量如何轉變整個空間。", advice: "以啟發帶領,而非以指示。", luckyColor: "橘紅", luckyColorHex: "#FF4500", luckyDirection: "西南", luckyActivity: "團體活動", shareText: "讓房間燃起來(好的那種)🔥✨" },
      { message: "認可能量強盛。你的努力即將被看見。", advice: "今天別貶低自己的成就。", luckyColor: "珊瑚色", luckyColorHex: "#FF7F50", luckyDirection: "南方", luckyActivity: "展示你的作品", shareText: "認可即將到來 — 宇宙看見我的努力 🌟🔥" },
      { message: "浪漫能量達到巔峰。如果正在尋覓,今天支持大膽行動。", advice: "直接表達你的感受。", luckyColor: "玫瑰紅", luckyColorHex: "#C21E56", luckyDirection: "南方", luckyActivity: "約會或告白", shareText: "火焰 + 浪漫 = 今天 🔥💕 勇敢的心獲勝" },
      { message: "你的直覺燃穿迷惑。相信第一個浮現的答案。", advice: "今天的第一個決定跟著直覺走。", luckyColor: "猩紅", luckyColorHex: "#FF2400", luckyDirection: "東南", luckyActivity: "果斷行動", shareText: "直覺燃燒 — 相信那道火花 🔥⚡" },
      { message: "競爭能量對你有利。運動、商業或遊戲 — 全力求勝。", advice: "把最好狀態帶到任何挑戰。", luckyColor: "烈焰色", luckyColorHex: "#E25822", luckyDirection: "南方", luckyActivity: "競賽或運動", shareText: "競賽之日 — 火元素說我贏 🏆🔥" },
      { message: "喜悅今天從你身上散發。慷慨分享 — 給出去時會倍增。", advice: "做一件讓別人笑的事。", luckyColor: "橘黃", luckyColorHex: "#FF9966", luckyDirection: "西南", luckyActivity: "讓他人微笑", shareText: "喜悅機器啟動 — 到處散播溫暖 🔥😊" },
      { message: "創造之火今天純淨燃燒。藝術表達流暢無阻。", advice: "創造點什麼 — 什麼都行。媒介不重要。", luckyColor: "紅寶石", luckyColorHex: "#E0115F", luckyDirection: "南方", luckyActivity: "藝術創作", shareText: "藝術模式:啟動 🎨🔥 繆思在這裡" },
      { message: "轉化能量達到巔峰。舊的東西今天可以重生 — 如果你允許。", advice: "用全新眼光重新看那個擱置的計畫。", luckyColor: "鳳凰紅", luckyColorHex: "#CD2029", luckyDirection: "南方", luckyActivity: "復興舊計畫", shareText: "今日鳳凰能量 — 死去的重生 🔥🦅" },
    ],
    mid: [
      { message: "今天火焰溫暖穩定。適合維持,不適合開始。保持火苗燃燒。", advice: "堅持既有的承諾。", luckyColor: "蜜桃色", luckyColorHex: "#FFCBA4", luckyDirection: "南方", luckyActivity: "完成任務", shareText: "今天穩定火苗 — 持續就是力量 🕯️" },
      { message: "心敞開但能量中等。選一個人專注。", advice: "今天關係品質勝過數量。", luckyColor: "鮭魚粉", luckyColorHex: "#FA8072", luckyDirection: "西南", luckyActivity: "一對一時間", shareText: "今天把火集中在一件事上 — 深度勝過廣度 🔥" },
      { message: "適合規劃而非執行的好日子。規劃你的下一個大膽之舉。", advice: "行動前停下來好好規劃。", luckyColor: "赤陶色", luckyColorHex: "#E2725B", luckyDirection: "南方", luckyActivity: "策略規劃", shareText: "策略家模式啟動 — 規劃下一步 🔥📋" },
      { message: "靈感中等。好想法會出現但需醞釀才能行動。", advice: "讓想法靜置24小時。", luckyColor: "淺桃色", luckyColorHex: "#FFDAB9", luckyDirection: "南方", luckyActivity: "帶筆記的冥想", shareText: "好想法需要空間 — 讓它沉澱 💭🔥" },
      { message: "社交能量愉快但不炸裂。享受陪伴不需表演。", advice: "做自己 — 別刻意當焦點。", luckyColor: "琥珀色", luckyColorHex: "#FFBF00", luckyDirection: "西南", luckyActivity: "輕鬆聚會", shareText: "今天舒服的氛圍 — 做我,不費力 🔥✨" },
      { message: "心知道某些大腦尚未領會的事。給感受空間。", advice: "不批判地寫下你的感受。", luckyColor: "磚紅色", luckyColorHex: "#CB4154", luckyDirection: "南方", luckyActivity: "情感反思", shareText: "心先知道 — 今天聆聽 🔥💛" },
      { message: "財務能量中性。不宜大賭注,但適合小投資。", advice: "今天小而穩贏得比賽。", luckyColor: "金色", luckyColorHex: "#FFD700", luckyDirection: "南方", luckyActivity: "檢視支出", shareText: "今天要智慧的錢,不是大錢 💰🔥" },
      { message: "身體需要運動讓火氣循環。靜止會造成停滯。", advice: "今天做有氧或跳舞20分鐘。", luckyColor: "番茄紅", luckyColorHex: "#FF6347", luckyDirection: "南方", luckyActivity: "舞蹈或有氧", shareText: "動起來讓我的火活著 🔥🏃" },
      { message: "今天溝通順暢。適合電郵、通話、訊息。", advice: "發送那些一直在草稿的訊息。", luckyColor: "淺珊瑚色", luckyColorHex: "#FA8072", luckyDirection: "西南", luckyActivity: "寄送通訊", shareText: "今天話語流暢 — 輕鬆連結 🔥💬" },
      { message: "感恩今天擁有的一天。感恩放大火焰能量。", advice: "寫下三件感恩的事。", luckyColor: "玫瑰金", luckyColorHex: "#E8B4B8", luckyDirection: "南方", luckyActivity: "感恩練習", shareText: "感恩加強火焰 — 今天心懷感謝 🔥🙏" },
    ],
    low: [
      { message: "你的火低。自然 — 火焰不可能永遠燃燒到頂點。", advice: "無愧地放慢。", luckyColor: "深赤陶", luckyColorHex: "#A0522D", luckyDirection: "南方", luckyActivity: "身體休息", shareText: "今天小火之日 — 所有火都需要休息 🔥💤" },
      { message: "動力稀少但內在清晰增長。今天用來思考,不要推進。", advice: "寫下你真正想要的。", luckyColor: "青銅色", luckyColorHex: "#CD7F32", luckyDirection: "南方", luckyActivity: "深度反思", shareText: "少做多思考 — 向內潛入 🔥🧘" },
      { message: "情緒可能被放大。反應性強 — 回應前先呼吸。", advice: "任何反應前先數到十。", luckyColor: "酒紅色", luckyColorHex: "#800020", luckyDirection: "南方", luckyActivity: "有意識呼吸", shareText: "反應前先呼吸 — 火需要紀律 🔥🌬️" },
      { message: "浪漫上的疲憊是真的。不要逼自己熱情。", advice: "靜靜的溫暖比強迫的熱情更珍貴。", luckyColor: "柔粉色", luckyColorHex: "#E8899C", luckyDirection: "南方", luckyActivity: "輕柔愛意", shareText: "今天柔軟的愛 — 不是每團火都要燒很旺 💕🔥" },
      { message: "心需要保護。今天避免激烈討論或戲劇。", advice: "從衝突中抽身 — 明天再回來。", luckyColor: "粉塵色", luckyColorHex: "#DCAE96", luckyDirection: "南方", luckyActivity: "避開戲劇", shareText: "今天守護我的心 — 和平勝過戲劇 🔥🛡️" },
      { message: "自信可能動搖。提醒自己過去的成功 — 那是真實的。", advice: "重讀你保存的正面筆記。", luckyColor: "鐵鏽色", luckyColorHex: "#B7410E", luckyDirection: "南方", luckyActivity: "回顧過去成就", shareText: "履歷說話 — 我不會忘記達成過什麼 🔥🏆" },
      { message: "可能有社交焦慮。今天對大型活動說不沒關係。", advice: "保護你的能量 — 你的界限是有效的。", luckyColor: "柔桃色", luckyColorHex: "#CC9966", luckyDirection: "南方", luckyActivity: "家中安靜時光", shareText: "家中安靜夜 > 派對 — 選擇和平 🏠🔥" },
      { message: "消化可能緩慢。今天吃清淡,避免辛辣。", advice: "熱湯或熱茶,不要重食。", luckyColor: "奶油色", luckyColorHex: "#FFFDD0", luckyDirection: "南方", luckyActivity: "輕柔料理", shareText: "簡單食物,身體開心 — 尊重我的系統 🍵🔥" },
      { message: "今晚可能失眠。即使身體累,心智卻過度活躍。", advice: "睡前一小時遠離螢幕。", luckyColor: "靛藍", luckyColorHex: "#4B0082", luckyDirection: "南方", luckyActivity: "平靜的夜間儀式", shareText: "關閉螢幕,點亮休息 🌙🔥" },
      { message: "後悔可能湧現。原諒自己 — 所有的火都會犯錯。", advice: "寫一封慈悲的信給自己。", luckyColor: "磚色", luckyColorHex: "#8B4513", luckyDirection: "南方", luckyActivity: "自我慈悲", shareText: "今天原諒自己 — 成長包含失敗 🔥💛" },
    ],
  },
  earth: {
    high: [
      { message: "你的根基今天堅不可摧。他人在混亂中尋求你的穩定。", advice: "對需要的人提供支持。", luckyColor: "赤陶色", luckyColorHex: "#E2725B", luckyDirection: "中央", luckyActivity: "接觸大地", shareText: "今天土氣穩固 — 我的根基堅不可摧 🏔️" },
      { message: "你的耐心建造帝國。今天每一小步都重要。", advice: "以恆心持續那個長期計畫。", luckyColor: "沙色", luckyColorHex: "#C2B280", luckyDirection: "中央", luckyActivity: "緩慢穩定的進展", shareText: "建造持久之物 — 一步一步 🏔️🧱" },
      { message: "你的忠誠被認可。某個親近的人感激你的穩定存在。", advice: "當別人表達感謝時,接受。", luckyColor: "金棕色", luckyColorHex: "#996515", luckyDirection: "中央", luckyActivity: "與家人或親友相處", shareText: "土氣忠誠被認可 — 堅固的連結很重要 🏔️💛" },
      { message: "你的組織能力閃耀。混亂的計畫在你手中找到秩序。", advice: "主動幫某人整理。", luckyColor: "卡其色", luckyColorHex: "#C3B091", luckyDirection: "中央", luckyActivity: "組織與系統", shareText: "今天從混亂中創造秩序 — 土之魔法 ⛰️✨" },
      { message: "你的真實吸引對的人。別再假裝了。", advice: "做你自己 — 已經足夠。", luckyColor: "卡其棕", luckyColorHex: "#D2B48C", luckyDirection: "中央", luckyActivity: "真誠對話", shareText: "今天做真實的自己 — 大地不偽裝 🏔️💯" },
      { message: "你的實用感今天幫你省錢。一個明智決定避免了不必要的開銷。", advice: "任何大額購買前等48小時。", luckyColor: "赭色", luckyColorHex: "#CC7722", luckyDirection: "中央", luckyActivity: "檢視財務", shareText: "今天土之智慧省錢 💰⛰️" },
      { message: "你提供的穩定吸引機會。今天可靠的人獲勝。", advice: "當個可靠的人,看大門如何為你打開。", luckyColor: "赭黃色", luckyColorHex: "#A0522D", luckyDirection: "中央", luckyActivity: "展示可靠", shareText: "今天當一塊岩石 — 可靠有回報 🏔️🗝️" },
      { message: "你的母性/父性照顧被需要。生活中有人今天需要滋養。", advice: "為你愛的人準備一餐。", luckyColor: "蜂蜜色", luckyColorHex: "#FFC30B", luckyDirection: "中央", luckyActivity: "為他人烹飪", shareText: "照顧模式啟動 — 用愛滋養 🏔️🥘" },
      { message: "你的耐力令人欽佩。你克服了別人無法克服的。", advice: "給自己因走到這裡的肯定。", luckyColor: "咖啡色", luckyColorHex: "#6F4E37", luckyDirection: "中央", luckyActivity: "反思進展", shareText: "土之耐力 — 我克服了很多 🏔️💪" },
      { message: "今天建立社群讓你滿足。你現在播下的羈絆,多年後會結果。", advice: "邀請某人進行有意義的連結。", luckyColor: "巧克力棕", luckyColorHex: "#7B3F00", luckyDirection: "中央", luckyActivity: "建立社群", shareText: "今天播下社群 — 收穫長存 🏔️🤝" },
    ],
    mid: [
      { message: "穩定可預測的一天。沒什麼刺激,但可靠。", advice: "接受平凡 — 那是生活真正發生的地方。", luckyColor: "米色", luckyColorHex: "#F5F5DC", luckyDirection: "中央", luckyActivity: "日常例行", shareText: "平凡的一天 — 而這很美好 ⛰️☕" },
      { message: "適合維護的好日子。修理、清潔、整理。", advice: "修一個你一直擱置的東西。", luckyColor: "淺褐色", luckyColorHex: "#E5AA70", luckyDirection: "中央", luckyActivity: "家居修繕", shareText: "維護模式 — 照顧我的系統 🔧🏔️" },
      { message: "食慾今天可能高漲。有意識地吃。", advice: "慢慢咀嚼,享受每一口。", luckyColor: "麥色", luckyColorHex: "#F5DEB3", luckyDirection: "中央", luckyActivity: "正念飲食", shareText: "有意識地吃 — 尊重身體 🍚⛰️" },
      { message: "慢不是懶。你穩定的節奏今天是對的。", advice: "忽略別人的匆忙。", luckyColor: "灰褐色", luckyColorHex: "#483C32", luckyDirection: "中央", luckyActivity: "自己的節奏", shareText: "我的步伐,我的路 — 不趕 🏔️🐢" },
      { message: "與自然連結有恢復效果。尋找腳下的土地。", advice: "可以的話赤腳踩在草地或泥土上。", luckyColor: "橄欖綠", luckyColorHex: "#6B8E23", luckyDirection: "中央", luckyActivity: "接觸大地", shareText: "今天接地氣 — 腳在地,心平靜 🌱🏔️" },
      { message: "榮耀傳統的日子。古老之物藏有智慧。", advice: "打給長者或讀本經典。", luckyColor: "棕褐色", luckyColorHex: "#704214", luckyDirection: "中央", luckyActivity: "連結根源", shareText: "榮耀根源 — 古老智慧長存 🏔️📜" },
      { message: "長期計畫推進一點點。慶祝微小的進展。", advice: "記下一件小小的進步。", luckyColor: "大地色", luckyColorHex: "#A67B5B", luckyDirection: "中央", luckyActivity: "記錄進展", shareText: "今天一小步 — 回頭看是大進步 🏔️📝" },
      { message: "好能量用於烘焙、慢煮、或發酵。耐心有回報。", advice: "今天煮需要時間的東西。", luckyColor: "麵糰色", luckyColorHex: "#F5DEB3", luckyDirection: "中央", luckyActivity: "慢煮", shareText: "今天慢慢煮 — 時間是一種食材 🍞🏔️" },
      { message: "你對安全的需求是合理的。別為選擇穩定道歉。", advice: "今天無愧地選擇安全選項。", luckyColor: "泥色", luckyColorHex: "#8B7355", luckyDirection: "中央", luckyActivity: "保守選擇", shareText: "穩定不無聊 — 是策略 🏔️🛡️" },
      { message: "今天細節工作順利。小細節值得你的注意。", advice: "完成那個你一直迴避的繁瑣工作。", luckyColor: "灰褐色", luckyColorHex: "#7F6B5B", luckyDirection: "中央", luckyActivity: "細節工作", shareText: "細節重要 — 今天搞定繁瑣 🔍🏔️" },
    ],
    low: [
      { message: "今天沉重感壓倒你。你的身體需要真正的休息。", advice: "無愧地小睡或早睡。", luckyColor: "炭黑", luckyColorHex: "#36454F", luckyDirection: "中央", luckyActivity: "深度休息", shareText: "緩慢沉重的一天 — 今天身體發號施令 🏔️💤" },
      { message: "停滯是真的。換環境比強迫自己更有用。", advice: "出門,哪怕只30分鐘。", luckyColor: "石灰灰", luckyColorHex: "#8E8E93", luckyDirection: "中央", luckyActivity: "戶外散步", shareText: "打破停滯 — 移動 > 強迫 🏔️🚶" },
      { message: "擔憂高漲。你的心原地轉圈,解決不了什麼。", advice: "寫下擔憂,然後合上本子。", luckyColor: "煙灰色", luckyColorHex: "#9A7B6C", luckyDirection: "中央", luckyActivity: "文字傾訴", shareText: "把擔憂放到紙上 — 從心到物 📓🏔️" },
      { message: "消化可能困難。簡單熱食最好。", advice: "蔬菜湯、白米飯、熱茶。", luckyColor: "金湯色", luckyColorHex: "#FFD580", luckyDirection: "中央", luckyActivity: "撫慰食物", shareText: "熱湯暖胃 — 今天簡單就是好 🍲🏔️" },
      { message: "不動可能感覺像失敗。不是 — 是在恢復。", advice: "允許自己今天什麼生產力都不做。", luckyColor: "深棕", luckyColorHex: "#8B4513", luckyDirection: "中央", luckyActivity: "無愧地休息", shareText: "靜止不是投降 — 是恢復 🏔️🌾" },
      { message: "家庭爭執可能發生。今天避開敏感話題。", advice: "換話題或暫時退一步。", luckyColor: "暗棕", luckyColorHex: "#A39161", luckyDirection: "中央", luckyActivity: "中性對話", shareText: "和平 > 道理 — 選擇和諧 🏔️☮️" },
      { message: "情感累積沉重。需要的話哭、寫或說。", advice: "向日記或信任的朋友傾訴情緒。", luckyColor: "泥漿色", luckyColorHex: "#70543E", luckyDirection: "中央", luckyActivity: "情感釋放", shareText: "釋放重擔 — 情感需要出口 🏔️💧" },
      { message: "固執可能增加。辨識何時讓步才是智慧。", advice: "今天練習說一次「你是對的」。", luckyColor: "鐵鏽色", luckyColorHex: "#B7410E", luckyDirection: "中央", luckyActivity: "有意識的彈性", shareText: "今天讓步 — 土之力包含柔韌 🏔️🙏" },
      { message: "憂鬱可能出現。是暫時的 — 感受它別抗拒。", advice: "需要就哭,然後吃點撫慰食物。", luckyColor: "灰白", luckyColorHex: "#848482", luckyDirection: "中央", luckyActivity: "感受不抗拒", shareText: "允許悲傷 — 土地也會下雨 🌧️🏔️" },
      { message: "完美主義今天讓你癱瘓。完成比完美好。", advice: "交出70% — 沒人注意剩下那30%。", luckyColor: "棕灰色", luckyColorHex: "#6F6351", luckyDirection: "中央", luckyActivity: "不完美地完成", shareText: "70%完成 > 100%永遠沒完成 — 進展勝於完美 🏔️✅" },
    ],
  },
  metal: {
    high: [
      { message: "你今天的心智清晰度達到最大。此刻做的決定,日後會被記為明智。", advice: "做那個你一直在分析的重要決定。", luckyColor: "銀色", luckyColorHex: "#C0C0C0", luckyDirection: "西方", luckyActivity: "做決策", shareText: "今天金之心智銳利 ⚔️ 清晰度最高" },
      { message: "你的正直是你的力量。人們注意到你的一致性。", advice: "今天堅守價值觀,不妥協。", luckyColor: "鉻色", luckyColorHex: "#DBE4EB", luckyDirection: "西方", luckyActivity: "維護原則", shareText: "金之正直穩固 — 我的原則不妥協 ⚔️💎" },
      { message: "你的精準令人印象深刻。別人忽略的細節你都抓到。", advice: "再審視那份重要文件一次。", luckyColor: "鋼色", luckyColorHex: "#71797E", luckyDirection: "西方", luckyActivity: "仔細審查", shareText: "今天鷹眼 — 細節是我的超能力 🦅⚔️" },
      { message: "你的正義感敏銳。為沒有聲音的人發聲。", advice: "為需要支持的人發言。", luckyColor: "白金色", luckyColorHex: "#E5E4E2", luckyDirection: "西方", luckyActivity: "為他人倡議", shareText: "金之正義行動 — 提升他人聲音 🗣️⚔️" },
      { message: "紀律今天結出果實。你冷靜開始的,現在閃耀。", advice: "繼續你一直在遵循的例行。", luckyColor: "金屬灰", luckyColorHex: "#A8A8A8", luckyDirection: "西方", luckyActivity: "持續紀律", shareText: "紀律見成果 — 金之路線有效 ⚔️📈" },
      { message: "你的誠實解放。今天說的一個真相化解多年的緊張。", advice: "溫柔但不畏懼地說那個真相。", luckyColor: "鎳色", luckyColorHex: "#727472", luckyDirection: "西方", luckyActivity: "誠實對話", shareText: "今天金之真相 — 誠實解放 ⚔️🔓" },
      { message: "當你清楚溝通,你的界限被尊重。人們比你想的更能理解。", advice: "設立一個你一直拖延的界限。", luckyColor: "深灰", luckyColorHex: "#4A4A4A", luckyDirection: "西方", luckyActivity: "溝通界限", shareText: "清楚劃界 — 收到和平 ⚔️🛡️" },
      { message: "你的美感敏銳。今天的選擇會多年保持好品味。", advice: "選最簡單、最永恆的選項。", luckyColor: "未漂白白", luckyColorHex: "#F5F5F0", luckyDirection: "西方", luckyActivity: "美學決策", shareText: "金之優雅 — 今天少即是多 ⚔️✨" },
      { message: "邏輯與直覺對齊。你的分析既冷靜又睿智。", advice: "相信那個你用頭腦也用心得出的結論。", luckyColor: "石墨色", luckyColorHex: "#383838", luckyDirection: "西方", luckyActivity: "深度分析", shareText: "今天心智同步 — 金之完整 ⚔️🧠💓" },
      { message: "你的精緻令人欽佩。優雅的簡潔吸引機會。", advice: "整理你的空間 — 今天少即是多。", luckyColor: "珍珠白", luckyColorHex: "#EAE0C8", luckyDirection: "西方", luckyActivity: "極簡主義", shareText: "今天優雅的簡潔獲勝 ⚔️🤍" },
    ],
    mid: [
      { message: "適合精煉而非建造的一天。打磨已存在的東西。", advice: "改進現有系統,而非建新的。", luckyColor: "錫色", luckyColorHex: "#D3D3D3", luckyDirection: "西方", luckyActivity: "系統精煉", shareText: "打磨我擁有的 — 金精煉,不取代 ⚔️🔧" },
      { message: "書面溝通流暢。電郵和訊息寫得精準。", advice: "起草那個你一直延遲的重要電郵。", luckyColor: "鴿灰", luckyColorHex: "#A9A9A9", luckyDirection: "西方", luckyActivity: "專業寫作", shareText: "今天精準的字 — 金清楚溝通 ⚔️✍️" },
      { message: "建設性批評今天有用。不防衛地聽。", advice: "接受一個最初讓你惱火的建議。", luckyColor: "淺炭", luckyColorHex: "#525252", luckyDirection: "西方", luckyActivity: "接受反饋", shareText: "聽批評來成長 — 金不被冒犯 ⚔️📊" },
      { message: "你的知識分子面閃耀。閱讀、學習、分析。", advice: "深入你感興趣的主題。", luckyColor: "珍珠灰", luckyColorHex: "#C8C8C8", luckyDirection: "西方", luckyActivity: "深度學習", shareText: "認真學生模式 — 金愛學習 📚⚔️" },
      { message: "今天言辭的節儉即力量。少說,但有份量。", advice: "練習有意圖的沉默。", luckyColor: "雲灰", luckyColorHex: "#B8B8B8", luckyDirection: "西方", luckyActivity: "簡潔溝通", shareText: "今天少言多量 ⚔️🤫" },
      { message: "適合財務審計或審查。數字告訴真實故事。", advice: "檢視本月支出。", luckyColor: "板岩灰", luckyColorHex: "#708090", luckyDirection: "西方", luckyActivity: "財務分析", shareText: "今天數字不說謊 📊⚔️" },
      { message: "你的肺要求乾淨空氣。遠離擁擠環境。", advice: "做深呼吸練習。", luckyColor: "雪白", luckyColorHex: "#FFFAFA", luckyDirection: "西方", luckyActivity: "呼吸與新鮮空氣", shareText: "今天為金元素供給乾淨空氣 🌬️⚔️" },
      { message: "放下舊物品有解脫感。捐出不用的騰出空間。", advice: "丟棄5樣6個月沒用的東西。", luckyColor: "象牙白", luckyColorHex: "#FFFFF0", luckyDirection: "西方", luckyActivity: "斷捨離", shareText: "放下以創造空間 — 金解放 ⚔️🎁" },
      { message: "履行承諾的日子。你的話建立或摧毀聲譽。", advice: "履行你做過的那個小承諾。", luckyColor: "白蠟色", luckyColorHex: "#8A8A8A", luckyDirection: "西方", luckyActivity: "履行約定", shareText: "我的話有價值 — 今天履行 ⚔️🤝" },
      { message: "獨處今天很有生產力。你最棒的洞察在沉默中誕生。", advice: "獨自不受打擾工作2小時。", luckyColor: "煙白", luckyColorHex: "#F5F5F5", luckyDirection: "西方", luckyActivity: "專注工作", shareText: "今天獨處的生產力 — 金在寂靜中綻放 ⚔️🤫" },
    ],
    low: [
      { message: "你的金氣感覺鈍化。悲傷可能無來由地浮現。", advice: "讓憂鬱不抵抗地通過。", luckyColor: "鉛灰", luckyColorHex: "#667580", luckyDirection: "西方", luckyActivity: "感受不分析", shareText: "憂鬱之日 — 金認識悲傷 🌫️⚔️" },
      { message: "完美主義今天癱瘓你。接受「夠好」即勝利。", advice: "不完美地交付某樣東西。", luckyColor: "柔灰", luckyColorHex: "#D0D0D0", luckyDirection: "西方", luckyActivity: "不完美交付", shareText: "夠就是夠 — 今天放下完美主義 ⚔️🙏" },
      { message: "批評今天影響你超過往常。限制曝光。", advice: "靜音讓你感到不足的訊息流。", luckyColor: "暗灰", luckyColorHex: "#484848", luckyDirection: "西方", luckyActivity: "數位排毒", shareText: "今天保護我的能量 — 少些噪音 🔇⚔️" },
      { message: "你的免疫系統可能下降。溫暖、休息、水分。", advice: "熱茶、圍巾、早睡。", luckyColor: "淺煙灰", luckyColorHex: "#E0E0E0", luckyDirection: "西方", luckyActivity: "預防性照護", shareText: "今天預防性照護 — 金保護它的肺 ⚔️🧣" },
      { message: "心智僵硬感覺沉重。允許自己不批判地改變主意。", advice: "不道歉地說「我改變主意了」。", luckyColor: "石灰灰", luckyColorHex: "#BEBEBE", luckyDirection: "西方", luckyActivity: "認知靈活", shareText: "今天改變主意 — 金也會彎曲 ⚔️🌀" },
      { message: "舊傷記憶可能回來。承認它們並放下。", advice: "寫下過去某事,象徵性地燒掉。", luckyColor: "灰燼色", luckyColorHex: "#A9A9A9", luckyDirection: "西方", luckyActivity: "釋放儀式", shareText: "今天釋放過去 — 金處理並放下 ⚔️🍂" },
      { message: "孤獨感沉重。尋求連結,哪怕一條短訊。", advice: "發「想你」給朋友。", luckyColor: "天空灰", luckyColorHex: "#B0C4DE", luckyDirection: "西方", luckyActivity: "輕度聯絡", shareText: "今天伸出手 — 連結勝過孤立 ⚔️💌" },
      { message: "憤世嫉俗想獲勝。提醒自己希望也是邏輯的決定。", advice: "列出今天三個有希望的理由。", luckyColor: "消光白", luckyColorHex: "#F2F2F2", luckyDirection: "西方", luckyActivity: "希望練習", shareText: "邏輯的希望 > 輕鬆的憤世 — 今天選擇光 ⚔️🕯️" },
      { message: "你的聲音可能沙啞或微弱。今天少說多寫。", advice: "讓聲帶休息 — 用文字。", luckyColor: "珍珠白", luckyColorHex: "#F0EAD6", luckyDirection: "西方", luckyActivity: "書面溝通", shareText: "今天讓聲音休息 — 文字替我發言 ✍️⚔️" },
      { message: "情感脫離很誘人。別把距離誤認為智慧。", advice: "今天感受某事,即使不舒服。", luckyColor: "冰灰", luckyColorHex: "#D3D3E7", luckyDirection: "西方", luckyActivity: "情感開放", shareText: "今天去感受 — 金不代表冷 💧⚔️" },
    ],
  },
  water: {
    high: [
      { message: "你的直覺今天深邃。聽那個內在的聲音 — 它知道的比你的頭腦多。", advice: "相信第一直覺,不要質疑。", luckyColor: "深藍", luckyColorHex: "#00008B", luckyDirection: "北方", luckyActivity: "冥想或長時間泡澡", shareText: "今天水之直覺最高 🌊 內在的聲音知道" },
      { message: "你的智慧被尋求。人們尋求你的建議因為他們清楚地看見。", advice: "被問時分享你的觀點。", luckyColor: "靛藍", luckyColorHex: "#4B0082", luckyDirection: "北方", luckyActivity: "給予建議", shareText: "水之智慧流動 — 今天人們聆聽 🌊🧠" },
      { message: "你的適應力是力量。即將到來的改變對你有利。", advice: "接受改變,不要抗拒。", luckyColor: "海軍藍", luckyColorHex: "#000080", luckyDirection: "北方", luckyActivity: "隨改變流動", shareText: "像水一樣適應 — 改變是我的盟友 🌊🌀" },
      { message: "你的情感深度吸引對的人。膚淺者遠離 — 讓它發生。", advice: "別為感受強烈道歉。", luckyColor: "天藍", luckyColorHex: "#2A52BE", luckyDirection: "北方", luckyActivity: "深度連結", shareText: "深邃即強大 — 膚淺者不共鳴 🌊💙" },
      { message: "你的夢今天是訊息。醒來時記下你記得的。", advice: "床邊放本筆記本。", luckyColor: "夜藍", luckyColorHex: "#191970", luckyDirection: "北方", luckyActivity: "夢境日記", shareText: "今天夢說水語 — 夜晚聆聽 🌙🌊" },
      { message: "你情感的藝術令人印象深刻。發自心底的創意無法被複製。", advice: "今天創造脆弱的東西。", luckyColor: "藍寶石", luckyColorHex: "#0F52BA", luckyDirection: "北方", luckyActivity: "情感藝術", shareText: "從深處而來的藝術 — 無人能及 🌊🎨" },
      { message: "靈性對話召喚你。有人想與你深入。", advice: "談意義,不談議程。", luckyColor: "深綠松石", luckyColorHex: "#116062", luckyDirection: "北方", luckyActivity: "深入對話", shareText: "今天深入 — 表面無聊 🌊💬" },
      { message: "你的耐心侵蝕障礙。看似牆的一滴一滴讓步。", advice: "堅持那個頑固的問題 — 你比想的更接近。", luckyColor: "藍灰", luckyColorHex: "#6699CC", luckyDirection: "北方", luckyActivity: "溫和堅持", shareText: "今天一滴一滴贏得戰役 💧🌊" },
      { message: "情感療癒在進展。曾經痛的感覺更遙遠了。", advice: "感謝你的進展,不要貶低。", luckyColor: "水藍", luckyColorHex: "#00BFFF", luckyDirection: "北方", luckyActivity: "認可療癒", shareText: "層層療癒 — 水需要時間 🌊🩹" },
      { message: "你的神秘吸引人。你不需要解釋一切。", advice: "今天留一些東西不回答。", luckyColor: "墨藍", luckyColorHex: "#1F2F5C", luckyDirection: "北方", luckyActivity: "保持隱私", shareText: "水之神秘 — 不是所有都需解釋 🌊🔮" },
    ],
    mid: [
      { message: "你的情感流動平衡。既不過多,也不過少。", advice: "感受而不淹沒在情緒中。", luckyColor: "天藍", luckyColorHex: "#87CEEB", luckyDirection: "北方", luckyActivity: "平衡的自我覺察", shareText: "今天情感平衡 — 感受而不淹沒 🌊⚖️" },
      { message: "適合誠實而不戲劇化對話的好日子。溫柔是強大的。", advice: "溫柔地說,但說真話。", luckyColor: "粉塵藍", luckyColorHex: "#7B9EAE", luckyDirection: "北方", luckyActivity: "平靜對話", shareText: "溫柔的聲音,強烈的真相 — 水的風格 🌊💬" },
      { message: "你的記憶敏銳。一個有用的記憶在對的時機浮現。", advice: "相信你記得的。", luckyColor: "石墨藍", luckyColorHex: "#4A708B", luckyDirection: "北方", luckyActivity: "反思過去", shareText: "今天水之記憶流動 — 過去告訴我們 🌊📖" },
      { message: "聆聽多於行動的日子。答案會隨時間到來。", advice: "問問題,不要斷言。", luckyColor: "藍綠色", luckyColorHex: "#008080", luckyDirection: "北方", luckyActivity: "積極聆聽", shareText: "今天聆聽 — 問題 > 答案 🌊👂" },
      { message: "你的水分攝取今天格外重要。有意識地喝水。", advice: "今天2公升水,沒藉口。", luckyColor: "海水藍", luckyColorHex: "#7FFFD4", luckyDirection: "北方", luckyActivity: "有意識的補水", shareText: "水給水元素 — 身體開心 💧🌊" },
      { message: "水邊工作或靠近水都有恢復效果。洗澡、游泳、河流。", advice: "泡個長澡或在水邊散步。", luckyColor: "潟湖藍", luckyColorHex: "#4B8F8C", luckyDirection: "北方", luckyActivity: "與水接觸", shareText: "今天水之充電 — 我的元素讓我恢復 🌊🛁" },
      { message: "你的敏感今天是力量,不是弱點。榮耀你所注意到的。", advice: "別壓抑感受 — 把它當資訊用。", luckyColor: "鋼藍", luckyColorHex: "#4682B4", luckyDirection: "北方", luckyActivity: "榮耀敏感", shareText: "我的敏感是我的超能力 🌊💎" },
      { message: "音樂今天說話。一首歌會把你帶到一個真相。", advice: "聽一首引發情感的歌。", luckyColor: "浪花藍", luckyColorHex: "#ADD8E6", luckyDirection: "北方", luckyActivity: "深度音樂聆聽", shareText: "音樂今天說我的水語 🎵🌊" },
      { message: "你的腎臟要求照顧。今天避免太鹹食物。", advice: "減鹽,增加溫水。", luckyColor: "淺海軍藍", luckyColorHex: "#5F9EA0", luckyDirection: "北方", luckyActivity: "清淡飲食", shareText: "照顧我的腎 — 水榮耀自己 🌊🍃" },
      { message: "適合深度休息的好日子。床比行程更有價值。", advice: "今晚多睡30分鐘。", luckyColor: "午夜藍", luckyColorHex: "#191970", luckyDirection: "北方", luckyActivity: "多睡", shareText: "今天水之深眠 — 必要的充電 🌙🌊" },
    ],
    low: [
      { message: "你的水氣感覺凍結。情感流動感覺受阻。", advice: "可以的話哭,或看部悲傷的電影。", luckyColor: "冰藍", luckyColorHex: "#D4E6F1", luckyDirection: "北方", luckyActivity: "情感解凍", shareText: "今天解凍 — 水需要流動 🌊❄️" },
      { message: "非理性恐懼可能浮現。承認它但別全盤相信。", advice: "問自己「這是真的還是恐懼?」", luckyColor: "灰藍", luckyColorHex: "#6F8695", luckyDirection: "北方", luckyActivity: "區分恐懼與事實", shareText: "今天質疑恐懼 — 不是所有害怕都說真相 🌊🛡️" },
      { message: "心智疲勞深。今天完成一個任務就夠了。", advice: "選一件小事,做完,休息。", luckyColor: "褪色藍", luckyColorHex: "#8FA3AD", luckyDirection: "北方", luckyActivity: "高效的極簡", shareText: "今天做完一件 > 開始五件 🌊✅" },
      { message: "孤獨感沉重。即使短暫的連結也有幫助。", advice: "給親密朋友一個語音訊息。", luckyColor: "冷藍", luckyColorHex: "#4F7B8B", luckyDirection: "北方", luckyActivity: "輕度聯絡", shareText: "今天打破孤獨 — 一則訊息就夠 🌊💌" },
      { message: "你的神經系統敏感。大噪音和混亂今天耗盡。", advice: "主動尋找寧靜 — 需要就戴耳機。", luckyColor: "深藍", luckyColorHex: "#3B4E5D", luckyDirection: "北方", luckyActivity: "感官保護", shareText: "今天寂靜是藥 — 水需要寧靜 🌊🎧" },
      { message: "反芻過去耗盡。昨天今天無法改變。", advice: "念頭浮現時重新導向當下。", luckyColor: "煙藍", luckyColorHex: "#7F8C9A", luckyDirection: "北方", luckyActivity: "當下錨定", shareText: "今天過去留在後面 — 當下錨定我 🌊⚓" },
      { message: "對未來的恐懼高漲。不確定不是敵人 — 是空間。", advice: "呼吸並記得你不需要知道一切。", luckyColor: "霧藍", luckyColorHex: "#AAB6BD", luckyDirection: "北方", luckyActivity: "容忍不確定", shareText: "不知道沒關係 — 今天擁抱神秘 🌊🌫️" },
      { message: "你的性慾可能低。柔軟的親密就夠了。", advice: "擁抱、牽手 — 少點壓力。", luckyColor: "薰衣草藍", luckyColorHex: "#9BB5D6", luckyDirection: "北方", luckyActivity: "柔軟親密", shareText: "溫柔 > 熱情 — 水今天溫和 💙🌊" },
      { message: "情感低落可能浮現。需要就求助 — 那是智慧。", advice: "感覺低落時打給信任的人。", luckyColor: "淺藍", luckyColorHex: "#ADD8E6", luckyDirection: "北方", luckyActivity: "尋求支持", shareText: "今天求助 — 力量,不是軟弱 🌊🤝" },
      { message: "自我批評加劇。像對摯友一樣對自己說話。", advice: "大聲對自己說一句溫柔的話。", luckyColor: "珍珠藍", luckyColorHex: "#BFD6DE", luckyDirection: "北方", luckyActivity: "自我慈悲", shareText: "今天做自己的朋友 — 水溫柔對我 💙🌊" },
    ],
  },
};
