// Japanese Daily Fortune Messages (日本語版)
import type { DailyFortune } from "./daily-fortune";
type Tier = "high" | "mid" | "low";

export const FORTUNES_JA: Record<string, Record<Tier, DailyFortune[]>> = {
  wood: { high: [
    { message: "木の気が満開の日。午前中のアイデアが最も力を持ちます。", advice: "新しいプロジェクトを始めましょう。", luckyColor: "緑", luckyColorHex: "#59DE9B", luckyDirection: "東", luckyActivity: "木々の中の散歩", shareText: "今日の木の気は最高潮 🌿" },
    { message: "成長のチャンスに満ちています。今日の会話が思わぬ扉を開くかも。", advice: "突然の誘いには「はい」と。", luckyColor: "ティール", luckyColorHex: "#2DD4BF", luckyDirection: "南東", luckyActivity: "朝の日記", shareText: "成長の気に満ちた一日 🌱" },
    { message: "生まれ持ったリーダーシップが輝く日。", advice: "グループの場で積極的に発言を。", luckyColor: "翡翠", luckyColorHex: "#00A86B", luckyDirection: "東", luckyActivity: "チーム活動", shareText: "甲木エネルギー全開 甲" },
    { message: "蒔いた種が芽を出し始めます。", advice: "待っていた件のフォローアップを。", luckyColor: "エメラルド", luckyColorHex: "#50C878", luckyDirection: "北東", luckyActivity: "ガーデニング", shareText: "努力の成果が見え始める 🌿" },
    { message: "柔軟さが今日の超能力。しなやかに道を見つけます。", advice: "計画を柔軟に調整しましょう。", luckyColor: "ライム", luckyColorHex: "#84CC16", luckyDirection: "東", luckyActivity: "ヨガ", shareText: "木はしなっても折れない 💚" },
    { message: "午後に創作インスピレーションが降りてきます。", advice: "メモ帳を手元に。", luckyColor: "深緑", luckyColorHex: "#228B22", luckyDirection: "南東", luckyActivity: "創作活動", shareText: "午後のインスピレーション爆発 🎋" },
    { message: "あなたの思いやりが導きを必要とする人を引き寄せます。", advice: "話すより聴くことに集中。", luckyColor: "セージ", luckyColorHex: "#9CAF88", luckyDirection: "東", luckyActivity: "メンタリング", shareText: "木の気が他者を癒す 🌳" },
    { message: "拡大のエネルギーが強い日。今日始めることは成長力抜群。", advice: "発表し、始めましょう。", luckyColor: "スプリンググリーン", luckyColorHex: "#00FF7F", luckyDirection: "東", luckyActivity: "新しいこと", shareText: "新たな始まりのエネルギー ☘️" },
    { message: "道徳的な羅針盤が正確に作動する日。", advice: "先延ばしの決断を下しましょう。", luckyColor: "オリーブ", luckyColorHex: "#808000", luckyDirection: "北東", luckyActivity: "空間整理", shareText: "直感を信じろ ✅" },
    { message: "アイデア同士の繋がりが自然にできる日。", advice: "洞察を共有しましょう。", luckyColor: "ミント", luckyColorHex: "#98FF98", luckyDirection: "南東", luckyActivity: "ブレスト", shareText: "パターン認識：起動 🧠🌿" },
  ], mid: [
    { message: "着実な成長の日。根は深く伸びています。", advice: "一貫性に集中。", luckyColor: "シダグリーン", luckyColorHex: "#4F7942", luckyDirection: "東", luckyActivity: "ルーティン", shareText: "静かな成長の日 🌿" },
    { message: "既存の関係を育むのに良い日。", advice: "連絡していない人に声を。", luckyColor: "モス", luckyColorHex: "#8A9A5B", luckyDirection: "南東", luckyActivity: "旧友との再会", shareText: "育むモード：ON 💚" },
    { message: "忍耐が試されますが報われます。", advice: "焦る衝動を抑えて。", luckyColor: "グリーン", luckyColorHex: "#59DE9B", luckyDirection: "東", luckyActivity: "読書", shareText: "忍耐が超能力 🎋" },
    { message: "適度な創作エネルギー。既存のものを磨くのに良い。", advice: "始めたものを編集、改善。", luckyColor: "ピスタチオ", luckyColorHex: "#93C572", luckyDirection: "北東", luckyActivity: "編集と修正", shareText: "磨きの日 🌱" },
    { message: "与えることと受け取ることのバランスが重要。", advice: "助けが来たら受け入れて。", luckyColor: "セージ", luckyColorHex: "#9CAF88", luckyDirection: "東", luckyActivity: "セルフケア", shareText: "受け取ることを学ぶ ⚖️🌿" },
    { message: "財務的に安定した日。貯蓄に良い。", advice: "予算を見直しましょう。", luckyColor: "ハンターグリーン", luckyColorHex: "#355E3B", luckyDirection: "南東", luckyActivity: "財務計画", shareText: "安定した財務エネルギー 💰" },
    { message: "体が動きを求めています。", advice: "緑の近くで20分歩きましょう。", luckyColor: "ライム", luckyColorHex: "#84CC16", luckyDirection: "東", luckyActivity: "屋外運動", shareText: "体が「動け！」と 🏃🌿" },
    { message: "学ぶには良いが教えるには微妙な日。", advice: "読んで、聴いて、学んで。", luckyColor: "ティール", luckyColorHex: "#2DD4BF", luckyDirection: "北東", luckyActivity: "学習", shareText: "学びモード 📚" },
    { message: "関係に正直さが役立つ日。", advice: "避けていた会話をしましょう。", luckyColor: "ミント", luckyColorHex: "#98FF98", luckyDirection: "東", luckyActivity: "率直な会話", shareText: "真実を語る日 🌿💬" },
    { message: "環境がいつも以上に大切。きれいな空間＝クリアな心。", advice: "15分間整理しましょう。", luckyColor: "エメラルド", luckyColorHex: "#50C878", luckyDirection: "南東", luckyActivity: "整理整頓", shareText: "きれいな空間、クリアな心 🧹" },
  ], low: [
    { message: "木の気が圧縮された日。休んでいるだけ。", advice: "罪悪感なく休みましょう。", luckyColor: "ダークグリーン", luckyColorHex: "#006400", luckyDirection: "東", luckyActivity: "昼寝や瞑想", shareText: "休む日 🌳💤" },
    { message: "創造力は詰まっていますが明晰さは上昇。", advice: "整理、分類、計画を。", luckyColor: "オリーブ", luckyColorHex: "#808000", luckyDirection: "北東", luckyActivity: "計画と分析", shareText: "分析モードON 🌿" },
    { message: "金の気が制約する日。制限の中に構造を。", advice: "制約の中で働きましょう。", luckyColor: "フォレスト", luckyColorHex: "#228B22", luckyDirection: "東", luckyActivity: "制限内で作業", shareText: "制約が創造力を生む 🎋" },
    { message: "エネルギーが低くても価値は低くない。", advice: "一人で考える時間を。", luckyColor: "セージ", luckyColorHex: "#9CAF88", luckyDirection: "南東", luckyActivity: "一人の思索", shareText: "静かな瞬間に知恵 🌱🤫" },
    { message: "肝臓と目にケアが必要。", advice: "緑の野菜を食べて目を休めて。", luckyColor: "グリーン", luckyColorHex: "#59DE9B", luckyDirection: "東", luckyActivity: "デジタルデトックス", shareText: "セルフケア優先 💚" },
    { message: "社交的エネルギーが低い日。", advice: "エネルギーを奪う約束は断って。", luckyColor: "モス", luckyColorHex: "#8A9A5B", luckyDirection: "東", luckyActivity: "孤独と静寂", shareText: "境界線はセルフラブ 🌿🛡️" },
    { message: "財務的な注意が必要。", advice: "買い物は別の日に。", luckyColor: "ダークモス", luckyColorHex: "#4A5D23", luckyDirection: "北東", luckyActivity: "予算管理", shareText: "お財布は今日閉じて 💰🌿" },
    { message: "過去の後悔が浮かぶかも。認めて手放して。", advice: "気になることを書いてノートを閉じて。", luckyColor: "シダ", luckyColorHex: "#4F7942", luckyDirection: "東", luckyActivity: "日記", shareText: "手放す日 🍃" },
    { message: "柔軟さが硬く感じます。時には静けさが答え。", advice: "寝る前に軽いストレッチを。", luckyColor: "パイン", luckyColorHex: "#01796F", luckyDirection: "南東", luckyActivity: "軽いストレッチ", shareText: "静けさが強さ 🌲" },
    { message: "他人に誤解されるかも。時間が解決します。", advice: "誤解は自然に解けるように。", luckyColor: "バジル", luckyColorHex: "#487800", luckyDirection: "東", luckyActivity: "忍耐", shareText: "すべてを説明する必要はない 🌿" },
  ]},
  fire: { high: [
    { message: "カリスマが磁石のように働く日。", advice: "影響力を意味のあることに。", luckyColor: "赤", luckyColorHex: "#EF4444", luckyDirection: "南", luckyActivity: "プレゼン", shareText: "火の気が全開 🔥" },
    { message: "情熱と明晰さが完璧に一致。", advice: "迷わず目標に向かって。", luckyColor: "クリムゾン", luckyColorHex: "#DC143C", luckyDirection: "南", luckyActivity: "大胆な行動", shareText: "心と頭が一つ 🔥❤️" },
    { message: "熱意が周りに火をつけます。", advice: "インスピレーションで導いて。", luckyColor: "オレンジレッド", luckyColorHex: "#FF4500", luckyDirection: "南西", luckyActivity: "グループ活動", shareText: "部屋に火をつける 🔥✨" },
    { message: "認められるエネルギーが強い。", advice: "成果を控えめにしないで。", luckyColor: "コーラル", luckyColorHex: "#FF7F50", luckyDirection: "南", luckyActivity: "成果アピール", shareText: "認められる運命 🌟🔥" },
    { message: "ロマンティックエネルギーが最高潮。", advice: "気持ちを直接伝えて。", luckyColor: "ローズレッド", luckyColorHex: "#C21E56", luckyDirection: "南", luckyActivity: "デートや告白", shareText: "火＋ロマンス＝今日 🔥💕" },
    { message: "直感が混乱を突き抜けます。", advice: "最初の直感で決断を。", luckyColor: "スカーレット", luckyColorHex: "#FF2400", luckyDirection: "南東", luckyActivity: "決断力", shareText: "直感が燃えている 🔥⚡" },
    { message: "競争エネルギーが味方する日。", advice: "全力で挑戦を。", luckyColor: "フレイム", luckyColorHex: "#E25822", luckyDirection: "南", luckyActivity: "競争やスポーツ", shareText: "勝負の日 🏆🔥" },
    { message: "喜びが溢れる日。分かち合いましょう。", advice: "誰かを笑わせて。", luckyColor: "タンジェリン", luckyColorHex: "#FF9966", luckyDirection: "南西", luckyActivity: "人を笑顔に", shareText: "喜びマシン起動 🔥😊" },
    { message: "創作の炎がきれいに燃える日。", advice: "何でもいいから創って。", luckyColor: "ルビー", luckyColorHex: "#E0115F", luckyDirection: "南", luckyActivity: "芸術創作", shareText: "アートモード起動 🎨🔥" },
    { message: "変容のエネルギーが最高潮。", advice: "諦めたプロジェクトを見直して。", luckyColor: "フェニックスレッド", luckyColorHex: "#CD2029", luckyDirection: "南", luckyActivity: "復活", shareText: "不死鳥のエネルギー 🔥🦅" },
  ], mid: [
    { message: "温かく安定した火の日。維持に良い。", advice: "既存の約束を守って。", luckyColor: "ピーチ", luckyColorHex: "#FFCBA4", luckyDirection: "南", luckyActivity: "タスク完了", shareText: "安定した炎 🕯️" },
    { message: "心は開いていますがエネルギーは普通。", advice: "関係は量より質で。", luckyColor: "サーモン", luckyColorHex: "#FA8072", luckyDirection: "南西", luckyActivity: "一対一の時間", shareText: "炎を一点に集中 🔥" },
    { message: "実行より計画に良い日。", advice: "行動の前に戦略を。", luckyColor: "アンバー", luckyColorHex: "#FFBF00", luckyDirection: "南", luckyActivity: "戦略立案", shareText: "次の炎を計画中 🔥📋" },
    { message: "適度なインスピレーション。熟成が必要。", advice: "書き留めて一晩寝かせて。", luckyColor: "コーラル", luckyColorHex: "#FF7F50", luckyDirection: "南東", luckyActivity: "メモ", shareText: "閃きを集める 🌟" },
    { message: "社交エネルギーは心地よいが爆発的ではない。", advice: "ただ一緒にいましょう。", luckyColor: "ローズ", luckyColorHex: "#FF007F", luckyDirection: "南", luckyActivity: "社交", shareText: "穏やかな火 🕯️😌" },
    { message: "心が頭より先に何かを知っています。", advice: "感情と一緒に座って。", luckyColor: "ブリック", luckyColorHex: "#CB4154", luckyDirection: "南", luckyActivity: "感情整理", shareText: "心の知恵がロード中 🔥💭" },
    { message: "財務は中立。小さな投資は育つ。", advice: "少し貯金を。", luckyColor: "オレンジ", luckyColorHex: "#FF8C00", luckyDirection: "南西", luckyActivity: "少額貯金", shareText: "小さな炎、大きな未来 💰🔥" },
    { message: "動かないと火が循環しません。", advice: "15分の運動でも。", luckyColor: "レッドオレンジ", luckyColorHex: "#FF5349", luckyDirection: "南", luckyActivity: "有酸素", shareText: "動いて火を生かす 🏃🔥" },
    { message: "コミュニケーションがスムーズな日。", advice: "下書きのメッセージを送って。", luckyColor: "タンジェリン", luckyColorHex: "#FF9966", luckyDirection: "南", luckyActivity: "文章", shareText: "言葉が火のように流れる 📝🔥" },
    { message: "感謝する日。感謝が火を増幅。", advice: "感謝すること3つ挙げて。", luckyColor: "ウォームピンク", luckyColorHex: "#FF6B81", luckyDirection: "南東", luckyActivity: "感謝", shareText: "感謝する心＝強い火 🔥🙏" },
  ], low: [
    { message: "今日の火は残り火。最も深い温もり。", advice: "温かさの近くで休んで。", luckyColor: "バーガンディ", luckyColorHex: "#800020", luckyDirection: "南", luckyActivity: "セルフケア", shareText: "残り火の日 🕯️" },
    { message: "心のエネルギーが低い日。守って。", advice: "説明なしに境界線を。", luckyColor: "ダークレッド", luckyColorHex: "#8B0000", luckyDirection: "南西", luckyActivity: "境界線", shareText: "炎を守る日 🔥🛡️" },
    { message: "血行と心臓にケアが必要。", advice: "冷たい飲み物を避けて。", luckyColor: "マルーン", luckyColorHex: "#800000", luckyDirection: "南", luckyActivity: "温かい飲み物", shareText: "火の元素をケア 🫖❤️" },
    { message: "自信が一時的に下がる。火は必ず戻る。", advice: "低い日に自己評価しないで。", luckyColor: "ラスト", luckyColorHex: "#B7410E", luckyDirection: "南", luckyActivity: "自己批判回避", shareText: "弱い炎≠消えた炎 🔥" },
    { message: "口論を避けて。火が弱すぎる。", advice: "難しい会話は明日に。", luckyColor: "ブリック", luckyColorHex: "#CB4154", luckyDirection: "南東", luckyActivity: "衝突回避", shareText: "平和を選ぶ日 🕊️" },
    { message: "創造力は休んでいるだけ。", advice: "作るより鑑賞を。", luckyColor: "ディープローズ", luckyColorHex: "#C21E56", luckyDirection: "南", luckyActivity: "映画や読書", shareText: "創作休息の日 🎬📚" },
    { message: "孤独がささやくかもしれませんが嘘です。", advice: "「思い出したよ」と一言。", luckyColor: "ウォームブラウン", luckyColorHex: "#964B00", luckyDirection: "南西", luckyActivity: "連絡", shareText: "繋がりが癒す 💌" },
    { message: "決断がいつもより難しい。待てのサイン。", advice: "大きな決断は24時間延期。", luckyColor: "テラコッタ", luckyColorHex: "#E2725B", luckyDirection: "南", luckyActivity: "決断延期", shareText: "遅らせること＝知恵 🔥⏳" },
    { message: "体力が低い日。休息は燃料。", advice: "30分早く寝ましょう。", luckyColor: "ダークコーラル", luckyColorHex: "#CD5B45", luckyDirection: "南", luckyActivity: "早めの就寝", shareText: "休むことが仕事 🔥💤" },
    { message: "他者が自分の光を見つけるためにあなたの光が暗くなる。", advice: "他の人にリードを。", luckyColor: "アッシュローズ", luckyColorHex: "#B5651D", luckyDirection: "南東", luckyActivity: "静かに応援", shareText: "光を抑えて他者を輝かせる 🌅" },
  ]},
  earth: { high: [
    { message: "安定感が超能力の日。", advice: "必要な人のそばに。", luckyColor: "ゴールド", luckyColorHex: "#F2CA50", luckyDirection: "中央", luckyActivity: "支えになる", shareText: "山のエネルギー 🏔️✨" },
    { message: "実践的な知恵が最高潮。", advice: "シンプルな答えを信じて。", luckyColor: "アンバー", luckyColorHex: "#FFBF00", luckyDirection: "南西", luckyActivity: "問題解決", shareText: "土の知恵が起動 🌍" },
    { message: "財務エネルギーが素晴らしい。", advice: "財務的決断を実行。", luckyColor: "ハニー", luckyColorHex: "#EB9605", luckyDirection: "中央", luckyActivity: "財務決断", shareText: "土＝富のエネルギー 💰🌍" },
    { message: "育む本能が強力。世話するものが繁栄。", advice: "料理、庭、空間を整えて。", luckyColor: "オークル", luckyColorHex: "#CC7722", luckyDirection: "南西", luckyActivity: "料理やガーデニング", shareText: "触れるもの全てが育つ 🌻" },
    { message: "基盤を築くエネルギーが最高。", advice: "構造が必要なプロジェクトを。", luckyColor: "ブロンズ", luckyColorHex: "#CD7F32", luckyDirection: "中央", luckyActivity: "基盤づくり", shareText: "土台の日 🏗️🌍" },
    { message: "信頼性がチャンスを引き寄せる。", advice: "責任を受け入れて。", luckyColor: "シエナ", luckyColorHex: "#A0522D", luckyDirection: "北東", luckyActivity: "責任", shareText: "信頼＝チャンス 🌍🤝" },
    { message: "収穫のエネルギーが到着。", advice: "褒め言葉を謙遜しないで。", luckyColor: "ウィート", luckyColorHex: "#F5DEB3", luckyDirection: "中央", luckyActivity: "認められる", shareText: "収穫の時 🌾✨" },
    { message: "忍耐が配当を出します。", advice: "進んでいる道を維持。", luckyColor: "サンド", luckyColorHex: "#C2B280", luckyDirection: "南西", luckyActivity: "忍耐", shareText: "忍耐＝超能力 🏔️" },
    { message: "体力が最高潮。", advice: "高強度の運動に挑戦。", luckyColor: "テラコッタ", luckyColorHex: "#E2725B", luckyDirection: "中央", luckyActivity: "運動", shareText: "土の体が強い日 💪🌍" },
    { message: "環境の調和が心の調和を。", advice: "模様替えか美しさを加えて。", luckyColor: "クリーム", luckyColorHex: "#FFFDD0", luckyDirection: "中央", luckyActivity: "インテリア", shareText: "空間に美を 🏡✨" },
  ], mid: [
    { message: "安定して頼もしい一日。", advice: "着実な仕事に集中。", luckyColor: "タン", luckyColorHex: "#D2B48C", luckyDirection: "中央", luckyActivity: "集中作業", shareText: "静かに積み上げる 🌍" },
    { message: "胃腸に注意が必要。", advice: "温かく調理された食事を。", luckyColor: "イエロー", luckyColorHex: "#F2CA50", luckyDirection: "南西", luckyActivity: "マインドフル食事", shareText: "内側から栄養 🍲" },
    { message: "メンテナンスに良い日。", advice: "小さなことを一つ直して。", luckyColor: "カーキ", luckyColorHex: "#C3B091", luckyDirection: "中央", luckyActivity: "修理", shareText: "メンテの日 🔧🌍" },
    { message: "適度な社交。少人数を。", advice: "食事しながら意味ある会話を。", luckyColor: "キャラメル", luckyColorHex: "#FFD59A", luckyDirection: "南西", luckyActivity: "少人数の集まり", shareText: "少人数エネルギー 🌍💛" },
    { message: "体に知恵が宿っています。", advice: "違和感があったら注意。", luckyColor: "ハニー", luckyColorHex: "#EB9605", luckyDirection: "中央", luckyActivity: "ボディスキャン", shareText: "体の声に耳を 🌍" },
    { message: "財務安定は維持だが成長に忍耐。", advice: "不要なサブスクを見直し。", luckyColor: "ベージュ", luckyColorHex: "#F5F5DC", luckyDirection: "中央", luckyActivity: "財務レビュー", shareText: "賢いお金管理 💰🌍" },
    { message: "実践的な行動が言葉より効果的。", advice: "誰かのために役立つことを。", luckyColor: "サンド", luckyColorHex: "#C2B280", luckyDirection: "南西", luckyActivity: "奉仕", shareText: "行動で示す愛 🤲" },
    { message: "やりながら学ぶ日。", advice: "勉強より実践。", luckyColor: "クレイ", luckyColorHex: "#B66A50", luckyDirection: "中央", luckyActivity: "実践学習", shareText: "やりながら学ぶ 🌍🔨" },
    { message: "意見に重みがある日。", advice: "フィードバックはオブラートに包まず。", luckyColor: "アンバー", luckyColorHex: "#FFBF00", luckyDirection: "北東", luckyActivity: "フィードバック", shareText: "正直な土のエネルギー 🌍💬" },
    { message: "物質世界に感謝する日。", advice: "恵みのリストを書いて。", luckyColor: "ゴールド", luckyColorHex: "#F2CA50", luckyDirection: "中央", luckyActivity: "感謝日記", shareText: "恵みを数える 🌍🙏" },
  ], low: [
    { message: "基盤が揺らぐ感覚。感覚であって事実ではない。", advice: "裸足で大地に立ち深く呼吸。", luckyColor: "ブラウン", luckyColorHex: "#8B4513", luckyDirection: "中央", luckyActivity: "グラウンディング", shareText: "大地に足をつけて 🌍🧘" },
    { message: "安全への不安が浮かぶかも。ほとんど投影。", advice: "銀行残高を確認して落ち着いて。", luckyColor: "ダークサンド", luckyColorHex: "#967117", luckyDirection: "南西", luckyActivity: "事実確認", shareText: "事実が恐れに勝つ 🌍" },
    { message: "消化器系が敏感な日。", advice: "辛い・冷たい・加工食品を避けて。", luckyColor: "タン", luckyColorHex: "#D2B48C", luckyDirection: "中央", luckyActivity: "優しい食事", shareText: "胃に優しく 🍵" },
    { message: "考えすぎが行動を妨げます。", advice: "10の計画より1つの小さな行動。", luckyColor: "マッド", luckyColorHex: "#70543E", luckyDirection: "中央", luckyActivity: "小さな行動", shareText: "一歩 > 十の計画 🌍👣" },
    { message: "社交エネルギーが不足。", advice: "任意の約束はキャンセル。", luckyColor: "ソイル", luckyColorHex: "#6B4226", luckyDirection: "南西", luckyActivity: "休息", shareText: "一人充電モード 🌍🤫" },
    { message: "コントロールが重要に感じるが今日は不可能。", advice: "一つのことを手放して。", luckyColor: "ダスト", luckyColorHex: "#B5A642", luckyDirection: "中央", luckyActivity: "手放す", shareText: "コントロールを手放す 🌍🙌" },
    { message: "体が重く感じたら軽い動きを。", advice: "走るより歩く。", luckyColor: "サンドストーン", luckyColorHex: "#786D5F", luckyDirection: "中央", luckyActivity: "軽い動き", shareText: "優しく動く日 🌍🚶" },
    { message: "古いパターンが表面に。判断せず気づいて。", advice: "パターンに名前をつけて。", luckyColor: "ダークアンバー", luckyColorHex: "#B8860B", luckyDirection: "南西", luckyActivity: "自己観察", shareText: "パターンを見る — 気づきが癒す 🌍👁️" },
    { message: "物質的欲求が緊急に感じるが実際はそうではない。", advice: "買う前に24時間待って。", luckyColor: "ダークゴールド", luckyColorHex: "#AA8C2C", luckyDirection: "中央", luckyActivity: "意識的消費", shareText: "十分に持っている 🌍✨" },
    { message: "土に水の気が必要。しっかり水分補給。", advice: "いつもより多く水を。", luckyColor: "ウェットサンド", luckyColorHex: "#96856C", luckyDirection: "中央", luckyActivity: "水分補給", shareText: "水が土を養う 💧🌍" },
  ]},
  metal: { high: [
    { message: "精神が刃のように鋭い日。", advice: "先延ばしの決断を下して。", luckyColor: "シルバー", luckyColorHex: "#C0C0C0", luckyDirection: "西", luckyActivity: "意思決定", shareText: "明晰モード ⚔️" },
    { message: "精密さと品質が最高潮。", advice: "量より質。少なく完璧に。", luckyColor: "プラチナ", luckyColorHex: "#E5E4E2", luckyDirection: "西", luckyActivity: "職人技", shareText: "精密さ最高潮 ✨" },
    { message: "正義のエネルギーが強い。", advice: "公正なことを支持して。", luckyColor: "スティール", luckyColorHex: "#71797E", luckyDirection: "北西", luckyActivity: "公正擁護", shareText: "正義が明確 ⚖️" },
    { message: "金銭感覚が絶頂。", advice: "交渉や投資を見直し。", luckyColor: "ゴールドシルバー", luckyColorHex: "#CFB53B", luckyDirection: "西", luckyActivity: "財務分析", shareText: "金銭感覚最高 💰" },
    { message: "言葉に権威が乗る日。", advice: "プレゼン、提案を。", luckyColor: "ホワイトゴールド", luckyColorHex: "#EBEBEB", luckyDirection: "西", luckyActivity: "プレゼン", shareText: "権威モードON 🎤" },
    { message: "手放すことが強力な日。", advice: "一つきれいに終わらせて。", luckyColor: "クローム", luckyColorHex: "#DBE4EB", luckyDirection: "北西", luckyActivity: "終結", shareText: "きれいな切断のみ ✂️" },
    { message: "ディテール志向が最高潮。", advice: "校正、デバッグ、監査を。", luckyColor: "チタン", luckyColorHex: "#878681", luckyDirection: "西", luckyActivity: "監査", shareText: "何も逃さない 🔍" },
    { message: "規律が自然に来る日。", advice: "最も恐れるタスクを最初に。", luckyColor: "アイアン", luckyColorHex: "#4A4A4A", luckyDirection: "西", luckyActivity: "難しいタスク", shareText: "規律が武器 ⚔️" },
    { message: "美的感覚が高まる。", advice: "秩序と美を作って。", luckyColor: "パール", luckyColorHex: "#FDEEF4", luckyDirection: "北西", luckyActivity: "美的配置", shareText: "美しさと秩序 ✨" },
    { message: "契約や合意に有利な日。", advice: "署名し、約束を。", luckyColor: "シルバー", luckyColorHex: "#C0C0C0", luckyDirection: "西", luckyActivity: "正式契約", shareText: "約束のエネルギー 📝✨" },
  ], mid: [
    { message: "着実な分析エネルギー。", advice: "チェックリストを体系的に。", luckyColor: "グレー", luckyColorHex: "#808080", luckyDirection: "西", luckyActivity: "体系的作業", shareText: "安定した金のエネルギー ⚙️" },
    { message: "肺と肌に注意。深く呼吸して。", advice: "5分外で新鮮な空気を。", luckyColor: "ライトグレー", luckyColorHex: "#D3D3D3", luckyDirection: "西", luckyActivity: "呼吸運動", shareText: "深い呼吸 🌬️" },
    { message: "デジタルと物理空間を整理するのに良い。", advice: "写真削除、配信停止、整理。", luckyColor: "シルバー", luckyColorHex: "#C0C0C0", luckyDirection: "北西", luckyActivity: "デジタル整理", shareText: "デジタルデトックス 🗂️" },
    { message: "会話に簡潔さが役立つ。", advice: "話す前に言葉を磨いて。", luckyColor: "ピューター", luckyColorHex: "#96A8A1", luckyDirection: "西", luckyActivity: "簡潔なコミュニケーション", shareText: "少ない言葉、多い意味 ✂️" },
    { message: "適度な規律。習慣に使って。", advice: "ルーティンを維持。", luckyColor: "アルミニウム", luckyColorHex: "#A9A9A9", luckyDirection: "西", luckyActivity: "ルーティン", shareText: "ルーティンが力 ⚙️" },
    { message: "批判的な目は自己改善に。他人には優しく。", advice: "自分を批評、他人を褒めて。", luckyColor: "ニッケル", luckyColorHex: "#727472", luckyDirection: "北西", luckyActivity: "自己改善", shareText: "自分を磨き他者を認める ⚖️" },
    { message: "ノスタルジアが湧くかも。", advice: "古い写真を見て微笑み前を向いて。", luckyColor: "アンティークシルバー", luckyColorHex: "#7B8788", luckyDirection: "西", luckyActivity: "思い出", shareText: "美しい思い出、輝く未来 🪞" },
    { message: "貯蓄に良く、支出は慎重に。", advice: "少額を貯金に。", luckyColor: "コインゴールド", luckyColorHex: "#CD7F32", luckyDirection: "西", luckyActivity: "貯金", shareText: "貯蓄モード 💰" },
    { message: "体に構造が必要。規則的な食事と睡眠。", advice: "一定時間に三食。", luckyColor: "スレート", luckyColorHex: "#708090", luckyDirection: "西", luckyActivity: "構造ルーティン", shareText: "構造＝健康 🕐" },
    { message: "契約や書類に良いエネルギー。", advice: "細かい条項を読んで。", luckyColor: "スティールブルー", luckyColorHex: "#4682B4", luckyDirection: "北西", luckyActivity: "書類", shareText: "細かい条項を読む 📄🔍" },
  ], low: [
    { message: "内なる批判者がうるさい日。", advice: "批判に強みで反論。", luckyColor: "ダークグレー", luckyColorHex: "#4A4A4A", luckyDirection: "西", luckyActivity: "セルフコンパッション", shareText: "批判者をミュート 🤍" },
    { message: "悲しみや喪失感が浮かぶかも。", advice: "理由なく悲しくても大丈夫。", luckyColor: "チャコール", luckyColorHex: "#36454F", luckyDirection: "西", luckyActivity: "感情解放", shareText: "秋のエネルギー 🍂" },
    { message: "呼吸が窮屈に感じます。", advice: "4-7-8呼吸法を実践。", luckyColor: "フォグ", luckyColorHex: "#C0C0C0", luckyDirection: "北西", luckyActivity: "呼吸法", shareText: "呼吸を広げる 🌬️" },
    { message: "完璧主義が進歩を妨げる。80%で十分。", advice: "80%で提出、送信。", luckyColor: "アッシュ", luckyColorHex: "#B2BEB5", luckyDirection: "西", luckyActivity: "不完全な完了", shareText: "80%完成 > 100%計画 📤" },
    { message: "孤立が誘うが繋がりが癒す。", advice: "テキスト一通、電話一本。", luckyColor: "ストームグレー", luckyColorHex: "#717D7E", luckyDirection: "西", luckyActivity: "小さな繋がり", shareText: "一回の連絡が全てを変える 📱" },
    { message: "硬直が摩擦を生む。期待を柔らかく。", advice: "他者のやり方を許して。", luckyColor: "スモーク", luckyColorHex: "#738276", luckyDirection: "北西", luckyActivity: "柔軟性", shareText: "金の鋭い面を柔らかく 🌊" },
    { message: "肌やアレルギーが出るかも。", advice: "肌に水分、加工食品を減らして。", luckyColor: "ペールシルバー", luckyColorHex: "#D4D4D4", luckyDirection: "西", luckyActivity: "スキンケア", shareText: "金の元素が肌で語る 🧴" },
    { message: "価値が不明確に感じる日。", advice: "低い日に人生を見直さないで。", luckyColor: "ガンメタル", luckyColorHex: "#2C3539", luckyDirection: "西", luckyActivity: "休む", shareText: "今日は人生の決断なし 😌" },
    { message: "基準が不可能に高い。今日だけ下げて。", advice: "平凡でいいと許可を。", luckyColor: "レッド", luckyColorHex: "#6B6B6B", luckyDirection: "北西", luckyActivity: "不完全への許可", shareText: "不完全でもいい 🤍" },
    { message: "金が重い日。荷を軽く。", advice: "不要なもの一つ手放して。", luckyColor: "くすんだシルバー", luckyColorHex: "#8A8D8F", luckyDirection: "西", luckyActivity: "荷を軽く", shareText: "重さを降ろす 🪶" },
  ]},
  water: { high: [
    { message: "直感が川のよう。力強く正しい。", advice: "最初の直感に従って。", luckyColor: "ディープブルー", luckyColorHex: "#3B82F6", luckyDirection: "北", luckyActivity: "直感に従う", shareText: "直感が最大 🌊" },
    { message: "知恵が流れる。周りが助言を求める。", advice: "見解を自由に共有。", luckyColor: "ネイビー", luckyColorHex: "#000080", luckyDirection: "北", luckyActivity: "メンタリング", shareText: "知恵のオーバーフロー 🌊🧠" },
    { message: "岩を回る水のように障害を越える。", advice: "塞がったら回り込んで。", luckyColor: "オーシャンブルー", luckyColorHex: "#4F93CE", luckyDirection: "北西", luckyActivity: "創造的問題解決", shareText: "水は道を見つける 🌊💪" },
    { message: "深い繋がりが形成される日。", advice: "「本当に調子は？」と聞いて聴いて。", luckyColor: "アクアマリン", luckyColorHex: "#7FFFD4", luckyDirection: "北", luckyActivity: "深い会話", shareText: "深い対話 🌊💙" },
    { message: "隠された知識が表面に。", advice: "繰り返す思考に注意。", luckyColor: "サファイア", luckyColorHex: "#0F52BA", luckyDirection: "北", luckyActivity: "夢日記", shareText: "隠された真実が浮上 🌊🔮" },
    { message: "金運が改善。予想外のルートで。", advice: "普段と違う収入源に心を開いて。", luckyColor: "セルリアン", luckyColorHex: "#007BA7", luckyDirection: "北西", luckyActivity: "財務的開放性", shareText: "お金が流れ込む 💰🌊" },
    { message: "感情知性が最高潮。", advice: "関係を癒すか取引を成立させて。", luckyColor: "ティール", luckyColorHex: "#008080", luckyDirection: "北", luckyActivity: "感情ナビ", shareText: "空気を完璧に読む 🌊👁️" },
    { message: "コミュニケーションが詩のよう。", advice: "大切なことを書いて。", luckyColor: "ロイヤルブルー", luckyColorHex: "#4169E1", luckyDirection: "北", luckyActivity: "文章", shareText: "言葉が水のように 🌊✍️" },
    { message: "ヒーリングエネルギーが強い。", advice: "休めば治りが早い日。", luckyColor: "スカイブルー", luckyColorHex: "#87CEEB", luckyDirection: "北西", luckyActivity: "休息と癒し", shareText: "癒しの加速 🌊💙" },
    { message: "フロー状態にアクセスできる日。", advice: "2時間の集中クリエイティブタイムを。", luckyColor: "コバルト", luckyColorHex: "#0047AB", luckyDirection: "北", luckyActivity: "深い創作", shareText: "フロー状態起動 🌊🎨" },
  ], mid: [
    { message: "穏やかで内省的なエネルギー。", advice: "反応する前に振り返って。", luckyColor: "ライトブルー", luckyColorHex: "#ADD8E6", luckyDirection: "北", luckyActivity: "内省", shareText: "内省の日 🌊" },
    { message: "腎臓エネルギーにサポートが必要。", advice: "水を8杯飲んで。", luckyColor: "ブルー", luckyColorHex: "#3B82F6", luckyDirection: "北", luckyActivity: "水分補給", shareText: "水分補給が優先 💧" },
    { message: "適度な直感。確認してから行動。", advice: "信じつつ確認を。", luckyColor: "ペリウィンクル", luckyColorHex: "#CCCCFF", luckyDirection: "北西", luckyActivity: "バランス判断", shareText: "信じて確認 🌊🔍" },
    { message: "新しい情報を吸収するのに良い。", advice: "読んで聴いて学んで。", luckyColor: "アイスブルー", luckyColorHex: "#99CCFF", luckyDirection: "北", luckyActivity: "学習", shareText: "知識吸収モード 📚🌊" },
    { message: "関係が心地よいペースで流れる。", advice: "穏やかさを楽しんで。", luckyColor: "パウダーブルー", luckyColorHex: "#B0E0E6", luckyDirection: "北", luckyActivity: "リラックス社交", shareText: "穏やかな水面 🌊😌" },
    { message: "睡眠の質がいつも以上に大切。", advice: "就寝30分前はスクリーンなし。", luckyColor: "ミッドナイトブルー", luckyColorHex: "#191970", luckyDirection: "北", luckyActivity: "睡眠最適化", shareText: "深い眠りが癒す 🌊🌙" },
    { message: "衝動買いを避けて。", advice: "$50以上は24時間待って。", luckyColor: "スティールブルー", luckyColorHex: "#4682B4", luckyDirection: "北西", luckyActivity: "意識的消費", shareText: "意識的な消費 💰" },
    { message: "共感力が頼りになる日。", advice: "共感的に聴きつつ境界を。", luckyColor: "アクア", luckyColorHex: "#00CED1", luckyDirection: "北", luckyActivity: "共感的傾聴", shareText: "共感ON、吸収OFF 🌊🛡️" },
    { message: "体の柔軟性が良い日。", advice: "ヨガ、水泳、温かいシャワー。", luckyColor: "ターコイズ", luckyColorHex: "#40E0D0", luckyDirection: "北", luckyActivity: "ストレッチ", shareText: "体が流れる日 🌊🧘" },
    { message: "記憶が知恵を運ぶ日。", advice: "似た過去の状況を思い出して。", luckyColor: "スレートブルー", luckyColorHex: "#6A5ACD", luckyDirection: "北西", luckyActivity: "過去の知恵", shareText: "過去の知恵、現在の力 🌊" },
  ], low: [
    { message: "水の気が停滞する日。感情が濁る。", advice: "体を動かして水の気を動かして。", luckyColor: "ダークブルー", luckyColorHex: "#00008B", luckyDirection: "北", luckyActivity: "運動", shareText: "濁った水は動けば澄む 🌊🚶" },
    { message: "恐れが浮上するが信頼できない。", advice: "恐れを声に出して名前を。", luckyColor: "ミッドナイト", luckyColorHex: "#191970", luckyDirection: "北", luckyActivity: "恐れの認知", shareText: "恐れに名前を 🌊💪" },
    { message: "腎臓エネルギーが低い。温かさと休息を。", advice: "腰を温かく。温水を。", luckyColor: "インクブルー", luckyColorHex: "#0A1628", luckyDirection: "北", luckyActivity: "温かく", shareText: "水の元素を温める 🫖🌊" },
    { message: "コミュニケーションが誤読されるかも。", advice: "意図を過剰に伝えて。", luckyColor: "ストームブルー", luckyColorHex: "#507786", luckyDirection: "北西", luckyActivity: "明確なコミュニケーション", shareText: "伝えたいことを明確に 🌊💬" },
    { message: "感情的な過負荷の可能性。", advice: "水の近くで一人の時間を。", luckyColor: "ディープシー", luckyColorHex: "#003366", luckyDirection: "北", luckyActivity: "水辺で一人", shareText: "水を求めてリセット 🌊" },
    { message: "先延ばしは水の影。", advice: "10分タイマーで始めて。", luckyColor: "ブルーグレー", luckyColorHex: "#6699CC", luckyDirection: "北", luckyActivity: "タイマー作業", shareText: "10分。それだけ。🌊⏱️" },
    { message: "孤立が不必要に深まる。", advice: "カフェや公園など人がいる場所に。", luckyColor: "トワイライト", luckyColorHex: "#4E5180", luckyDirection: "北", luckyActivity: "人がいる場所", shareText: "完全に一人ではなく 🌊☕" },
    { message: "夢が鮮明で不安になるかも。", advice: "起きたらすぐ夢を書いて。", luckyColor: "ナイトブルー", luckyColorHex: "#1B2838", luckyDirection: "北西", luckyActivity: "夢日記", shareText: "今夜夢が語る 🌊🌙" },
    { message: "知恵にアクセスできない感覚。", advice: "洞察を強要せず他者の知恵を。", luckyColor: "オーシャンダーク", luckyColorHex: "#023E73", luckyDirection: "北", luckyActivity: "知恵文学", shareText: "知恵を借りる日 📚🌊" },
    { message: "体の冷えは水の気が低いサイン。", advice: "温かいお風呂やシャワーを。", luckyColor: "フロストブルー", luckyColorHex: "#7EB6D0", luckyDirection: "北", luckyActivity: "温める儀式", shareText: "温める — 体温が水のエネルギーを回復 🛁🌊" },
  ]},
};
