// Korean Daily Fortune Messages (한국어)
import type { DailyFortune } from "./daily-fortune";
type Tier = "high" | "mid" | "low";

export const FORTUNES_KO: Record<string, Record<Tier, DailyFortune[]>> = {
  wood: {
    high: [
      { message: "목 기운이 활짝 피어나는 날입니다. 오전에 떠오르는 아이디어가 가장 강력합니다.", advice: "새 프로젝트를 시작하거나 아이디어를 제안하세요.", luckyColor: "초록", luckyColorHex: "#59DE9B", luckyDirection: "동쪽", luckyActivity: "나무 사이 산책", shareText: "오늘 목 기운 폭발 🌿 창의력 최고조!" },
      { message: "성장의 기회가 가득합니다. 오늘 나누는 대화가 뜻밖의 문을 열 수 있습니다.", advice: "즉흥적인 만남에 '예'라고 답하세요.", luckyColor: "청록", luckyColorHex: "#2DD4BF", luckyDirection: "동남쪽", luckyActivity: "아침 일기 쓰기", shareText: "성장의 기운이 충만한 하루 🌱" },
      { message: "타고난 리더십이 빛나는 날. 주변 사람들이 자연스럽게 따릅니다.", advice: "그룹 모임에서 적극적으로 의견을 내세요.", luckyColor: "비취", luckyColorHex: "#00A86B", luckyDirection: "동쪽", luckyActivity: "팀 협업", shareText: "갑목 에너지 최강 — 오늘은 리더 모드 甲" },
      { message: "지난 몇 주간 뿌린 씨앗이 싹트기 시작합니다.", advice: "기다리던 일에 대해 후속 연락을 해보세요.", luckyColor: "에메랄드", luckyColorHex: "#50C878", luckyDirection: "동북쪽", luckyActivity: "정원 가꾸기 또는 요리", shareText: "노력의 결실이 보이기 시작하는 날 🌿" },
      { message: "유연함이 오늘의 초능력입니다. 부러지지 않고 휘어지면 완벽한 길을 찾습니다.", advice: "계획을 강요하기보다 유연하게 조정하세요.", luckyColor: "라임", luckyColorHex: "#84CC16", luckyDirection: "동쪽", luckyActivity: "스트레칭 또는 요가", shareText: "목은 휘어져도 부러지지 않는다 💚" },
      { message: "오후에 창작 영감이 폭발합니다. 아이디어를 놓치지 마세요.", advice: "메모장을 가까이 두고 생각을 기록하세요.", luckyColor: "진초록", luckyColorHex: "#228B22", luckyDirection: "동남쪽", luckyActivity: "글쓰기 또는 그림", shareText: "오후 영감 폭발 예정 🎋" },
      { message: "당신의 따뜻한 마음이 도움이 필요한 누군가를 끌어당깁니다.", advice: "오늘은 말하기보다 들어주세요.", luckyColor: "세이지", luckyColorHex: "#9CAF88", luckyDirection: "동쪽", luckyActivity: "멘토링", shareText: "목 기운이 다른 사람을 치유하는 날 🌳" },
      { message: "확장의 에너지가 강합니다. 오늘 시작하는 것은 성장 잠재력이 뛰어납니다.", advice: "발표하고, 시작하고, 도전하세요.", luckyColor: "연두", luckyColorHex: "#00FF7F", luckyDirection: "동쪽", luckyActivity: "새로운 것 시작하기", shareText: "새로운 시작의 에너지 최대치 ☘️" },
      { message: "도덕적 나침반이 정확하게 작동하는 날. 옳고 그름의 감각을 믿으세요.", advice: "미루던 결정을 내리세요.", luckyColor: "올리브", luckyColorHex: "#808000", luckyDirection: "동북쪽", luckyActivity: "공간 정리하기", shareText: "직감을 믿어라 — 사주가 확인해준다 ✅" },
      { message: "아이디어 간의 연결이 자연스럽게 형성됩니다. 남들이 못 보는 패턴이 보입니다.", advice: "통찰을 공유하세요 — 생각보다 가치있습니다.", luckyColor: "민트", luckyColorHex: "#98FF98", luckyDirection: "동남쪽", luckyActivity: "브레인스토밍", shareText: "패턴 인식 능력: 활성화 🧠🌿" },
    ],
    mid: [
      { message: "꾸준한 성장의 날. 극적이진 않지만 뿌리가 깊어지고 있습니다.", advice: "강도보다 꾸준함에 집중하세요.", luckyColor: "고사리", luckyColorHex: "#4F7942", luckyDirection: "동쪽", luckyActivity: "일상적인 업무", shareText: "조용한 성장의 하루 🌿" },
      { message: "새로운 관계보다 기존 관계를 돌보기 좋은 날입니다.", advice: "오랫동안 연락 못 한 사람에게 먼저 연락하세요.", luckyColor: "이끼", luckyColorHex: "#8A9A5B", luckyDirection: "동남쪽", luckyActivity: "오랜 친구와 수다", shareText: "관계 돌봄 모드: ON 💚" },
      { message: "인내가 시험받지만 보상받는 날.", advice: "서두르지 마세요. 자연스럽게 흘러가게 두세요.", luckyColor: "초록", luckyColorHex: "#59DE9B", luckyDirection: "동쪽", luckyActivity: "독서 또는 공부", shareText: "인내가 나의 초능력 🎋" },
      { message: "적당한 창작 에너지. 새 아이디어보다 기존 아이디어를 다듬기 좋습니다.", advice: "이미 시작한 것을 편집, 다듬고, 개선하세요.", luckyColor: "피스타치오", luckyColorHex: "#93C572", luckyDirection: "동북쪽", luckyActivity: "편집과 수정", shareText: "다듬기의 날 — 좋은 것을 훌륭하게 🌱" },
      { message: "주고받음의 균형이 중요한 날.", advice: "도움이 제안될 때 받아들이세요.", luckyColor: "세이지", luckyColorHex: "#9CAF88", luckyDirection: "동쪽", luckyActivity: "자기 관리", shareText: "받는 법을 배우는 날 ⚖️🌿" },
      { message: "재정 결정에 안정적인 날. 위험은 아니지만 저축에 좋습니다.", advice: "예산을 검토하거나 자동 저축을 설정하세요.", luckyColor: "헌터 그린", luckyColorHex: "#355E3B", luckyDirection: "동남쪽", luckyActivity: "재정 계획", shareText: "안정적인 재정 에너지 💰" },
      { message: "몸이 움직임을 원합니다. 신체 활동이 정신적 안개를 걷어냅니다.", advice: "20분간 걸으세요, 가능하면 녹지 근처에서.", luckyColor: "라임", luckyColorHex: "#84CC16", luckyDirection: "동쪽", luckyActivity: "야외 운동", shareText: "몸이 '움직여!'라고 한다 🏃🌿" },
      { message: "배움에 좋지만 가르치기엔 애매한 날.", advice: "읽고, 듣고, 온라인 강의를 수강하세요.", luckyColor: "청록", luckyColorHex: "#2DD4BF", luckyDirection: "동북쪽", luckyActivity: "새로운 것 배우기", shareText: "학생 모드 — 지식을 스펀지처럼 흡수 중 📚" },
      { message: "관계에 정직함이 도움되는 날.", advice: "피해왔던 대화를 나누세요.", luckyColor: "민트", luckyColorHex: "#98FF98", luckyDirection: "동쪽", luckyActivity: "솔직한 대화", shareText: "진실을 말하는 날 🌿💬" },
      { message: "환경이 평소보다 중요합니다. 깨끗한 공간 = 맑은 마음.", advice: "15분간 작업 공간을 정리하세요.", luckyColor: "에메랄드", luckyColorHex: "#50C878", luckyDirection: "동남쪽", luckyActivity: "정리 정돈", shareText: "깨끗한 공간, 맑은 마음 🧹" },
    ],
    low: [
      { message: "목 기운이 압축된 날. 성장이 멈춘 게 아니라 쉬고 있는 것.", advice: "죄책감 없이 쉬세요. 큰 나무도 겨울잠을 잡니다.", luckyColor: "짙은 초록", luckyColorHex: "#006400", luckyDirection: "동쪽", luckyActivity: "낮잠 또는 명상", shareText: "쉬는 날 — 거대한 참나무도 고요함이 필요하다 🌳💤" },
      { message: "창의력은 막혔지만 명확성은 올라갑니다. 분석에 집중하세요.", advice: "만들기보다 정리, 분류, 계획하세요.", luckyColor: "올리브", luckyColorHex: "#808000", luckyDirection: "동북쪽", luckyActivity: "계획 세우기", shareText: "분석 모드 ON 🌿" },
      { message: "금 기운이 제약하는 날. 한계 안에서 길을 찾으세요.", advice: "제약 안에서 일하세요.", luckyColor: "숲", luckyColorHex: "#228B22", luckyDirection: "동쪽", luckyActivity: "한계 안에서 작업", shareText: "제약이 창의력을 낳는다 🎋" },
      { message: "에너지가 낮다고 가치가 낮은 건 아닙니다.", advice: "혼자만의 시간을 보내세요.", luckyColor: "세이지", luckyColorHex: "#9CAF88", luckyDirection: "동남쪽", luckyActivity: "혼자 사색", shareText: "고요한 순간에 지혜가 있다 🌱🤫" },
      { message: "간과 눈에 특별한 관리가 필요한 날.", advice: "녹색 채소를 먹고 눈에 휴식을 주세요.", luckyColor: "초록", luckyColorHex: "#59DE9B", luckyDirection: "동쪽", luckyActivity: "저녁 디지털 디톡스", shareText: "자기 관리 우선 💚" },
      { message: "사회적 에너지가 낮습니다. 자신만의 공간을 지키세요.", advice: "에너지를 빼는 약속은 취소하세요.", luckyColor: "이끼", luckyColorHex: "#8A9A5B", luckyDirection: "동쪽", luckyActivity: "고독과 휴식", shareText: "경계선은 자기 사랑 🌿🛡️" },
      { message: "재정적 주의가 필요합니다. 큰 구매는 다른 날에.", advice: "쇼핑은 다른 날을 위해 아껴두세요.", luckyColor: "짙은 이끼", luckyColorHex: "#4A5D23", luckyDirection: "동북쪽", luckyActivity: "예산 관리", shareText: "지갑은 오늘 닫아두자 💰🌿" },
      { message: "과거의 후회가 떠오를 수 있습니다. 인정하고 놓아주세요.", advice: "신경 쓰이는 것을 적어보고 노트를 닫으세요.", luckyColor: "고사리", luckyColorHex: "#4F7942", luckyDirection: "동쪽", luckyActivity: "일기 쓰기", shareText: "도움이 되지 않는 것을 놓아주는 날 🍃" },
      { message: "평소의 유연함이 뻣뻣하게 느껴집니다. 때론 고요함이 답.", advice: "잠자리에 들기 전 가벼운 스트레칭을 하세요.", luckyColor: "소나무", luckyColorHex: "#01796F", luckyDirection: "동남쪽", luckyActivity: "가벼운 스트레칭", shareText: "고요함이 힘이다 🌲" },
      { message: "다른 사람이 오해할 수 있는 날. 시간이 해결합니다.", advice: "오해가 자연스럽게 풀리도록 두세요.", luckyColor: "바질", luckyColorHex: "#487800", luckyDirection: "동쪽", luckyActivity: "인내 연습", shareText: "모든 것을 설명할 필요는 없다 🌿" },
    ],
  },
  fire: { high: [
    { message: "카리스마가 자석처럼 작용하는 날.", advice: "영향력을 의미 있는 일에 사용하세요.", luckyColor: "빨강", luckyColorHex: "#EF4444", luckyDirection: "남쪽", luckyActivity: "발표 또는 프레젠테이션", shareText: "화 기운 폭발 🔥 멈출 수 없는 카리스마!" },
    { message: "열정과 명확함이 완벽하게 일치합니다.", advice: "망설이지 말고 목표를 향해 달리세요.", luckyColor: "크림슨", luckyColorHex: "#DC143C", luckyDirection: "남쪽", luckyActivity: "과감한 행동", shareText: "마음과 머리가 하나 🔥❤️" },
    { message: "당신의 열정이 주변을 불태웁니다.", advice: "지시가 아닌 영감으로 이끄세요.", luckyColor: "오렌지레드", luckyColorHex: "#FF4500", luckyDirection: "서남쪽", luckyActivity: "그룹 활동", shareText: "방에 불을 지르는 중 (좋은 의미로) 🔥✨" },
    { message: "인정받는 에너지가 강합니다.", advice: "오늘은 성과를 겸손하게 말하지 마세요.", luckyColor: "코랄", luckyColorHex: "#FF7F50", luckyDirection: "남쪽", luckyActivity: "성과 보여주기", shareText: "인정받을 운명 🌟🔥" },
    { message: "로맨틱 에너지가 최고조.", advice: "감정을 직접적으로 표현하세요.", luckyColor: "로즈 레드", luckyColorHex: "#C21E56", luckyDirection: "남쪽", luckyActivity: "데이트 또는 고백", shareText: "화 + 로맨스 = 오늘 🔥💕" },
    { message: "직감이 혼란을 꿰뚫습니다.", advice: "오늘 첫 번째 결정은 직감대로.", luckyColor: "스칼렛", luckyColorHex: "#FF2400", luckyDirection: "동남쪽", luckyActivity: "결단력 있는 행동", shareText: "직감이 불타고 있다 🔥⚡" },
    { message: "경쟁 에너지가 당신 편.", advice: "어떤 도전이든 최선을 다하세요.", luckyColor: "플레임", luckyColorHex: "#E25822", luckyDirection: "남쪽", luckyActivity: "경쟁 또는 스포츠", shareText: "경쟁의 날 — 화의 기운이 '승리'를 말한다 🏆🔥" },
    { message: "기쁨이 당신에게서 뿜어나오는 날.", advice: "다른 사람을 웃게 만드세요.", luckyColor: "탠저린", luckyColorHex: "#FF9966", luckyDirection: "서남쪽", luckyActivity: "다른 사람 웃기기", shareText: "기쁨 기계 활성화 🔥😊" },
    { message: "창작의 불이 깨끗하게 타오릅니다.", advice: "무엇이든 만드세요. 매체는 중요하지 않습니다.", luckyColor: "루비", luckyColorHex: "#E0115F", luckyDirection: "남쪽", luckyActivity: "예술 창작", shareText: "아트 모드: 활성화 🎨🔥" },
    { message: "변환의 에너지가 최고조.", advice: "포기했던 프로젝트를 새로운 눈으로 다시 보세요.", luckyColor: "피닉스 레드", luckyColorHex: "#CD2029", luckyDirection: "남쪽", luckyActivity: "오래된 프로젝트 되살리기", shareText: "불사조 에너지 🔥🦅" },
  ], mid: [
    { message: "따뜻하고 안정적인 화기. 시작보다 유지하기 좋은 날.", advice: "기존 약속을 지키세요.", luckyColor: "피치", luckyColorHex: "#FFCBA4", luckyDirection: "남쪽", luckyActivity: "할 일 마무리", shareText: "안정적인 불꽃 🕯️" },
    { message: "마음은 열려있지만 에너지는 보통. 한 사람에게 집중.", advice: "관계의 양보다 질에 집중.", luckyColor: "살몬", luckyColorHex: "#FA8072", luckyDirection: "서남쪽", luckyActivity: "1:1 시간", shareText: "불꽃을 한 곳에 집중 🔥" },
    { message: "실행보다 계획에 좋은 날.", advice: "전략 먼저, 행동은 나중에.", luckyColor: "앰버", luckyColorHex: "#FFBF00", luckyDirection: "남쪽", luckyActivity: "전략 수립", shareText: "다음 불꽃을 계획 중 🔥📋" },
    { message: "적당한 영감. 실행 전 숙성이 필요합니다.", advice: "아이디어를 적어두되 하룻밤 재워두세요.", luckyColor: "코랄", luckyColorHex: "#FF7F50", luckyDirection: "동남쪽", luckyActivity: "아이디어 메모", shareText: "불꽃을 모으는 중 🌟" },
    { message: "사교 에너지가 쾌적하지만 폭발적이지 않은 날.", advice: "감동을 주려 하지 말고 그냥 함께.", luckyColor: "로즈", luckyColorHex: "#FF007F", luckyDirection: "남쪽", luckyActivity: "가벼운 사교", shareText: "편안한 화 에너지 🕯️😌" },
    { message: "마음이 머리보다 먼저 알고 있는 것이 있습니다.", advice: "분석하기 전에 감정과 함께 앉아보세요.", luckyColor: "벽돌", luckyColorHex: "#CB4154", luckyDirection: "남쪽", luckyActivity: "감정 정리", shareText: "마음의 지혜가 로딩 중 🔥💭" },
    { message: "재정 에너지는 중립. 작은 투자는 자랍니다.", advice: "조금 저축하세요.", luckyColor: "오렌지", luckyColorHex: "#FF8C00", luckyDirection: "서남쪽", luckyActivity: "소액 저축", shareText: "작은 불꽃, 큰 미래 💰🔥" },
    { message: "움직여야 화기가 순환됩니다.", advice: "15분이라도 운동하면 하루가 바뀝니다.", luckyColor: "레드오렌지", luckyColorHex: "#FF5349", luckyDirection: "남쪽", luckyActivity: "유산소 운동", shareText: "움직여야 불이 산다 🏃🔥" },
    { message: "소통이 순조로운 날.", advice: "머릿속에서 작성 중이던 메시지를 보내세요.", luckyColor: "탠저린", luckyColorHex: "#FF9966", luckyDirection: "남쪽", luckyActivity: "서면 소통", shareText: "말이 불처럼 흐르는 날 📝🔥" },
    { message: "가진 것에 감사하는 날.", advice: "지금 감사한 것 3가지를 말해보세요.", luckyColor: "웜 핑크", luckyColorHex: "#FF6B81", luckyDirection: "동남쪽", luckyActivity: "감사 연습", shareText: "감사하는 마음 = 강한 불 🔥🙏" },
  ], low: [
    { message: "오늘의 불은 잔불. 하지만 가장 깊은 따뜻함이 있는 곳.", advice: "따뜻함 가까이 쉬세요.", luckyColor: "버건디", luckyColorHex: "#800020", luckyDirection: "남쪽", luckyActivity: "아늑한 자기 관리", shareText: "잔불의 하루 🕯️" },
    { message: "심장 에너지가 낮습니다. 보호하세요.", advice: "설명 없이 경계를 세우세요.", luckyColor: "다크 레드", luckyColorHex: "#8B0000", luckyDirection: "서남쪽", luckyActivity: "경계 설정", shareText: "내 불꽃을 보호하는 날 🔥🛡️" },
    { message: "순환과 심장에 관리가 필요한 날.", advice: "찬 음료를 피하세요. 따뜻한 물과 차를.", luckyColor: "마룬", luckyColorHex: "#800000", luckyDirection: "남쪽", luckyActivity: "따뜻한 음료와 휴식", shareText: "화 원소 관리 🫖❤️" },
    { message: "자신감이 일시적으로 내려가는 날. 불은 반드시 돌아옵니다.", advice: "낮은 날에 자기 평가를 하지 마세요.", luckyColor: "러스트", luckyColorHex: "#B7410E", luckyDirection: "남쪽", luckyActivity: "자기 비판 피하기", shareText: "낮은 불꽃 ≠ 꺼진 불 🔥" },
    { message: "오늘 말다툼을 피하세요.", advice: "어려운 대화는 내일로 미루세요.", luckyColor: "벽돌", luckyColorHex: "#CB4154", luckyDirection: "동남쪽", luckyActivity: "갈등 회피", shareText: "평화를 선택하는 날 🕊️" },
    { message: "창의력이 쉬고 있을 뿐, 사라진 게 아닙니다.", advice: "만들기 대신 예술을 감상하세요.", luckyColor: "딥 로즈", luckyColorHex: "#C21E56", luckyDirection: "남쪽", luckyActivity: "영화 감상 또는 독서", shareText: "창작 휴식의 날 🎬📚" },
    { message: "외로움이 속삭일 수 있지만, 거짓말입니다.", advice: "누군가에게 '생각나서'라고 한마디 보내세요.", luckyColor: "웜 브라운", luckyColorHex: "#964B00", luckyDirection: "서남쪽", luckyActivity: "소중한 사람에게 연락", shareText: "연결이 치유한다 💌" },
    { message: "결정이 평소보다 어렵습니다. 기다리라는 신호.", advice: "큰 결정은 24시간 미루세요.", luckyColor: "테라코타", luckyColorHex: "#E2725B", luckyDirection: "남쪽", luckyActivity: "결정 미루기", shareText: "미루는 것 = 오늘의 지혜 🔥⏳" },
    { message: "체력이 낮은 날. 휴식은 게으름이 아니라 연료.", advice: "오늘 밤 30분 일찍 잠자리에 드세요.", luckyColor: "다크 코랄", luckyColorHex: "#CD5B45", luckyDirection: "남쪽", luckyActivity: "일찍 취침", shareText: "쉬는 것이 곧 일 🔥💤" },
    { message: "다른 사람이 자신의 빛을 찾도록 당신의 빛이 잠시 낮아집니다.", advice: "오늘은 다른 사람이 주도하게 하세요.", luckyColor: "애쉬 로즈", luckyColorHex: "#B5651D", luckyDirection: "동남쪽", luckyActivity: "조용히 응원하기", shareText: "내 빛을 낮춰 다른 이가 빛나게 🌅" },
  ]},
  earth: { high: [
    { message: "안정감이 초능력인 날. 당신이 있으면 주변도 안정됩니다.", advice: "필요한 사람에게 자리를 내어주세요.", luckyColor: "골드", luckyColorHex: "#F2CA50", luckyDirection: "중앙", luckyActivity: "누군가의 버팀목 되기", shareText: "산의 에너지 🏔️✨" },
    { message: "실용적 지혜가 최고조. 단순한 해결책이 정답.", advice: "복잡한 답보다 단순한 답을 믿으세요.", luckyColor: "앰버", luckyColorHex: "#FFBF00", luckyDirection: "서남쪽", luckyActivity: "문제 해결", shareText: "토 지혜 활성화 🌍" },
    { message: "재정 에너지가 훌륭합니다.", advice: "고민 중이던 재정적 결정을 실행하세요.", luckyColor: "허니", luckyColorHex: "#EB9605", luckyDirection: "중앙", luckyActivity: "재정 결정", shareText: "토 = 재물 에너지 💰🌍" },
    { message: "양육 본능이 강력합니다. 오늘 돌보는 모든 것이 번창.", advice: "요리, 정원 가꾸기, 공간 가꾸기를 하세요.", luckyColor: "오커", luckyColorHex: "#CC7722", luckyDirection: "서남쪽", luckyActivity: "요리 또는 정원 가꾸기", shareText: "오늘 내가 만지는 것은 모두 자란다 🌻" },
    { message: "기초를 쌓는 에너지가 최고.", advice: "인내와 구조가 필요한 프로젝트를 시작하세요.", luckyColor: "브론즈", luckyColorHex: "#CD7F32", luckyDirection: "중앙", luckyActivity: "기초 만들기", shareText: "기초 공사의 날 🏗️🌍" },
    { message: "신뢰성이 기회를 끌어당깁니다.", advice: "책임감을 받아들이세요 — 선물입니다.", luckyColor: "시에나", luckyColorHex: "#A0522D", luckyDirection: "동북쪽", luckyActivity: "책임 맡기", shareText: "신뢰 = 기회 🌍🤝" },
    { message: "수확의 에너지가 도착합니다.", advice: "칭찬을 겸손하게 거절하지 마세요.", luckyColor: "밀", luckyColorHex: "#F5DEB3", luckyDirection: "중앙", luckyActivity: "인정 받기", shareText: "수확의 때 🌾✨" },
    { message: "인내가 배당금을 줍니다.", advice: "가던 길을 유지하세요.", luckyColor: "모래", luckyColorHex: "#C2B280", luckyDirection: "서남쪽", luckyActivity: "인내와 끈기", shareText: "인내 = 나의 초능력 🏔️" },
    { message: "체력이 최고조.", advice: "육체 노동이나 고강도 운동에 도전하세요.", luckyColor: "테라코타", luckyColorHex: "#E2725B", luckyDirection: "중앙", luckyActivity: "운동 또는 육체 노동", shareText: "토의 몸이 강한 날 💪🌍" },
    { message: "환경의 조화가 마음의 조화를 만듭니다.", advice: "주변 환경을 재배치하거나 아름다움을 더하세요.", luckyColor: "크림", luckyColorHex: "#FFFDD0", luckyDirection: "중앙", luckyActivity: "인테리어 개선", shareText: "공간에 아름다움을 🏡✨" },
  ], mid: [
    { message: "안정적이고 든든한 하루.", advice: "꾸준한 집중이 필요한 일에 집중.", luckyColor: "탄", luckyColorHex: "#D2B48C", luckyDirection: "중앙", luckyActivity: "꾸준한 집중 작업", shareText: "조용히 쌓아가는 하루 🌍" },
    { message: "위장과 소화에 주의. 의식적으로 식사.", advice: "따뜻하게 조리된 음식을 선택.", luckyColor: "옐로", luckyColorHex: "#F2CA50", luckyDirection: "서남쪽", luckyActivity: "마인드풀 이팅", shareText: "안에서부터 영양 공급 🍲" },
    { message: "유지보수에 좋은 날.", advice: "신경 쓰이던 작은 것 하나를 고치세요.", luckyColor: "카키", luckyColorHex: "#C3B091", luckyDirection: "중앙", luckyActivity: "고치기와 유지하기", shareText: "유지보수의 날 🔧🌍" },
    { message: "적당한 사교 에너지. 소그룹 선호.", advice: "식사하며 의미 있는 대화를 나누세요.", luckyColor: "캐러멜", luckyColorHex: "#FFD59A", luckyDirection: "서남쪽", luckyActivity: "소규모 모임", shareText: "소그룹 에너지 🌍💛" },
    { message: "오늘 몸이 지혜를 담고 있습니다.", advice: "몸에서 뭔가 이상하면 주의.", luckyColor: "허니", luckyColorHex: "#EB9605", luckyDirection: "중앙", luckyActivity: "바디 스캔", shareText: "몸의 소리에 귀 기울이는 날 🌍" },
    { message: "재정적 안정은 유지되지만 성장엔 인내.", advice: "불필요한 구독을 검토하고 줄이세요.", luckyColor: "베이지", luckyColorHex: "#F5F5DC", luckyDirection: "중앙", luckyActivity: "재정 리뷰", shareText: "현명한 돈 관리의 날 💰🌍" },
    { message: "관계는 거창한 말보다 실천적 행동.", advice: "누군가를 위해 도움이 되는 일을 하세요.", luckyColor: "모래", luckyColorHex: "#C2B280", luckyDirection: "서남쪽", luckyActivity: "봉사 실천", shareText: "행동으로 보여주는 사랑 🤲" },
    { message: "읽기보다 하면서 배우는 날.", advice: "공부보다 실습.", luckyColor: "점토", luckyColorHex: "#B66A50", luckyDirection: "중앙", luckyActivity: "실전 학습", shareText: "해보면서 배우기 🌍🔨" },
    { message: "당신의 의견이 무게를 가지는 날.", advice: "피드백을 감싸지 마세요.", luckyColor: "앰버", luckyColorHex: "#FFBF00", luckyDirection: "동북쪽", luckyActivity: "정직한 피드백", shareText: "솔직한 토 에너지 🌍💬" },
    { message: "물질세계에 감사하는 날.", advice: "축복을 목록으로 적어보세요.", luckyColor: "골드", luckyColorHex: "#F2CA50", luckyDirection: "중앙", luckyActivity: "감사 일기", shareText: "축복을 세는 날 🌍🙏" },
  ], low: [
    { message: "기반이 흔들리는 느낌. 느낌이지 사실이 아닙니다.", advice: "맨발을 땅에 대고 깊이 호흡.", luckyColor: "브라운", luckyColorHex: "#8B4513", luckyDirection: "중앙", luckyActivity: "그라운딩 운동", shareText: "땅에 발을 딛고 🌍🧘" },
    { message: "안전에 대한 걱정이 올라올 수 있습니다.", advice: "통장 잔고를 확인해서 마음을 진정.", luckyColor: "다크 샌드", luckyColorHex: "#967117", luckyDirection: "서남쪽", luckyActivity: "걱정을 사실로 확인", shareText: "사실이 두려움을 이긴다 🌍" },
    { message: "소화 시스템이 민감한 날.", advice: "매운 것, 찬 것, 가공식품을 피하세요.", luckyColor: "탄", luckyColorHex: "#D2B48C", luckyDirection: "중앙", luckyActivity: "부드러운 식사", shareText: "위장에 친절한 날 🍵" },
    { message: "과도한 생각이 행동을 막습니다.", advice: "열 가지 큰 계획 대신 한 가지 작은 일.", luckyColor: "머드", luckyColorHex: "#70543E", luckyDirection: "중앙", luckyActivity: "작은 행동하기", shareText: "한 걸음 > 열 계획 🌍👣" },
    { message: "사회적 에너지 부족. 혼자 충전하라는 신호.", advice: "선택적 약속은 취소하세요.", luckyColor: "흙", luckyColorHex: "#6B4226", luckyDirection: "서남쪽", luckyActivity: "고독과 휴식", shareText: "혼자 충전 모드 🌍🤫" },
    { message: "통제가 중요하게 느껴지지만 오늘은 불가능.", advice: "통제하려던 한 가지를 풀어놓으세요.", luckyColor: "더스트", luckyColorHex: "#B5A642", luckyDirection: "중앙", luckyActivity: "놓아주기 연습", shareText: "통제를 놓다 🌍🙌" },
    { message: "몸이 무겁게 느껴지면 더 가벼운 움직임이 필요.", advice: "달리기보다 천천히 걷기.", luckyColor: "사암", luckyColorHex: "#786D5F", luckyDirection: "중앙", luckyActivity: "가벼운 움직임", shareText: "부드럽게 움직이는 날 🌍🚶" },
    { message: "오래된 패턴이 표면에. 판단 없이 알아차리세요.", advice: "패턴에 이름을 붙이세요.", luckyColor: "다크 앰버", luckyColorHex: "#B8860B", luckyDirection: "서남쪽", luckyActivity: "자기 관찰", shareText: "오래된 패턴을 명확히 보다 🌍👁️" },
    { message: "물질적 욕구가 긴급하게 느껴지지만 사실은 아닙니다.", advice: "구매 전 24시간 기다리세요.", luckyColor: "다크 골드", luckyColorHex: "#AA8C2C", luckyDirection: "중앙", luckyActivity: "의식 있는 소비", shareText: "나에게 충분함이 있다 🌍✨" },
    { message: "토에 수기가 필요한 날. 충분히 수분 섭취.", advice: "평소보다 물을 많이 마시세요.", luckyColor: "젖은 모래", luckyColorHex: "#96856C", luckyDirection: "중앙", luckyActivity: "수분 보충", shareText: "물이 토를 먹인다 💧🌍" },
  ]},
  metal: { high: [
    { message: "정신이 칼날처럼 날카로운 날.", advice: "미루던 결정을 내리세요.", luckyColor: "실버", luckyColorHex: "#C0C0C0", luckyDirection: "서쪽", luckyActivity: "의사 결정", shareText: "명확성 모드 — 금의 기운 ⚔️" },
    { message: "정밀함과 품질이 최고조.", advice: "양보다 질. 적게 하되 완벽하게.", luckyColor: "플래티넘", luckyColorHex: "#E5E4E2", luckyDirection: "서쪽", luckyActivity: "장인 정신", shareText: "정밀함 최고 ✨" },
    { message: "정의의 에너지가 강합니다.", advice: "불편하더라도 공정한 것을 지지.", luckyColor: "스틸", luckyColorHex: "#71797E", luckyDirection: "서북쪽", luckyActivity: "공정함 옹호", shareText: "정의가 명확한 날 ⚖️" },
    { message: "금전 감각이 절정.", advice: "협상, 비교, 투자 검토를 하세요.", luckyColor: "골드실버", luckyColorHex: "#CFB53B", luckyDirection: "서쪽", luckyActivity: "재정 분석", shareText: "돈 감각 최고 💰" },
    { message: "당신의 말에 권위가 실립니다.", advice: "발표, 제안, 피칭하세요.", luckyColor: "화이트 골드", luckyColorHex: "#EBEBEB", luckyDirection: "서쪽", luckyActivity: "발표와 제안", shareText: "권위 모드 ON 🎤" },
    { message: "놓아주기가 강력한 날.", advice: "한 가지를 깔끔하게 끝내세요.", luckyColor: "크롬", luckyColorHex: "#DBE4EB", luckyDirection: "서북쪽", luckyActivity: "마무리와 정리", shareText: "깔끔한 절단만 ✂️" },
    { message: "디테일 지향성 최고조.", advice: "교정, 디버깅, 감사, 검사하세요.", luckyColor: "티타늄", luckyColorHex: "#878681", luckyDirection: "서쪽", luckyActivity: "감사와 검토", shareText: "오늘 내 눈을 피하는 것은 없다 🔍" },
    { message: "규율이 자연스럽게 찾아옵니다.", advice: "가장 두려운 일을 먼저 처리.", luckyColor: "아이언", luckyColorHex: "#4A4A4A", luckyDirection: "서쪽", luckyActivity: "어려운 일 먼저", shareText: "규율이 나의 무기 ⚔️" },
    { message: "미적 감각이 고조됩니다.", advice: "어디서든 질서와 아름다움을 만드세요.", luckyColor: "진주", luckyColorHex: "#FDEEF4", luckyDirection: "서북쪽", luckyActivity: "미적 배치", shareText: "아름다움과 질서 ✨" },
    { message: "계약, 합의, 약속이 유리한 날.", advice: "서명하고, 동의하고, 약속하세요.", luckyColor: "실버", luckyColorHex: "#C0C0C0", luckyDirection: "서쪽", luckyActivity: "공식 계약", shareText: "약속의 에너지 📝✨" },
  ], mid: [
    { message: "꾸준한 분석 에너지.", advice: "체크리스트를 체계적으로 처리.", luckyColor: "그레이", luckyColorHex: "#808080", luckyDirection: "서쪽", luckyActivity: "체계적 작업", shareText: "안정적인 금 에너지 ⚙️" },
    { message: "폐와 피부에 주의. 깊이 호흡하고 보습.", advice: "5분간 밖에 나가 신선한 공기를.", luckyColor: "라이트 그레이", luckyColorHex: "#D3D3D3", luckyDirection: "서쪽", luckyActivity: "호흡 운동", shareText: "깊은 호흡 🌬️" },
    { message: "디지털과 물리적 공간을 정리하기 좋은 날.", advice: "사진 20장 삭제, 이메일 5개 구독 취소.", luckyColor: "실버", luckyColorHex: "#C0C0C0", luckyDirection: "서북쪽", luckyActivity: "디지털 정리", shareText: "디지털 디톡스의 날 🗂️" },
    { message: "대화에 간결함이 도움됩니다.", advice: "말하기 전에 다듬으세요.", luckyColor: "퓨터", luckyColorHex: "#96A8A1", luckyDirection: "서쪽", luckyActivity: "간결한 소통", shareText: "적은 말, 더 많은 의미 ✂️" },
    { message: "적당한 규율. 영웅적 행동보다 습관에 사용.", advice: "루틴을 유지하세요.", luckyColor: "알루미늄", luckyColorHex: "#A9A9A9", luckyDirection: "서쪽", luckyActivity: "루틴 유지", shareText: "루틴이 힘이다 ⚙️" },
    { message: "비판적인 눈은 자기 개선에, 타인에겐 부드럽게.", advice: "자신의 작업을 비판하고 남을 칭찬.", luckyColor: "니켈", luckyColorHex: "#727472", luckyDirection: "서북쪽", luckyActivity: "자기 개선", shareText: "나를 다듬고, 남을 인정하기 ⚖️" },
    { message: "향수가 올라올 수 있습니다. 과거를 존중하되 집착하지 마세요.", advice: "오래된 사진을 보고 미소 짓고 앞을 보세요.", luckyColor: "앤틱 실버", luckyColorHex: "#7B8788", luckyDirection: "서쪽", luckyActivity: "추억 돌아보기", shareText: "아름다운 추억, 더 밝은 미래 🪞" },
    { message: "저축에 좋고, 지출엔 조심.", advice: "소액을 저축으로 이체하세요.", luckyColor: "코인 골드", luckyColorHex: "#CD7F32", luckyDirection: "서쪽", luckyActivity: "저축하기", shareText: "저축 모드 💰" },
    { message: "몸이 오늘 구조를 필요로 합니다.", advice: "일정한 시간에 세 끼.", luckyColor: "슬레이트", luckyColorHex: "#708090", luckyDirection: "서쪽", luckyActivity: "구조적 루틴", shareText: "구조 = 건강 🕐" },
    { message: "계약과 서류에 좋은 에너지.", advice: "서명하는 모든 것의 세부 조항을 읽으세요.", luckyColor: "스틸 블루", luckyColorHex: "#4682B4", luckyDirection: "서북쪽", luckyActivity: "서류와 계약", shareText: "세부 조항을 읽는 날 📄🔍" },
  ], low: [
    { message: "내면의 비평가가 시끄러운 날.", advice: "자기비판 하나마다 진짜 강점 하나로 반박.", luckyColor: "다크 그레이", luckyColorHex: "#4A4A4A", luckyDirection: "서쪽", luckyActivity: "자기 연민 연습", shareText: "비평가 음소거 🤍" },
    { message: "슬픔이나 상실감이 올라올 수 있습니다.", advice: "이유 없이 슬퍼도 괜찮습니다.", luckyColor: "차콜", luckyColorHex: "#36454F", luckyDirection: "서쪽", luckyActivity: "감정 해방", shareText: "가을의 에너지 🍂" },
    { message: "호흡이 답답하게 느껴집니다.", advice: "4-7-8 호흡법을 실천하세요.", luckyColor: "안개", luckyColorHex: "#C0C0C0", luckyDirection: "서북쪽", luckyActivity: "호흡법", shareText: "호흡을 확장 🌬️" },
    { message: "완벽주의가 진행을 막습니다. 80%면 충분.", advice: "80% 완성도로 제출하세요.", luckyColor: "재", luckyColorHex: "#B2BEB5", luckyDirection: "서쪽", luckyActivity: "불완전한 작업 마무리", shareText: "80% 완성 > 100% 계획 📤" },
    { message: "고립이 유혹하지만 연결이 치유합니다.", advice: "문자 한 통, 전화 한 통.", luckyColor: "스톰 그레이", luckyColorHex: "#717D7E", luckyDirection: "서쪽", luckyActivity: "작은 연결", shareText: "한 번의 연락이 모든 걸 바꾼다 📱" },
    { message: "경직이 마찰을 만드는 날.", advice: "누군가가 자기 방식으로 하도록 허락.", luckyColor: "스모크", luckyColorHex: "#738276", luckyDirection: "서북쪽", luckyActivity: "유연성 연습", shareText: "금의 날카로운 면을 부드럽게 🌊" },
    { message: "피부와 알레르기가 나타날 수 있습니다.", advice: "피부에 수분을 공급하고 가공식품을 줄이세요.", luckyColor: "페일 실버", luckyColorHex: "#D4D4D4", luckyDirection: "서쪽", luckyActivity: "피부 관리", shareText: "금 원소가 피부를 통해 말한다 🧴" },
    { message: "가치가 불분명하게 느껴지는 날.", advice: "낮은 날에 인생을 재평가하지 마세요.", luckyColor: "건메탈", luckyColorHex: "#2C3539", luckyDirection: "서쪽", luckyActivity: "재평가 없이 쉬기", shareText: "오늘 인생 결정 안 함 😌" },
    { message: "기준이 불가능하게 높게 느껴집니다.", advice: "뭔가에서 평범해도 된다는 허락을 자신에게.", luckyColor: "납", luckyColorHex: "#6B6B6B", luckyDirection: "서북쪽", luckyActivity: "불완전할 자격 허용", shareText: "불완전해도 된다 🤍" },
    { message: "금이 무거운 날. 짐을 가볍게 하세요.", advice: "필요 없는 것 하나를 버리세요.", luckyColor: "변색 실버", luckyColorHex: "#8A8D8F", luckyDirection: "서쪽", luckyActivity: "짐 줄이기", shareText: "무게를 덜다 🪶" },
  ]},
  water: { high: [
    { message: "직감이 강처럼 흐릅니다 — 강력하고, 절대적으로 맞습니다.", advice: "두 번 생각하지 말고 첫 직감을 따르세요.", luckyColor: "딥 블루", luckyColorHex: "#3B82F6", luckyDirection: "북쪽", luckyActivity: "직감 따르기", shareText: "직감 최대 🌊" },
    { message: "지혜가 당신을 통해 흐릅니다.", advice: "관점을 자유롭게 나누세요.", luckyColor: "네이비", luckyColorHex: "#000080", luckyDirection: "북쪽", luckyActivity: "멘토링과 조언", shareText: "지혜 오버플로우 🌊🧠" },
    { message: "적응력 최고. 바위 주위로 흐르는 물처럼.", advice: "막혔을 때 둘러가세요.", luckyColor: "오션 블루", luckyColorHex: "#4F93CE", luckyDirection: "서북쪽", luckyActivity: "창의적 문제 해결", shareText: "물은 길을 찾는다 🌊💪" },
    { message: "깊은 연결이 형성되는 날.", advice: "'정말 어떻게 지내?'라고 물어보고 들으세요.", luckyColor: "아쿠아마린", luckyColorHex: "#7FFFD4", luckyDirection: "북쪽", luckyActivity: "깊은 대화", shareText: "깊은 대화 에너지 🌊💙" },
    { message: "숨겨진 지식이 표면으로.", advice: "반복되는 생각에 주의하세요.", luckyColor: "사파이어", luckyColorHex: "#0F52BA", luckyDirection: "북쪽", luckyActivity: "꿈 일기", shareText: "숨겨진 진실 표면화 🌊🔮" },
    { message: "금전 흐름이 개선됩니다.", advice: "평소와 다른 수입원에 열려 있으세요.", luckyColor: "세룰리안", luckyColorHex: "#007BA7", luckyDirection: "서북쪽", luckyActivity: "재정적 개방성", shareText: "돈이 흘러들어온다 💰🌊" },
    { message: "감성 지능 최고. 공간과 사람을 완벽하게 읽습니다.", advice: "이 능력으로 관계를 치유하거나 거래를 성사시키세요.", luckyColor: "틸", luckyColorHex: "#008080", luckyDirection: "북쪽", luckyActivity: "감정 내비게이션", shareText: "분위기 파악 완벽 🌊👁️" },
    { message: "소통이 시처럼 흐릅니다.", advice: "중요한 것을 쓰세요.", luckyColor: "로얄 블루", luckyColorHex: "#4169E1", luckyDirection: "북쪽", luckyActivity: "글쓰기", shareText: "말이 물처럼 흐른다 🌊✍️" },
    { message: "치유 에너지가 강합니다.", advice: "쉬면 치유가 빨라지는 날.", luckyColor: "스카이 블루", luckyColorHex: "#87CEEB", luckyDirection: "서북쪽", luckyActivity: "적극적 휴식과 치유", shareText: "치유 가속 🌊💙" },
    { message: "몰입 상태에 접근 가능한 날.", advice: "2시간을 방해받지 않는 창작 시간으로.", luckyColor: "코발트", luckyColorHex: "#0047AB", luckyDirection: "북쪽", luckyActivity: "깊은 창작 작업", shareText: "몰입 상태 활성화 🌊🎨" },
  ], mid: [
    { message: "부드럽고 사색적인 에너지.", advice: "반응하기 전에 성찰하세요.", luckyColor: "라이트 블루", luckyColorHex: "#ADD8E6", luckyDirection: "북쪽", luckyActivity: "성찰과 일기", shareText: "성찰의 날 🌊" },
    { message: "신장과 방광 에너지에 지원이 필요합니다.", advice: "물 8잔을 마시세요.", luckyColor: "블루", luckyColorHex: "#3B82F6", luckyDirection: "북쪽", luckyActivity: "수분 충전", shareText: "수분 충전 우선 💧" },
    { message: "적당한 직감. 확인 후 행동하세요.", advice: "믿되 확인하세요.", luckyColor: "페리윙클", luckyColorHex: "#CCCCFF", luckyDirection: "서북쪽", luckyActivity: "균형 잡힌 결정", shareText: "믿되 확인 🌊🔍" },
    { message: "새로운 정보를 흡수하기 좋은 날.", advice: "읽고, 팟캐스트 듣고, 배우세요.", luckyColor: "아이스 블루", luckyColorHex: "#99CCFF", luckyDirection: "북쪽", luckyActivity: "학습과 공부", shareText: "지식 흡수 모드 📚🌊" },
    { message: "관계가 편안한 속도로 흐릅니다.", advice: "평온함을 즐기세요.", luckyColor: "파우더 블루", luckyColorHex: "#B0E0E6", luckyDirection: "북쪽", luckyActivity: "편안한 사교", shareText: "잔잔한 물결 🌊😌" },
    { message: "수면의 질이 평소보다 중요합니다.", advice: "취침 30분 전 화면 보지 마세요.", luckyColor: "미드나이트 블루", luckyColorHex: "#191970", luckyDirection: "북쪽", luckyActivity: "수면 최적화", shareText: "깊은 잠이 치유한다 🌊🌙" },
    { message: "충동 구매를 피하세요.", advice: "$50 이상 구매 전 24시간 기다리세요.", luckyColor: "스틸 블루", luckyColorHex: "#4682B4", luckyDirection: "서북쪽", luckyActivity: "의식 있는 소비", shareText: "의식 있는 소비의 날 💰" },
    { message: "공감 능력이 신뢰할 만한 날.", advice: "공감적으로 들되 경계를 유지.", luckyColor: "아쿠아", luckyColorHex: "#00CED1", luckyDirection: "북쪽", luckyActivity: "공감적 경청", shareText: "공감 ON, 흡수 OFF 🌊🛡️" },
    { message: "신체적 유연성이 좋은 날.", advice: "요가, 수영, 또는 긴 뜨거운 샤워.", luckyColor: "터쿼이즈", luckyColorHex: "#40E0D0", luckyDirection: "북쪽", luckyActivity: "스트레칭 또는 수영", shareText: "몸이 흐르는 날 🌊🧘" },
    { message: "기억이 지혜를 담고 있는 날.", advice: "비슷한 과거 상황을 떠올려보세요.", luckyColor: "슬레이트 블루", luckyColorHex: "#6A5ACD", luckyDirection: "서북쪽", luckyActivity: "과거 지혜 활용", shareText: "과거의 지혜, 현재의 힘 🌊" },
  ], low: [
    { message: "수기가 정체되는 날. 감정이 탁합니다.", advice: "몸을 움직여 수기를 움직이세요.", luckyColor: "다크 블루", luckyColorHex: "#00008B", luckyDirection: "북쪽", luckyActivity: "정체 해소를 위한 움직임", shareText: "탁한 물은 움직이면 맑아진다 🌊🚶" },
    { message: "두려움이 올라오지만 신뢰할 수 없습니다.", advice: "두려움을 소리 내어 이름 붙이세요.", luckyColor: "미드나이트", luckyColorHex: "#191970", luckyDirection: "북쪽", luckyActivity: "두려움 인정하기", shareText: "두려움에 이름을 붙여 길들이기 🌊💪" },
    { message: "신장 에너지가 낮습니다.", advice: "허리를 따뜻하게 유지하세요.", luckyColor: "잉크 블루", luckyColorHex: "#0A1628", luckyDirection: "북쪽", luckyActivity: "따뜻하게 유지", shareText: "수 원소를 따뜻하게 🫖🌊" },
    { message: "소통이 오해받을 수 있습니다.", advice: "의도를 과하게 전달하세요.", luckyColor: "스톰 블루", luckyColorHex: "#507786", luckyDirection: "서북쪽", luckyActivity: "명확한 소통", shareText: "의미하는 바를 명확히 🌊💬" },
    { message: "감정적 과부하 가능.", advice: "가능하면 물 근처에서 혼자 시간을.", luckyColor: "딥 시", luckyColorHex: "#003366", luckyDirection: "북쪽", luckyActivity: "물 근처에서 혼자", shareText: "물을 찾아 리셋 🌊" },
    { message: "미루기가 수의 그림자.", advice: "10분 타이머를 맞추고 시작하세요.", luckyColor: "블루 그레이", luckyColorHex: "#6699CC", luckyDirection: "북쪽", luckyActivity: "타이머 작업 스프린트", shareText: "10분. 그게 전부. 🌊⏱️" },
    { message: "고립이 불필요하게 깊어집니다.", advice: "카페, 공원 같이 사람이 있는 곳으로.", luckyColor: "트와일라잇", luckyColorHex: "#4E5180", luckyDirection: "북쪽", luckyActivity: "주변에 사람이 있는 곳", shareText: "완전히 혼자는 아닌 🌊☕" },
    { message: "꿈이 생생하고 불안할 수 있습니다.", advice: "깨자마자 꿈을 적으세요.", luckyColor: "나이트 블루", luckyColorHex: "#1B2838", luckyDirection: "서북쪽", luckyActivity: "꿈 일기", shareText: "꿈이 오늘 밤 말한다 🌊🌙" },
    { message: "지혜에 접근이 안 되는 느낌.", advice: "통찰을 강요하지 마세요. 남의 지혜를 읽으세요.", luckyColor: "오션 다크", luckyColorHex: "#023E73", luckyDirection: "북쪽", luckyActivity: "지혜 문학 읽기", shareText: "지혜를 빌리는 날 📚🌊" },
    { message: "몸이 차가운 것은 수기가 낮다는 신호.", advice: "따뜻한 목욕이나 샤워를 하세요.", luckyColor: "프로스트 블루", luckyColorHex: "#7EB6D0", luckyDirection: "북쪽", luckyActivity: "따뜻한 의식", shareText: "따뜻하게 🛁🌊" },
  ]},
};
